"""Auto-migrated bulk hidden test cases."""

def generate_cases(*, count: int, seed: int, start_index: int):
    del seed
    cases = [
        {'input': '["y"]', 'expected_output': '"y"'},
        {'input': '["ljlnsakf", "ljlzevjpkuy", "knkmkp", "ljlkftjtv", "ljlsnibjvoijy", "ljlujkeczb"]', 'expected_output': '""'},
        {'input': '["eooqzeslu", "rqlwwhyk", ""]', 'expected_output': '""'},
        {'input': '["grkodrruupj", "grkodrrhzkmcuptut", "grkodrr", "grkodrr", "grkodrrauful", "grkodrrmptudiemyi", "fbc", "igipbnrdo"]', 'expected_output': '""'},
        {'input': '["wdyjbuybtt", "anonmhyzdue", "fjqtmjfhjp", "odmbgyc", "fvcvgp", "qye"]', 'expected_output': '""'},
        {'input': '["okvqkysdqacp", "oyiggg", "ovwokqjawin", "ysgkgyulwyi", "oywe", "oualayjitq"]', 'expected_output': '""'},
        {'input': '["mjov", "mjovqxwoclansmvf", "mjovnukbxpd", "mjovymciqd", "mjovamz"]', 'expected_output': '"mjov"'},
        {'input': '["", "fontwtnjrk", "yfazr"]', 'expected_output': '""'},
        {'input': '["azbyfqnkwhfsh", "azbyfij", "azbyfv", "wreib", "azbyffgxehsc", "xmhbbq", "azbyfgmvxr", "gydypuojax", ""]', 'expected_output': '""'},
        {'input': '["isembjvbjg", "fqovfjlzeat", "fqovfjloijtcvqup", "vowsgpmana", "fqovfjle", "fqovfjlnknmmvqez", "fqovfjlaw", "fqovfjlxdfyws", "fqovfjlckacxn", "fqovfjlivciohqigh"]', 'expected_output': '""'},
        {'input': '["jmgpbsaavwgyze", "jmp", "axufaoneivr", "jm", "jmmzcybnvx", "jmcdlqslijgq"]', 'expected_output': '""'},
        {'input': '["fvdcevlnuoualjeei", "nkirasvzhf", "fvdcevlxn", "fvdcevl", "fvdcevl", "fvdcevloocvan", "fvdcevltlkowlzfonsr"]', 'expected_output': '""'},
        {'input': '["kz", "", "fhgzulvzb", "nbfxpfsdgnl", "enzq"]', 'expected_output': '""'},
        {'input': '["juftonihaawgq", "juftoomkraqrrdw", "sn", "jufto", "gzlhizyrh", "juftovvdnnuziun"]', 'expected_output': '""'},
        {'input': '["qpdispzgaz"]', 'expected_output': '"qpdispzgaz"'},
        {'input': '["ojzkmhvi", "rk", "orqgclfxapppt", "owypbbgx", "oemfqvf", "o", "oj", "opvux", "ougptl", "oxrgtvndvbkvh"]', 'expected_output': '""'},
        {'input': '["xkvihleyvugq", "xkvihley", "xkvihleyeroiawnfi", "xkvihleylopqpqzhtr", "xkvihleyr", "xkvihleysdph", "xkvihleybadikgkzlcr", "xkvihleyvjxaittpbs"]', 'expected_output': '"xkvihley"'},
        {'input': '["fvftvxwcde", "ybqeaj", "gzjzbd", "zrzufvvphuzh", "fpwkucszii", "s", "di", "aboi", "p"]', 'expected_output': '""'},
        {'input': '["jernwzxapz", "zixth", "zixpdocvzznsd", "zixovj", "zixwdpgqdjx", "zixveiqrncqphi", "zixdxxrtexgvv", "zixow", "zixrwmmnc"]', 'expected_output': '""'},
        {'input': '["", "ybt", "hqkebjkprwsu"]', 'expected_output': '""'},
        {'input': '["iiourugjuoc", "ibtlmpu", "skugljd", "ih", "x", "igglij"]', 'expected_output': '""'},
        {'input': '["vbafhr", "speohsxqcgnoh", "speskncvtkqrn", "fbz", "speukziyooxlgm", "spebpcbvka"]', 'expected_output': '""'},
        {'input': '["gkoertlje", "zk", "gkoertoqxfpp", "gkoertahasatpxtxiv"]', 'expected_output': '""'},
        {'input': '["jchm", "jchbboxmoib", "jchqchpo", "jchlvdlycqpf", "jchhx", "", "jchirhnb", "flem"]', 'expected_output': '""'},
        {'input': '["dcyiyjpsh", "dcyiyjpst", "dcyiyjpsiyhkzv", "dcyiyjpsnhfysx", "dcyiyjpsttbwryajr", "dcyiyjpst", "enlomzem"]', 'expected_output': '""'},
        {'input': '["pntufqy", "lef"]', 'expected_output': '""'},
        {'input': '["mg", "keapjeux", "wbm", "cbhjltuwyq", "so", "kdwcxwgimr", "vwyryden", "nsrbhokbfcj", "p", "ucaiyaocqog"]', 'expected_output': '""'},
        {'input': '["hvljfeejjiuvap"]', 'expected_output': '"hvljfeejjiuvap"'},
        {'input': '["lbjtbvafrmf"]', 'expected_output': '"lbjtbvafrmf"'},
        {'input': '["gehectlhwmjsnggr", "gehectgzkk", "xjlshplrln", "gehectgzmchufbwduz", "gehectgzhmoww", "gehectnchahmjlym", "cioikmslknp"]', 'expected_output': '""'},
        {'input': '["tcdehhm"]', 'expected_output': '"tcdehhm"'},
        {'input': '["ynurwzfic", "ynurwzfithrmb", "ynurwzfinfrus", "ynurwzfipftb", "ynurwzfia", "ynurwzfiqxtoptaaq", "ynurwzfizfcuduz", "ynurwzfihtgsrfbhf", "ynurwzfieqqmsmyvat", "ynurwzfigyenxxnp"]', 'expected_output': '"ynurwzfi"'},
        {'input': '["qeck", "qebfm", "qeurkoohx", "qejwrdccupvoeo"]', 'expected_output': '"qe"'},
        {'input': '["okzvkblvb", "okwchxgsqh", "uovm"]', 'expected_output': '""'},
        {'input': '["jfpnumxfbhrpi", "lyr"]', 'expected_output': '""'},
        {'input': '["fvltaqv", "fvltabcyivvdxsct", "tdkkdpvrxbz", "fvltackxzwdt", "fvltahpmfglzw"]', 'expected_output': '""'},
        {'input': '["see", "sba", "svdewjeyf", "skdcxavlizn", "urqmbqfhn", "svhojhqgfsfw", "sjntbflgiol"]', 'expected_output': '""'},
        {'input': '["tphlhq", "tvbjmzhibicx", "thxwidmlwgpwe", "tqtg"]', 'expected_output': '"t"'},
        {'input': '["ktdickxagdo", "ktdicrcyspze"]', 'expected_output': '"ktdic"'},
        {'input': '["qsvshr", "vglmxzjxeylgmcvgec", "vglmxzjxqjvsayxn", "vglmxzjxswjcamsoaapj", "vglmxzjxsnmdpqfpcxe", "vglmxzjxw", "vglmxzjxxh", "vglmxzjxkkhgusfhnvlg", "a"]', 'expected_output': '""'},
        {'input': '["kifrwqrczv", "kifrwepzqp", "kifrwndjxbhsudzx"]', 'expected_output': '"kifrw"'},
        {'input': '["olgpdeqtckfpub", "ollneutlccxyu", "kcf", "ol", "olsawibacm", "olxbha"]', 'expected_output': '""'},
        {'input': '["nusiqkejlqy", "nusiqkcpipnteibx", "nusiqktfne", "nusiqkod", "nusiqkqmv", "nusiqkoc", "nusiqktjxa", ""]', 'expected_output': '""'},
        {'input': '["bgzlihtvjkk", "brgy", "bgnlbapjef", "bbwlgjud", "boyyxanvi", "bhsuqan", "bw", "bwkougy", "bnbvuervswi", ""]', 'expected_output': '""'},
        {'input': '["whb", "feogccjsev", "feogcyajgmsmaeic", "feogcxjmqknjkkur"]', 'expected_output': '""'},
        {'input': '["rpfpnozh", "rpfpnozheknaliuok", "rpfpnozhblitzmhvu", "rpfpnozhhhgdmjksqiyh", "rpfpnozhssfqxd", "rpfpnozhvypvttjybs", "zd"]', 'expected_output': '""'},
        {'input': '["uhmq", "r", "uhmqbhe", "uhmq", "uhmqejjmirbcnljw", "uhmqpqxkuaxbshmc", "uhmqrdtpp", "uhmqtlrto"]', 'expected_output': '""'},
        {'input': '["ccrnksbxasms", "cfzqi", "cr", "cswpuyxtmwsvu", "y", "cotbycmb"]', 'expected_output': '""'},
        {'input': '["ywhwrqffberq"]', 'expected_output': '"ywhwrqffberq"'},
        {'input': '["nfbeapbyrecfayaznq", "nfbeapbyeahsv", "nfbeapbyxfhrzebm", "nfbeapbyfvsbf", "nfbeapbyat", "nfbeapbya", "nfbeapbyd", "nfbeapbyhdddgtxjxwp", "qyxlhbpwvhq", "nfbeapbyuxh"]', 'expected_output': '""'},
        {'input': '["xzoylu", "xncfkzg", "rkmubctlbt", "mzsktwjxl", "xvznzkthp", "x", "xsgyso"]', 'expected_output': '""'},
        {'input': '["toacazyeo", "toay", "toarcjssa"]', 'expected_output': '"toa"'},
        {'input': '["ntzyslm", "ntzyslmerkirj", "ntzyslmxun", "ntzyslmyyziqemmn", "ntzyslmlyjcp", "ntzyslmbjply"]', 'expected_output': '"ntzyslm"'},
        {'input': '["yzcuhri", "yzcuh", "yzcuhnnxtkjnldcr", "yzcuhikpoe", "yzcuhdjxjo", "yzcuhqdrwnxexcfgd", "yzcuhrlhumtlwlwzg", "", "yzcuhrbn"]', 'expected_output': '""'},
        {'input': '["nkcwrofp", "n", "nhc"]', 'expected_output': '"n"'},
        {'input': '["awsqeq", "fibm", "fibmuihr"]', 'expected_output': '""'},
        {'input': '["hgxwk"]', 'expected_output': '"hgxwk"'},
        {'input': '["rxiwa", "kc", "czk", "abktmpi", "qhhijady", "opznrrhr", "al", "dtucuiv"]', 'expected_output': '""'},
        {'input': '["wlmbtgstxqoqh", "wlr"]', 'expected_output': '"wl"'},
        {'input': '["uwfcykimgkpykhvvae", "uwfcykimlwvavv", "uwfcykimdllqmvnnke", ""]', 'expected_output': '""'},
        {'input': '["kkspz"]', 'expected_output': '"kkspz"'},
        {'input': '["umjhfedqgh", "umjhfedqlxsx", "umjhfedquz", "umjhfedqowrmrorbrwgg", "umjhfedqsciwff", "umjhfedqluvwwbjvvyui", "qdldo", "umjhfedqd", "usnoh"]', 'expected_output': '""'},
        {'input': '["cokxlrtzbpan", "rx", "cxmvjlnu"]', 'expected_output': '""'},
        {'input': '["rnpaufmlz", "mhcbiguxkf", "mhcbiguxzc", "fymki", "mhcbiguxsyfedun", "oesmudooof", "mhcbiguxysylzd", "mhcbiguxwafeguzcq", "mhcbiguxptzr"]', 'expected_output': '""'},
        {'input': '["itulgfsal", "ifch"]', 'expected_output': '"i"'},
        {'input': '["nuhkzkqmpeclnmda", "nuhkzkoobys", "nuhkzkfjeaaajw", "nuhkzkywszpd", "berj"]', 'expected_output': '""'},
        {'input': '["o"]', 'expected_output': '"o"'},
        {'input': '["bxrkukpn", "bod", "bpcux", "bysnnqkycff"]', 'expected_output': '"b"'},
        {'input': '["ilatxtu", "ilabctn", "tcjjzyg", "ilajuhmcvqn", "ilaelzsrhgs", "cvdohva", "ilarclrd", "ilafuseyxkb", "ilalbing"]', 'expected_output': '""'},
        {'input': '["zvggimzejty", "zvgqtto", "zvguo"]', 'expected_output': '"zvg"'},
        {'input': '["tywkdxwcxqflfe", "tywkdxwcbwizgqpklr", "tywkdxwcmvmukmzvjit", "tywkdxwcltekslktnkz", "wmjimxovidyb", "s"]', 'expected_output': '""'},
        {'input': '["bxmtdkph"]', 'expected_output': '"bxmtdkph"'},
        {'input': '["dtkvzi", "zefdxnfygchxunma", "zefdxzpozboxbyb", "zefdx", "zefdxuatu", "zefdxt", "sacjej"]', 'expected_output': '""'},
        {'input': '["fzoyhp", "gmusktymrhzi", "f", "eajfbpbferc", "fulcbidw"]', 'expected_output': '""'},
        {'input': '["whymfbrzd", "whyvccxib", "whyrqxnnjbw", "whywqvwdpialdsv", "whyemex", "vldpsiv", "whyil"]', 'expected_output': '""'},
        {'input': '["ggqhdykkrhpfbkcvvwm", "ggqhdykktcvlruaw", "ggqhdykkyfrasbhmntl", "ggqhdykkafsrad", "ggqhdykkmhzpkdnxle", "ggqhdykkmhwvcpgv", "ggqhdykksgnl", "scp"]', 'expected_output': '""'},
        {'input': '["lxkzwxzbnldf", "lxkzwxzzhrzefgvmsc", "bp", "lxkzwxzf", "lxkzwxzyxqbr", "lxkzwxzfqimmheba", "lxkzwxzonrpwnyosw", "lxkzwxzjbsqhfcum"]', 'expected_output': '""'},
        {'input': '["dlfd", "gklre", "gklo", "buktazurmep"]', 'expected_output': '""'},
        {'input': '["idthxrndvqvtbgamgoq", "idthxrndhpwlqmkab", "meljxgoewta", "vlicctwkqiw", "idthxrndxgahi"]', 'expected_output': '""'},
        {'input': '["wljxzw", "hsost", "qhuhk", "qhuqp", "qhunwxkawe", "sixwjgoex", "qhuxtfmoxoy"]', 'expected_output': '""'},
        {'input': '["mjohppelqstesby", "mjohppelgmersg", "mjohppelvtqr", "mjohppel", "gmuloqiike", "mjohppelebcn", "mjohppeldqwnanpba", "mjohppeles"]', 'expected_output': '""'},
        {'input': '["bptdniwxhs", "bptmvo", "bptpsuii", "bptpyfzn", "kay", "bpteqrvz", "bptkkb", "bptiecowxoxlm", "bpttlzjf", "ccx"]', 'expected_output': '""'},
        {'input': '["tffgcxoklgqr"]', 'expected_output': '"tffgcxoklgqr"'},
        {'input': '["tunqhyubl", "iwavkllpjdcdgf", "iwad"]', 'expected_output': '""'},
        {'input': '["uotersjykkhfok", "uobnhpu", "uowbkuztiy"]', 'expected_output': '"uo"'},
        {'input': '["kvapziwwerovjihjfz", "zjfocazwyul", "kvapziwwwyvzvjmx", "kvapziww", "kvapziwwtz", "kvapziwwqpjxab", "kvapziwwoojdwpj", "kvapziwwgbuz", "d"]', 'expected_output': '""'},
        {'input': '["ajptdwrxungqsvdupp", "ajptdwrzlxrbdpmfddb", "ajptdwrodzndswupuvm", "ajptdwrichawr", "ajptdwreq", "ajptdwrdcwlcndvopbv", "ajptdwrmf", "ajptdwrgbqvgnwf"]', 'expected_output': '"ajptdwr"'},
        {'input': '["sczdjrmrtlhgatxsy", "sczdjrlzuadwvhuf", "sczdjrect", "sczdjrx", "", "ay", "ypzxtwviw", "sczdjr", "sczdjrmflgzyctis"]', 'expected_output': '""'},
        {'input': '["vwoivknl", "vwoqkfn", "yryehqzexz", "vwoabmrraet", "vwo", "hx", "vwoxjt", "vwoxha"]', 'expected_output': '""'},
        {'input': '["baugkejkynbt", "btug", "bhqwzvz", "bpajbqx", "bkcxknhqqr", "bxpdjmtrdx"]', 'expected_output': '"b"'},
        {'input': '["wntlqlnmgxhesksl", "wntlqlnbc"]', 'expected_output': '"wntlqln"'},
        {'input': '["riaziwkr", "ri", "riopnpikszcz", "risjpmgnjdj"]', 'expected_output': '"ri"'},
        {'input': '["vkckrpgztcqqfttgud", "kz", "b", "zf", "vkckrpgndz", "vkckrpg", "mjhtokdft"]', 'expected_output': '""'},
        {'input': '["bpupbdslfzjmzjqu", "bpupbdduolyrkt", "bpupbdqnnrynyf"]', 'expected_output': '"bpupbd"'},
        {'input': '["fonigznnan", "fzooxjzgwgc", "fpubwkfbilj", "flb"]', 'expected_output': '"f"'},
        {'input': '["yifdwywrgckzpkd"]', 'expected_output': '"yifdwywrgckzpkd"'},
        {'input': '["", "hidgtewkvksp", "", "tptskj", "zsededb", "qezdeflnmj", "plpyvxbubytl"]', 'expected_output': '""'},
        {'input': '["ohkiuagvtjkvvni", "ohkietwijeeohan", "ohkimth", "ohkinrcescqjpzf"]', 'expected_output': '"ohki"'},
        {'input': '["trapplcdafoqnn", "trapmywuvgfjfpg", "trapqfnuncl", "trapvcxbmuynwl", "avuvnvttiup"]', 'expected_output': '""'},
        {'input': '["fbfvibbqpxl", "fbfvzbgonp", "fbfvdvhiycikt", "fbfvakflfxvtrae", "fbfvysljd", "mbdxbv", "fbfvqwap", "fbfvtab", "", "fbfvkdyx"]', 'expected_output': '""'},
        {'input': '["yhwdfocdy"]', 'expected_output': '"yhwdfocdy"'},
        {'input': '["ixrovi", "bulhwgs", "bulhwgzqjwo", "bulhwgfghnxusos", "bulhwggrjpdce", "egsj", "gk", "bulhwgqoznwjtorr", "bulhwgrgrfrxeebem"]', 'expected_output': '""'},
        {'input': '["ibsnfbgxrv"]', 'expected_output': '"ibsnfbgxrv"'},
        {'input': '["rjpedimtrkshp", "oauvbc", "df", "rjpeujrr", "cupsuadyvdef"]', 'expected_output': '""'},
        {'input': '[""]', 'expected_output': '""'},
        {'input': '["odsbtwjao", "odsbtwja"]', 'expected_output': '"odsbtwja"'},
        {'input': '["rlmiveyf", "invwvswqvw"]', 'expected_output': '""'},
        {'input': '["ltcmfhpmc", "ltcmfhpwluujfejff", "ltcmfhpx"]', 'expected_output': '"ltcmfhp"'},
        {'input': '["wqenfkaitcz", "wvjmizypjypv", "wxyxxgkake", "wyq", "wlz", "wrpuzax", "wcmoqgcddnxgh", "wvvhmnpwvhct"]', 'expected_output': '"w"'},
        {'input': '["ouxsh", "xelsojmpytyw", "ym", "rlyrpsgxt", "xelsohaohikea", "xelsoaza", "ohj", "xelsoty", "xelsofxldnvp"]', 'expected_output': '""'},
        {'input': '["tvdwjsp"]', 'expected_output': '"tvdwjsp"'},
        {'input': '["wlccxdkelsxjgshan", "wlccxderli", "wlccxd", "wlccxdkyarj", "wlccxdxlpcdoopg", "wlccxduacsbcr", "nfewsqzdboj"]', 'expected_output': '""'},
        {'input': '["krznqipy", "vbuymqtzwz"]', 'expected_output': '""'},
        {'input': '["hlvayteel", "eyavrkqzvgtsqwb", "eyavjutrana", "eyav", "eyavaszfvprqbmi", "eyavnrencagzcr", "eyavyettcrodg"]', 'expected_output': '""'},
        {'input': '["dlghrc", "", "vhirfcwhotlsrf", "qnd", "vhiipsgq"]', 'expected_output': '""'},
        {'input': '["japfaiogc", "g", "nivbxrmyb", "ssdmexefoxmd", "nivbxrmlpdvrlvgdia", "nivbxrmszdbt", "nivbxrmxkbyyc", "nivbxrmwymkze", "", "nivbxrmf"]', 'expected_output': '""'},
        {'input': '["zygahczsddyansygd", "", "zygahcohylf", "pdflzzfazuqn", "jmu", "bfrf"]', 'expected_output': '""'},
        {'input': '["sztrvr"]', 'expected_output': '"sztrvr"'},
        {'input': '["pvqcspyby"]', 'expected_output': '"pvqcspyby"'},
        {'input': '["woupnwgscbvmizonh", "woupnwisiouqnauo", "woupnwnltcobghm"]', 'expected_output': '"woupnw"'},
        {'input': '["jrrxlkaigoou", ""]', 'expected_output': '""'},
        {'input': '["potdvvycvzgrnagdze", "potdvvsifz"]', 'expected_output': '"potdvv"'},
        {'input': '["qgegajiew", "qgegajipmlldd", "qgegajionblqei", "qgegajihdyexg", "qgegajiqqdgvuwdbvf"]', 'expected_output': '"qgegaji"'},
        {'input': '["zbcwvyzqlnl", "zbcwvyzqfso", "zbcwvyzqiaqebkfvqxg", "zbcwvyzqryolombgdlh", "zbcwvyzqnrlbtbrcwmn", "zbcwvyzqheihibjmfpas"]', 'expected_output': '"zbcwvyzq"'},
        {'input': '["caxnxdoea", "cacjcr", "catzhbmronpk", "fz", "caciufalmjm", "cadxxvties"]', 'expected_output': '""'},
        {'input': '["ymzjktxmf", "zveajvlhzjunl", "zveajrvna", "zveajrmybosp", "zveajogunz", "zveajb", ""]', 'expected_output': '""'},
        {'input': '["", "jjzusodzttbkfv", "jjzusodeixmtlptmbp", "jjzusopm", "nybtw", "jjzusoqgycyaxjy", "jjzusov", "jjzuso", "jjzusophpjqll"]', 'expected_output': '""'},
        {'input': '["qrhdhsmvhytdh", "qrhrjahnxjtbvo", "qrhjdxicbmxpf", "qrhtit"]', 'expected_output': '"qrh"'},
        {'input': '["tflbumjwmmusfefrz", "tflbumqnsziwslbjv", "tflbumxhtypxty", "knrjgecpb", "s"]', 'expected_output': '""'},
        {'input': '["vtizqbxbrtdsfgii", "vtizeszgnhisdbuy"]', 'expected_output': '"vtiz"'},
        {'input': '["wsjdknlzzzk", "wsjdkpshwoyvgpssz", "gyqirk", "wsjdkce", "wsjdkwytwutynie", "wsjdkj", "wsjdkibmkkihvyaz", "wsjdkhvfyuuixkp"]', 'expected_output': '""'},
        {'input': '["nimxzmhbwlvdq", "wpwv", "shecv", "nimy", "nimozqfrqowftv"]', 'expected_output': '""'},
        {'input': '["jkurkyzkiwrplgskxw", "jkurkyzmh", "jkurkyztbkocy", "jkurkyzpocknw", "jkurkyzu", "jkurkyzgkfrwcrpsn"]', 'expected_output': '"jkurkyz"'},
        {'input': '["iknhfmsqnpq", "iknhfmpqvbpywm", "hvypxwaol", "iknhfmjxoisdqfvfx", "ydwygfaunj", "iknhfmzhrlyggti"]', 'expected_output': '""'},
        {'input': '["huqcgmmcurx", "yl", "", "ylyen", "yldkxkf", "ylixujylfzek", "ylojietxegsr"]', 'expected_output': '""'},
        {'input': '["xfdqqy", "xfdfd", "xfdtdlspqths", "xfdtwzxo", "momzd", "xfdstpuywxbqds", "xfdclaqkcxovaeo"]', 'expected_output': '""'},
        {'input': '["vcgzk", "vcgzawiw", "vcgzqelfzmnzhq"]', 'expected_output': '"vcgz"'},
        {'input': '["hfqidrue", "hfqidr", "fsr", "hfqidrzagsspscwngh", "hfqidrvvfzhm", "l", "akiuoqax", "hfqidrdtxb", "hfqidrogzn", "hfqidrwunj"]', 'expected_output': '""'},
        {'input': '["qrjvovleifds", "qrjvjzsylksprasv", "vhcxd", "qrjv", "qrjvbpxeeqs", "qrjvin", "qrjv"]', 'expected_output': '""'},
        {'input': '["cvqwpl", "cvc", "d", "cooypsum", "cvnyfosbr", "cvauhj"]', 'expected_output': '""'},
        {'input': '["xuygrdnbahfrni", "xuygrdnpgoxsxzbp", "xuygrdnulvqsfksy", "xuygrdn", "xuygrdnfnteign", "fjbtfjct", "ppbofdr"]', 'expected_output': '""'},
        {'input': '["bbqbvmjejuw", "zlaayomdew", "ocxwuklaccv", "", "nhoczzbvtk", "b"]', 'expected_output': '""'},
        {'input': '["ibxcrrfrsfec", "jyvl", "ojkerkrlbm", "ozxkmovwr", "ijzqdwndgzhx"]', 'expected_output': '""'},
        {'input': '["wqjvdbmemzaivugazwqy", "wqjvdbmeiim", "wqjvdbmehko", "wqjvdbmeenlu", "wqjvdbme", "wqjvdbmexumnfxelnuf"]', 'expected_output': '"wqjvdbme"'},
        {'input': '["up", "upspayhed"]', 'expected_output': '"up"'},
        {'input': '["stsevpyqyepy", "stsevpy", "stsevpywsp", "stsevpyistibdo"]', 'expected_output': '"stsevpy"'},
        {'input': '["iapcpmwc", "iajktnuxvwypeu", "iapptgu", "iajv"]', 'expected_output': '"ia"'},
        {'input': '["zkjyboa"]', 'expected_output': '"zkjyboa"'},
        {'input': '["fptmvui"]', 'expected_output': '"fptmvui"'},
        {'input': '["bi", "lkvcnfmzmtzzpndntv", "lkvcnfmkjrtlo", "lkvcnfmjy", "lkvcnfm", "lkvcnfmymdwic", "r", "lkvcnfmkqmaipyat", "lkvcnfmnhdktctrz", "lkvcnfmuwhcuabmnre"]', 'expected_output': '""'},
        {'input': '["phmjyvgk", "axmrlywqc", "lodojywg", "axmrloumwzhipknc", "axmrlmgpjunaz", "axmrlqogqmpmumexf", "axmrlssjbhqphosij", "axmrlgzvnhm", "axmrlpxpthcntabn", "axmrlstdvutxz"]', 'expected_output': '""'},
        {'input': '["pngi", "ftfhgkuyua", "todgko", "ykk", "c", "fhybcdlvcn", "ddt"]', 'expected_output': '""'},
        {'input': '["tkglljdgeertvyudokw", "tkglljdpondkq"]', 'expected_output': '"tkglljd"'},
        {'input': '["gbynoi", "gbjga", "gbsaacrth", "gbbxa"]', 'expected_output': '"gb"'},
        {'input': '["", "sb", "rviepjrkoejpchkqqdb", "rviepjrkzyje"]', 'expected_output': '""'},
        {'input': '["vcdjva", "vcez", "rymr"]', 'expected_output': '""'},
        {'input': '["zfsrnyatxywmqkn", "zfsrnyadwy", "zfsrnyaokm", "jtg", "zfsrnyammkn", "wl", "zfsrnyajuaz"]', 'expected_output': '""'},
        {'input': '["osnrheenrvv", "osnrheybswhs", "osnrhegakjkdzsyesl", "osnrhefm", "osnrhegr", "osnrhejxpjprnixtn"]', 'expected_output': '"osnrhe"'},
        {'input': '["", "bptcgewzansgr", "bptcgjxgquvbwr", "u", "bptcgbfrz"]', 'expected_output': '""'},
        {'input': '["wqjydgane", "wqjydganetwtk", "wqjydganyesnzzrzkrm", "wqjydganmdqfhlrbr", "wqjydganguvbwrvk", "zliqlku"]', 'expected_output': '""'},
        {'input': '["vtbzhynvu", "vtbtoixo", "vtbasvcq", "vtbmvseomciedgx"]', 'expected_output': '"vtb"'},
        {'input': '["ujayvdgu", "ujayvdp"]', 'expected_output': '"ujayvd"'},
        {'input': '["pxogytzaazlb", "n", "pznqmkx", "pof", "pvcuqvbor", "phmpwgddwat"]', 'expected_output': '""'},
        {'input': '["aterwanryxlje", "qwyoroc", "aterwanegvetfwffyp", "aterwanzlnprttauwr", "aterwanyhcrfxjg"]', 'expected_output': '""'},
        {'input': '["jyktmaxgtth", "f", "fghztaljn", "fxqqhuwzejikr", "facfq", "fdvqixsa", "foobhuv", "frctgxipof"]', 'expected_output': '""'},
        {'input': '["ukhotlxkwdadyryun", "ukhotlend", "ukhotlu", "ukhotlmghowxghzy", "ukhotlnicdgtqp", "ukhotlisdvziq", "ukhotltdvyxhpnzgi", "ukhotlvf", "ukhotlmfuqkbskzekx", "ukhotleoxcxncssja"]', 'expected_output': '"ukhotl"'},
        {'input': '["jeawmlieez", "jeacfahfmhqmnh"]', 'expected_output': '"jea"'},
        {'input': '["ncgqos"]', 'expected_output': '"ncgqos"'},
        {'input': '["ytwpvus", "wysuzvpbisr", "tbqwgrqlml", "rpwsa", "tbqwgrsxpk", "tbqwgrgq", "tbqwgrdnqmqwuqf", "tbqwgrc", "tbqwgrrcfmbejo", "tbqwgrpccreol"]', 'expected_output': '""'},
        {'input': '["cefv", "uic", "mjqbadbz", "ehwfktf", "beqdan", "pvexspokblv", ""]', 'expected_output': '""'},
        {'input': '["ilgegxmpnzgu", "ilroslitfo", "ilmlhccwzz", "ilbkyjrpvhvuz", "iljkgdlolo", "ilqhgmnzz", "ilgnm", "ilapxhkklkjq"]', 'expected_output': '"il"'},
        {'input': '["lvkxj", "mmvevfut", "mmvevcd", "mmvevuprxs", "k", "mmvevwoyuls", "mmvevxyae", "ggynluimdqj", "mmvevawh"]', 'expected_output': '""'},
        {'input': '["hdix", "vg"]', 'expected_output': '""'},
        {'input': '["cnlkd", "yijalinx", "cnlkd", "cnlkduuzhjb", "cnlkdbmiuuhopfu", "cnlkdbvvc", "cnlkdosbi", "cnlkdehdb"]', 'expected_output': '""'},
        {'input': '["ndluunmsv", "ndfedrmysbxirt", "ndstrmcvzkde", "ndmntiuylwvhf", "ndttgfagejvcus", "ndplbwmwxg"]', 'expected_output': '"nd"'},
        {'input': '["whhe"]', 'expected_output': '"whhe"'},
        {'input': '["yasbrkyxu", "a"]', 'expected_output': '""'},
        {'input': '["vx", "zzuezwu", "mwuljphmf", "nmrwxdbyr", "shsedjgtig", "ulnyuufwrh", "xzgqusqmzld"]', 'expected_output': '""'},
        {'input': '["m", "dchjywlbfcgprugxbqf", "gffop", "dbzmdsibdbfz", "dchjywlbp", "dchjywlbauzmizsl", "dchjywlbstwvd", "dchjywlbd", "dchjywlbo", "dchjywlbi"]', 'expected_output': '""'},
        {'input': '["gapli", "uf", "gapkpu", "msyaqbkxosz", "gapogglabe", "gaikofiuuxr", "gapszesgnbr"]', 'expected_output': '""'},
        {'input': '["fymwnolsfmb", "fymwnolsugpvax", "fymwnolspvs", "fymwnolsgcusslwderdj", "fymwnolsv", "fymwnolsepvquxwals", "fymwnols", "fymwnolsy"]', 'expected_output': '"fymwnols"'},
        {'input': '["zqbmgmmapxvquta", "zqbmpkwscm"]', 'expected_output': '"zqbm"'},
        {'input': '["fpssbjr", "vzjbmn", "vbqq", "vybddlxsp"]', 'expected_output': '""'},
        {'input': '["xsnqfsrlhagpyrke", "xsnqfsrkfdiypsvuey", "xsnqfsrsakcodjqfnb", "xsnqfsrvtbeyvgvng"]', 'expected_output': '"xsnqfsr"'},
        {'input': '["bxlnflrlwj", "ixyjrdmwb", "ihcjpnrb", "lrnixccrolv", "yqv", "kmzg", "soubf", "wnizvi", "nhed"]', 'expected_output': '""'},
        {'input': '["aaeuayyygdjzur", "aaeuayy", "aaeuayylvnqqt", "aaeuayyivddzoina", "aaeuayygnqqg", "aaeuayyfcgyyynjaz"]', 'expected_output': '"aaeuayy"'},
        {'input': '["nijvegzgjrphc", "nijvegzlltbkggjc", "nijvegzjunwhv", "nijvegzlpjfw", "nijvegzsmr", "z", "nijvegzegmlmdwd"]', 'expected_output': '""'},
        {'input': '["afasrqile", "bhzvcn", "fbbd", "nzihomg", "whzfptnk"]', 'expected_output': '""'},
        {'input': '["g", "qwxyohxd", "n", "dlrvcud"]', 'expected_output': '""'},
        {'input': '["towzcfh", "doqbmxh", "tocbdk", "toydhzcwi", "tof", "ylkbo", "fsybec", "to", "tolihapagmx", "aqib"]', 'expected_output': '""'},
        {'input': '["tgxdbahoudh", "tgxduglnfxj", "tgxdylgvs", "iyco", "tgxdzawutgwj"]', 'expected_output': '""'},
        {'input': '["yjrigyhi", "yjr", "yjreeqiojhpt"]', 'expected_output': '"yjr"'},
        {'input': '["snxfrnbcahjcdomvozkx", "snxfrnbclhrff", "snxfrnbccaln", "snxfrnbcikedysgvfnab"]', 'expected_output': '"snxfrnbc"'},
        {'input': '["unqqcas"]', 'expected_output': '"unqqcas"'},
        {'input': '["emhnno", "yrr", "emhnuer", "xr", "emhnblyidxatwzw", "emhnxmuiinouzhyo", "emhnvd", "emhnz"]', 'expected_output': '""'},
        {'input': '["hrkkm", "hrkkmvgwoeoyr", "hrkkmtlafhlgbzwhk", "hrkkma", "hrkkmh"]', 'expected_output': '"hrkkm"'},
        {'input': '["bwuxdjti", "byi", "bdqrykwjex", "bcfysaykgtp", "bnorjmhgi", "", "bz", "bga", "zchrr"]', 'expected_output': '""'},
        {'input': '["ghsgritsmsuo", "ghkhk", "gho", "ghrantasihiy", "ghcev", "koqclqqkvo", "ghfkxqg"]', 'expected_output': '""'},
        {'input': '["wauvoxftkggix", "wauvoxezairh", "milmy", "wauvoxnc", "wauvoxg", "wauvoxancwnnlbjmeq", "wauvoxohoaunbz", "wauvoxhokfzaxg", "wauvoxigncridfdu"]', 'expected_output': '""'},
        {'input': '["yewecamzlebhde", "ltv", "yewecambac", "yewecamgkltrz", "jvkze"]', 'expected_output': '""'},
        {'input': '["hvhdcaeirrn", "rlshvipcmod", "u", "fesrt", "phv", "hhmyrbabprks"]', 'expected_output': '""'},
        {'input': '["colcmwftpe", "colcuw"]', 'expected_output': '"colc"'},
        {'input': '["kwchoqhozpacyy", "kwcho", "kwchoxvmurjt", "kwchojg", "kwchorwhw", "tzggkzeazd", "kwchogd"]', 'expected_output': '""'},
        {'input': '["xn", "q", "cuetkhdrfgo", "boyhaimgl", "guqpitzpn", "ouxqe", "roijdbnezv", "rvaappuua", "zwohtsfaxdt", "mxstazet"]', 'expected_output': '""'},
        {'input': '["anoka", "anujeeinp", "anlscbbvdd", "anp", "relx", "anodgwtzabzjou", "anoxzcrijigf"]', 'expected_output': '""'},
        {'input': '["kmlovvnpzi"]', 'expected_output': '"kmlovvnpzi"'},
        {'input': '["pmhpobly", "pmhpokewxvc", "pmhpozerzygfear", "pmhpoixgbnbl"]', 'expected_output': '"pmhpo"'},
        {'input': '["xullqdjnddkg", "cxy", "x", "xgrjyzldjzouf", "xbqmwvvf"]', 'expected_output': '""'},
        {'input': '["xmuvgikp", "xmuvgimtvlemgt", "xmuvgilqvaxyi", "xmuvgitrimkvn", "xmuvgi", "wypc", "qsfdo"]', 'expected_output': '""'},
        {'input': '["htmpaqfaese", "xykbkwymekqx", "lghl", "kdvnvssxve", "mklfnhzdb", "dlv", "uitbte"]', 'expected_output': '""'},
        {'input': '["vwsywhdr", "ykjhmbyzvj", "vwsywuwatmswob", "vwsywhrd", "vwsywyafwnijvrxd", "vwsywwllsk", "vwsywr", "mummjhsqhm", "vwsywte", "vwsywrgbpkzvriuu"]', 'expected_output': '""'},
        {'input': '["rvugtmetbarqcf", "rvunarstadm"]', 'expected_output': '"rvu"'},
        {'input': '["uaarvty", "uslaf", "urfqusqjx", "gbybadquiq", "ukgupoynhuzh", "uknczlovvpd", "pmxivse", "ue"]', 'expected_output': '""'},
        {'input': '["ojvl", "yjunkxnq", "fpqkscbqio", "qnf", "o", "f", "g"]', 'expected_output': '""'},
        {'input': '["kdobytteeqvoy", "kdobyexfrfeizx", "kdobyqxxs", "kdobyfugaunpqwgh", "kdobyjtolkaduix", "kdobyzciqoahfozig"]', 'expected_output': '"kdoby"'},
        {'input': '["bszsclnxjmppnjrjqi"]', 'expected_output': '"bszsclnxjmppnjrjqi"'},
        {'input': '["kwvkrofeaabaebc", "xqfxvooqh", "kwvkrowqlwuov", "kwvkroeu"]', 'expected_output': '""'},
        {'input': '["kpbpjxvnz", "kbmmbc", "kneuyuxuyw", "kavwrqrofkys", "krbp"]', 'expected_output': '"k"'},
        {'input': '["sptwfw"]', 'expected_output': '"sptwfw"'},
        {'input': '["fwesbvbrcjnppmdtlx", ""]', 'expected_output': '""'},
        {'input': '["spjjktsltrifhqa", "spjpalbox", "spjcpbdy", "spjqnlwleoj"]', 'expected_output': '"spj"'},
        {'input': '["rqdvwdnwjmfkfizf"]', 'expected_output': '"rqdvwdnwjmfkfizf"'},
        {'input': '["qkjdsxneoqsy", "qkjms", "qkfl", "qk", "qkjjpaxlepe", "prvmumd", "j", "qkoiheksspnj", "gj"]', 'expected_output': '""'},
        {'input': '["clyyi", "lterajumqpoekme", "lteramfqabatm", "lterah", "lterapusf", "lterapgz", "lteracigdlxu", "lteratzybcybeps", "ltera", "lteratact"]', 'expected_output': '""'},
        {'input': '["wprbmnkxm", "d", "wprbmnktzrkymdqcq"]', 'expected_output': '""'},
        {'input': '["kri"]', 'expected_output': '"kri"'},
        {'input': '["q", "qdowvblzppsq", "qdud", "qchgjsoil", "hxektfqt", "htnjhioib", "qknztfzwcdzbe", "qzkhitocnxjf"]', 'expected_output': '""'},
        {'input': '["txrbsuulpvfcy", "txrbsuul", "txrbsuuleyzxrhlmjhu", "txrbsuuluwoy", "hvigbo", "", "hsafyxnc", "txrbsuulntdzhb", "txrbsuulimdwk"]', 'expected_output': '""'},
        {'input': '["gherqgi", "umk", "ueb", "uh", "ubs"]', 'expected_output': '""'},
        {'input': '["xrg"]', 'expected_output': '"xrg"'},
        {'input': '["ailxbpswyk", "plqamvoo", "plqamvooy", "plqamvooe", "plqamvoobzssx", "plqamvoobzdglf", "plqamvoozbhhfq", "rronoyw", "plqamvoolnlamv", "plqamvoowgr"]', 'expected_output': '""'},
        {'input': '["rvrxbweizxbncq", "rvrxgtdv", "rvrxx", "rvrxq", "jivmd", "rvrxyxccjnab", "m"]', 'expected_output': '""'},
        {'input': '["ocxqucy", "phxujvxk", "cfxas", "ciaw"]', 'expected_output': '""'},
        {'input': '["vmgqsdvgvc", "ehkywev", "yhyzphhmdmd", "xnti", "auultuufe"]', 'expected_output': '""'},
        {'input': '["ayjmvgoamgmh", "ayjmviq", "ayjmvyy", "ayjmvnfgvg"]', 'expected_output': '"ayjmv"'},
        {'input': '["casommbl", "qvaxrzoub", "qvaxrz", "qvaxrznjqnyfzo", "qvaxrzw", "qvaxrzqvu", "qvaxrzb"]', 'expected_output': '""'},
        {'input': '["seqvildvtxvitqvrp", "seqvildvukmb", "yhdqifdlmy", "seqvildvlzcdfqtcvrtr", "seqvildvqdjjedsta", "q", "seqvildvxzszawh"]', 'expected_output': '""'},
        {'input': '["hiitu", "xeoawfijx", "hbjeiehw"]', 'expected_output': '""'},
        {'input': '["pxjiiedz", "pxdkscgzpeevm", "pxhpauh", "odoiyowj", "pxthignw", "pxe", "aux", "lbmwcx", "pxflj"]', 'expected_output': '""'},
        {'input': '["ztgexci"]', 'expected_output': '"ztgexci"'},
        {'input': '["zekf", "", "xewavaguehel"]', 'expected_output': '""'},
        {'input': '["idboujd", "idboujltokokwro", "idbouzcofpzk", "idboux", "idboujsb", "idbouzr", "idbounpmsxvlvbagv", "idboudlncx", "idboucptggfbfxaz"]', 'expected_output': '"idbou"'},
        {'input': '["ijlkcnja", "ijlkcnwqufcabixhu", "fyg", "ijlkcnsglzisy", "ijlkcnmvx", "wnftpkhghe", "ijlkcnanqvialnzud", "ijlkcnaavio", "ijlkcnusezgltfqitj", "ijlkcngvbjr"]', 'expected_output': '""'},
        {'input': '["kbvjklyhhbm", "s", "kbvjxwz", "kbvjppvngbfzf", "kbvjrjirjnwlbaom", "jxjt", "kbvjsveglnzzuzvj"]', 'expected_output': '""'},
        {'input': '["fmsuavy", "hgpu", "fmwbhmy"]', 'expected_output': '""'},
        {'input': '["izfxatpcn", "izkhcuolzae", "izha", "izkodhusw", "izzdyskzxx", "izaqkv", "izebm"]', 'expected_output': '"iz"'},
        {'input': '["q", "fcoblhwflz", "i", "epmilnrpasws"]', 'expected_output': '""'},
        {'input': '["xgzh", "lqvtvwpaldm"]', 'expected_output': '""'},
        {'input': '["ofjhybfxfhkvpvubiq", "ofjhybye", "ofjhybbwoz", "ofjhybah", "ofjhybetlzzvroiri", "drnqcf"]', 'expected_output': '""'},
        {'input': '["wd", "nzngpzqytt", "qbtcr", "sebxmi", "xglt", "cyve", "oe", "fyqww"]', 'expected_output': '""'},
        {'input': '["apanxtmdjnwf", "vhjss", "vhjjwjsploxivh", "vhjpodyuwd", "eidpbab", "vhjazhmsz", "vhjevm", "vhjfgntqhfxw", "bpd"]', 'expected_output': '""'},
        {'input': '["dhusmmisnxehgsuhddqx", "wlpkjrec", "iifdxa", "dhusmmisdrlccqewb", "itymmh", "dhusmmis", "dhusmmis", "p"]', 'expected_output': '""'},
        {'input': '["kcsiygtjrsnz", "cfjezhkq", "pwpribi", "ptkbwzjkmr", "mkcbjsuvvcnm", "ynhpvkysywkp", "cfjezhidlxteq", "cwpdp", "cfjezhjftfz"]', 'expected_output': '""'},
        {'input': '["wnnqrojwq", "wnnqrojwmskmpkf", "wnnqrojwbzmw", "wnnqrojwfwa", "wnnqrojw", "wnnqrojwgtcpymdwjeb", "wnnqrojwccbbb", "wnnqrojwtpwfcfsasnx"]', 'expected_output': '"wnnqrojw"'},
        {'input': '["", "utctqtaszjgfteq", "utclxd", "eiyattkvoe", "utcr"]', 'expected_output': '""'},
        {'input': '["jqpyxhrovjdsk"]', 'expected_output': '"jqpyxhrovjdsk"'},
        {'input': '["fvcznktnhuuhrtl", "spjbalwvn", "fvcznktnv"]', 'expected_output': '""'},
        {'input': '[""]', 'expected_output': '""'},
        {'input': '["bofnuxwep"]', 'expected_output': '"bofnuxwep"'},
        {'input': '["zxmbqptfdluixwr", "zxmbzzlult", "zxmbhfnku", "zxmbdcecfqcgcpb", "icpeylylbkvg", "qk", "tthloweoc", "zxmbfb"]', 'expected_output': '""'},
        {'input': '["vvafvxplute", "vvafvxbuhv", "vvafvx", "vvafvx", "nwiwyz", "vvafvx", "vvafvxmivh", "vvafvxgztrpztsl", "vvafvxlxmrzcid", "vvafvxsnmm"]', 'expected_output': '""'},
        {'input': '["qzcqrcbr", "qzcqrcbulloqnvy", "qzcqrcbxuehfa"]', 'expected_output': '"qzcqrcb"'},
        {'input': '["klyjplpxxwtejpw", "klyjplhk", "klyjpludfjlqcep", "klyjplqgyzrtcmlroy", "klyjply", "klyjplwiv"]', 'expected_output': '"klyjpl"'},
        {'input': '["lb"]', 'expected_output': '"lb"'},
        {'input': '["iglnhmaut", "iglnhmaubhfmdiz", "iglnhmaufr", "iglnhmaujylity", "iglnhmaunud", "uwkymsc", "iglnhmaucavmw", "iglnhmaukytdrmtaz", "iglnhmaujbmc"]', 'expected_output': '""'},
        {'input': '["lqirizqtebreoxnbn", "lqirizqelhkth", "lqirizqgiz", "lcwmbc", "lqirizqgwcoqlohxua", "lqirizqecjs"]', 'expected_output': '"l"'},
        {'input': '["j", "feo"]', 'expected_output': '""'},
        {'input': '["kxytevnkfjbg", "kn", "keuimtcfe", "kgsgkkgxhr", "ktpe", "rgiatu", "kztjfavgvt", "kyxfpa", "kqqlmamsvxzfo"]', 'expected_output': '""'},
        {'input': '["udvp", "rkuieyszwe", "om"]', 'expected_output': '""'},
        {'input': '["vtdprpxrhjrrka", "vtdprpvjzpnqqswoda"]', 'expected_output': '"vtdprp"'},
        {'input': '["cbxxb", "cbxynkh", "ulmoqreyi", "cbx", "cbxosydefbosfkx", "cbx", "cbxpkvigtf", "cbx"]', 'expected_output': '""'},
        {'input': '["tnqkomqago", "tnqkomqabwxzqgx", "blwumddsa", "tnqkomqad", "tnqkomqarz", "faqlg"]', 'expected_output': '""'},
        {'input': '["beovhwtl", "", "bekqggybolrk", "be"]', 'expected_output': '""'},
        {'input': '["iwgoyt", "vgjuoengltrt", "iadbys", "hwsaclhidvo", "iwsrrrc", "yjpblm", "larsdbneogr", "mdspm", "bsqls", "onmgtxusns"]', 'expected_output': '""'},
        {'input': '["tezqmecxrcfhdk", "tezs", "tezaqtlyerpifnn", "tezgtvts", "tezvuifhjy", "h"]', 'expected_output': '""'},
        {'input': '["pgbrngnylnfm", "tfmtrejpjfzrqe", "tfmtrejrzzjkuzk", "tfmtrejypxw", "lwpuiakcgnm", "tfmtrejisgkw", "tfmtrejiunpxgcbih"]', 'expected_output': '""'},
        {'input': '["ebuipx", "eveu", "embztgaiy", "edkjqxane", "wkmvvbll"]', 'expected_output': '""'},
        {'input': '["o", "ohfb", "osjthgyol", "ofc", "eprqclez", "ojdzvtyiqfe", "okywzfhxxveky", "okxq", "olcwefcqgk"]', 'expected_output': '""'},
        {'input': '["qkjbbmwoon", "qkj", "qkj", "qkjwxrnp", "qkjc", "qkj", "z"]', 'expected_output': '""'},
        {'input': '["npjs", "wxzupasuixv"]', 'expected_output': '""'},
        {'input': '["azshszgqsihxbwxz", "bmdwtenzv", "azshj", "azshsqkc", "s"]', 'expected_output': '""'},
        {'input': '["whtseainj", "whtseainvlptpb", "whtseainlybdy", "whtseainkatzzu", "whtseainfa", "eidndnts", "whtseainosdhxwngfrap", "whtseainvajuroalh", ""]', 'expected_output': '""'},
        {'input': '["lonhsgpaxafwmd", "lonlzdixdmcl"]', 'expected_output': '"lon"'},
        {'input': '["akutajnfre", "eapyuryhu", "ayfotuhowd", "eapyurywn", "eapyurypmobnwvlqyo", "eapyuryed"]', 'expected_output': '""'},
        {'input': '["x", "yqitoqysfygo", "cz", "m", "prpgptfhbyy", "mktqrxdppw", "", "oa", "zxomx", "czrqriipwg"]', 'expected_output': '""'},
        {'input': '["ndtqmqzekj", "ndtqmisgvqtrr", "rqjzygfve", "ndtqmtjlzcxdheab"]', 'expected_output': '""'},
        {'input': '["rjyjhdbvu", "okswecjp", "vvmsvwa"]', 'expected_output': '""'},
        {'input': '["xgleuyl"]', 'expected_output': '"xgleuyl"'},
        {'input': '["ydhrqonnopq", "ydhrqrzweglbamfnt", "ydhrqsbkrbggwqg", "pofq", "", "ydhrqfngeqc", "fmpzsxvae"]', 'expected_output': '""'},
        {'input': '["ejysemvorr", "ejysemrhptyym", "ejysemcgrnbnmpkb", "p", "ejysemsimzpbyo", "ejysemli", "ejysemtrnrbeqeque", "ejysemqgtbrcyhndv", "ejysemow"]', 'expected_output': '""'},
        {'input': '["wzdrs", "wzdrpxywutquusc"]', 'expected_output': '"wzdr"'},
        {'input': '["kklqur", "kklqorq", "kklqthraihwnuhhv", "kklqlkcibyueaosl", "kklqxzdldflau", "kklqwo", "kklqmgx"]', 'expected_output': '"kklq"'},
        {'input': '["vrfbcsvmxjpxve", "vrfbcsvmgbdfdpegca", "wltnqakqj", "vrfbcsvmxrpbjesenxu", "vrfbcsvmizbqkkipkt", "xlswurn", "vrfbcsvmdaglsz", "vrfbcsvmrqvbyzbspgmb", "vrfbcsvmvobocagdxvk", "vrfbcsvmlu"]', 'expected_output': '""'},
        {'input': '["uiiff", "bgdxkilfobaydtge", "bgdxkil", "bgdxkilvh", "bgdxkillhdia"]', 'expected_output': '""'},
        {'input': '["djyppqvcm", "djyppqgrf", "djyppqmc", "djyppqajn", "djyppqppmrriltvp", "djyppqpvznqghxhxun", "jmed", "ltcgu"]', 'expected_output': '""'},
        {'input': '["uwyrjvmgzatsalmrff", "man", "uwyrjvmcqvxqxysktl", "uwyrjvms", "sbwbrarckbp", "uwyrjvmrxusmu"]', 'expected_output': '""'},
        {'input': '["cexziediokabagv", "cexziediwzbouabbw"]', 'expected_output': '"cexziedi"'},
        {'input': '["spetmvzwyknhiv", "spetmvzfzbhnu", "spetmvzmmzhnvn", "znsafnvhgpsi", "spetmvzjpbs"]', 'expected_output': '""'},
        {'input': '["fsfyddudanxugimkrng", "umik", "fsfyddudetkfikkjtn", "fsfyddudgmjwsnxidnf"]', 'expected_output': '""'},
        {'input': '["isaltaxytbot", "fboijosrth", "", "hlluvousr", "fbqjyb", "fbzrhmpz", "kc", "oueqsbel", "fbioern"]', 'expected_output': '""'},
        {'input': '["gdxusizsz", "gdxusizmqpcsnwwih", "gdxusiztlcqwfevewb", "dopwme", "gdxusizddcnxitmuf", "gdxusizyq", "gxwlsav", "gdxusizubksotyrps", "gdxusizkhhpkzwssy", "gdxusizfizgeozrwt"]', 'expected_output': '""'},
        {'input': '["mcmzehwvxcv", "mcmzehzvusuqurw", "mcmzehbui", "mcmzehfwcrfvjjp", "mcmzehl", "mcmzehgizb", "mcmzehoumlq", "mcmzehvqjdwit"]', 'expected_output': '"mcmzeh"'},
        {'input': '["soznkxvphiv", "kmwqivt", "kmwqivajgcpcrz", "kmwqivsfdi", "c"]', 'expected_output': '""'},
        {'input': '["iag", "iagzoskrjshrjqx", "gzsadws", "iagag", "iagagzosmztraa", "iagyvi", "iagwkkvciiqa", "tbkb", "iagbstikwxnamk", "jzlwaigiihi"]', 'expected_output': '""'},
        {'input': '["iw", "ichpazy", "czxkfhpv"]', 'expected_output': '""'},
        {'input': '["cxupxnkkpjk", "", "eh"]', 'expected_output': '""'},
        {'input': '["cmhtbdzawfsutluc", "cmhtbdzaqicixb", "cmhtbdzaszftce"]', 'expected_output': '"cmhtbdza"'},
        {'input': '["", "gjvps"]', 'expected_output': '""'},
        {'input': '["jrpwoi", "jrpwoifnqawreyoyv", "jrpwoijcxllo", "jrpwoicjpt"]', 'expected_output': '"jrpwoi"'},
        {'input': '["fana", "owsoikndewszz", "ogzzejmgzazxz", "opuhsq", ""]', 'expected_output': '""'},
        {'input': '["zfrkwdrjt", "lwwjxopepup", "wmwihkvzhmyoak", "wmwihkvqkihkvkmeoal", "wmwihkvh", "wmwihkvhockt", "wmwihkvafu"]', 'expected_output': '""'},
        {'input': '["qijnjwgg", "fmijbpbkumu", "qijnjwggiw", "qijnjwggyitvl"]', 'expected_output': '""'},
        {'input': '["xdxjrvsdb", "xdktunymemrmju", "xdrmvygmx", "xdeqnjdrtkjpjh", "xdtnjhjavf", "xdnnnekmmhn", "xdbb", "xdpwswknr", "xdwyiyqvoem", "xd"]', 'expected_output': '"xd"'},
        {'input': '["pdi", "pdiulhxrky", "pdiegqivxglcewz"]', 'expected_output': '"pdi"'},
        {'input': '["koexsevz", "kovqnncjgmjy", "koqb"]', 'expected_output': '"ko"'},
        {'input': '["grmcyasienkuhhcd", "grmchajon", "grmcuqm", "grmcdcftdwkpxc", "grmcbbodpas"]', 'expected_output': '"grmc"'},
        {'input': '["qfwrh"]', 'expected_output': '"qfwrh"'},
        {'input': '["kxfskjztciyfb", "kx", "lmky", "hvyumcvlkvj", "kxxstcdnrklqjw", "kxfsrgrs", "kxqyjkwsutrnp", "kxuq", "kxisfxrxcbjq", "kxeboeblh"]', 'expected_output': '""'},
        {'input': '["nzocwwlni", "nzqureprnkoniz", "nzvhlu", "nzxyrcm", "nzcqf", "", "oplaqhiyqnjl", "nzn", "hxbnxk", "mapqznbrt"]', 'expected_output': '""'},
        {'input': '["qbtfrlpnye", "fvmvj", "qbthe", "qbtlcmyqzhste", "qbthvf", "qbtdpahlkmi"]', 'expected_output': '""'},
        {'input': '["yfagwyfy", "yfagwyjopesqch"]', 'expected_output': '"yfagwy"'},
        {'input': '["nwsqsqqfa", "hvhuttriz", "vryq", "kuct", "nwsqifyadgpg"]', 'expected_output': '""'},
        {'input': '["kazjlmeeunxtshvq"]', 'expected_output': '"kazjlmeeunxtshvq"'},
        {'input': '["syzitksxzzixa", "syzzqovyv"]', 'expected_output': '"syz"'},
        {'input': '["xvlpae", "gpftzk", "qioinkfgdrr", "", "sy"]', 'expected_output': '""'},
        {'input': '["ptvdvwiez", "zcxhxagyi", "ptvdvwixllcmbh", "lvwzfukcthqt"]', 'expected_output': '""'},
        {'input': '["kxeftwkiaouh"]', 'expected_output': '"kxeftwkiaouh"'},
        {'input': '["zrn", "zicad"]', 'expected_output': '"z"'},
        {'input': '["motrsyhcddhafp", "motrirp", "ft", "motrmmneq", "", "motrsqzxrkscg", "motrockhkyluq", "motrrq"]', 'expected_output': '""'},
        {'input': '["wrxtucelvsqyo", "wrxbdth", "", "wrxp", "wrxljbqxcl", "wrxbpfkj", "wrxwxgxugwo"]', 'expected_output': '""'},
        {'input': '["kdiqr", "kdiqrmjeuv", "kdiqrhuyxnnrr", "kdiqryz", "kdiqrhjxkc", "kdiqruieefkebbk", "ihhyyx"]', 'expected_output': '""'},
        {'input': '["rgyiawfgz"]', 'expected_output': '"rgyiawfgz"'},
        {'input': '["iwbvwmvsnnl", "iwbvwlwyiyisgufv", "ukymhzgc", "iwbvwbe", "iwbvwspjo", "iwbvwyhqrhunlepxm", "iwbvwrcwvwam", "iwbvwaxvjgmfbufk", "ugglx"]', 'expected_output': '""'},
        {'input': '["g", "wteevqqfp", "wteevqwakcdvxidrq", "wteevqmpmksabo", "wteevqotnmtcswpb", "wteevqzevtlpbcybe"]', 'expected_output': '""'},
        {'input': '["icibxaqc", "icibxax", "icibxadb", "icibxaaoqopzbx", "icibxayzkkbax", "icibxankoaisvi"]', 'expected_output': '"icibxa"'},
        {'input': '["hc", "h", "huaz", "hqdtmlapdpsj"]', 'expected_output': '"h"'},
        {'input': '["ceo", "cexzfhwy", "cereqcrqws", "cefjnmuuixmnf", "cemkayy", "cexrtaqfxoerv", "ofukjbp"]', 'expected_output': '""'},
        {'input': '["lfbmcagolehgnzj", "lfbmcadsiiz", "lfbmcadrtnqfcgj"]', 'expected_output': '"lfbmca"'},
        {'input': '["ourvdcmccugmasa", "ourvdcz", "ourvdcwhgzxp", "kf"]', 'expected_output': '""'},
        {'input': '["v"]', 'expected_output': '"v"'},
        {'input': '["gkufjkt", "gkufjkttqsugz", "gkufjkxb", "gkufjkzk", "gkufjkfkubpsirbykh", "gkufjkfqceitmu"]', 'expected_output': '"gkufjk"'},
        {'input': '["yuiksoymoyotgq", "yuiksoymnbwcnewxchnh", "yuiksoymldnzci", "yuiksoymx", "yzfuj", "wd", "huojfzbv"]', 'expected_output': '""'},
        {'input': '["thjtqmydqgjzhirxxdt", "dwxtwftecgao", "thjtqmydqlns", "thjtqmydulfgqiqv", "thjtqmydbccgrigm"]', 'expected_output': '""'},
        {'input': '["ipewci", "dnnehomgm", "vowwt", "vowwoz", "vowwjjoqcnad", "vowwlaqglybmv"]', 'expected_output': '""'},
        {'input': '["kkmtkjnxygzrdhncyiw", "ssdvhoirnpti", "kkmtkjnxo", "kkmtkjnxodmcaebeojog"]', 'expected_output': '""'},
        {'input': '["xtvbvvpfpzg", "mrwqqoiqev", "xtugkisuukq", "xtcl", "coehaiem", "xtfyzt", "xtr"]', 'expected_output': '""'},
        {'input': '["ulomcxp", "go", "ulomcxpixnjlx", "ulomcxprni", "ulomcxpcihtea", "ulomcxpjvspz", "ulomcxpfoanbgrjejtr", "ulomcxpesboqdryq", "ulomcxp", "ulomcxpllgp"]', 'expected_output': '""'},
        {'input': '["jgberztaly", "zjmn", "cprvaih", "jgberztagjmsnqr", "jgberztann"]', 'expected_output': '""'},
        {'input': '["sbkedjwrpaswnzis", "jpokvjjildh", "brta", "xfabemgmgw", "sbkedjwrqjpnrnhgvc"]', 'expected_output': '""'},
        {'input': '["pwafoj", "ivp", "pwgm", "pwvxiour", ""]', 'expected_output': '""'},
        {'input': '["pli", "rdbqvelcptnnmdvir", "rdbqvzddxijfcpg", "rdbqvxn"]', 'expected_output': '""'},
        {'input': '["ugghiv", "yhwjwlcamaq", "yluqmnyiwrbb"]', 'expected_output': '""'},
        {'input': '["xylregcoinfl", "xyzkwdrai", "xylphyrt", "xylzvyoq", "xympwgvobh", "xyadlwdtzu", "xyeymvkddg", "xycktuajgugi", "xyhcfigm", "xyspubisc"]', 'expected_output': '"xy"'},
        {'input': '["foybhzqpwyss", "foybat", "foybdpox", "foyb", "foybjehdiinjayb", "foyby"]', 'expected_output': '"foyb"'},
        {'input': '["taazvcp", "tydly"]', 'expected_output': '"t"'},
        {'input': '["nqvzjepxtmemuaj", "nqvpsgywyuoqpr", "nqvxbrlen", "nqvl", "nqvvuvzhkyxfyj", "nqvrqajunaojeng", "nqvnmeqddj", "yakros", "nqv"]', 'expected_output': '""'},
        {'input': '["ruieusosum", "lsbhrr", "kkrffpwz", "nu", "eiwp", "", "lrrufloa", "uidbz", "kciimwjzddr", "rlf"]', 'expected_output': '""'},
        {'input': '["chfpxlmvaldhy", "chfirh", "chferbdb", "chfl", "chfnldhnqhqrtqk", "chfesedhko", "chfzhimh"]', 'expected_output': '"chf"'},
        {'input': '["cdseynzw", "jvhjrxors", "cnb", "c"]', 'expected_output': '""'},
        {'input': '["lfwrtouq", "lfwheeaxjhvgot", "lfwxyczurp", "lfw", "lfwfsupfbzomn", "lfwqaxhhlsquwd", "lfwbbmcnqfcjbmv"]', 'expected_output': '"lfw"'},
        {'input': '["mnpnvbdiadgqnvy", "mnpnvbdtymectjsmb", "mnpnvbdcsxhatzz", "mnpnvbdflyrjoyhpg", "mnpnvbdxh", "mnpnvbdvchwtkvevmr", "ykgddkbxh"]', 'expected_output': '""'},
        {'input': '["i", "ikvcwmcdy", "itpplahixnknr", "irltmvpnmcgx", "quvvqnxwdktm", "i", "crc", "iiuhrhpb"]', 'expected_output': '""'},
        {'input': '["edqntya", "zmmwk"]', 'expected_output': '""'},
        {'input': '["g", "voc", "dyoc", "jyeia", "csvkipi", "uzglza"]', 'expected_output': '""'},
        {'input': '["bsivqwrng", "miwekepq", "", "irzml"]', 'expected_output': '""'},
        {'input': '["qobkuyhgdkq", "qobkudtxr", "qobkupzxzmi", "qobkuedtdc", "qobkutaum", "qobku"]', 'expected_output': '"qobku"'},
        {'input': '["ldafopiicxy", "ldafopiijnqof", "miouq", "ldafopiichnhy", "ldafopii", "ldafopiiqhneuhphwti", "ldafopiiocxbdx", "ldafopii"]', 'expected_output': '""'},
        {'input': '["drsragxcbrlpenev", "drsrayrcatlzxqs", "vferqqkatpx"]', 'expected_output': '""'},
        {'input': '["yytgaokmr", "bn", "yytgeitwh", "yytgobdlxqluqn", "yytgjaevxjkhzq"]', 'expected_output': '""'},
        {'input': '["pqraa", "pckcgxajdax"]', 'expected_output': '"p"'},
        {'input': '["vkjvqtzs", "f", "xqnemqbnyk", "oqlkgtsuzym", "qnuolpd", "zlne"]', 'expected_output': '""'},
        {'input': '["fztawcburpmg", "fz", "fzbvyhldkbwd", "fzaiqpef", "fzei"]', 'expected_output': '"fz"'},
        {'input': '["acypjyldjryd", "hqsnvvn", "ydc", "tzuhutmsh", "hqobcos", ""]', 'expected_output': '""'},
        {'input': '["jdpeyvtlax", "tm", "oxn", "rytdjlwc", "whp", "hedhacm", "sw", "gslpqfyzglw", "wywlosizjk"]', 'expected_output': '""'},
        {'input': '["ds", "dszvyahf", "dsoslteoclzpxg", "dsd"]', 'expected_output': '"ds"'},
        {'input': '["znefdyvnanduqrh", "zneynwzduooihop", "tllrxwua", "zne", "znefwnh"]', 'expected_output': '""'},
        {'input': '["ahwcugl", "wvfbtjylppp", "", "fzjvtwn", "w", "ayetldzgxti", "sm", "brb", "hcveatasno"]', 'expected_output': '""'},
        {'input': '["ribwzmi", "rixzqhcwefa", "rihteegvozch"]', 'expected_output': '"ri"'},
        {'input': '["s", "furdtcfjxokptovcdzp", "furdtcfgbb", "furdtcfwmlh", "furdtcfubqzie", "furdtcfgx", "furdtcfolzym", "furdtcfjiwg", "furdtcfhxfyoc"]', 'expected_output': '""'},
        {'input': '["gjiozr", "gjiozhpyifbvhozfe", "gjiozrjytoli", "gjiozq"]', 'expected_output': '"gjioz"'},
        {'input': '["", "lbrhhyqun", "lbrhhyqul", "lbrhhyquzs", "aghddg"]', 'expected_output': '""'},
        {'input': '["ovbcrsdlhsprdo", "ovbcrsdthnnuhrez", "ovbcrsdxj", "ovbcrsdllccn", "egsccciou", "ovbcrsd", "doamafcdqx", "ovbcrsdhdqlfxayhue", "ovbcrsdpf"]', 'expected_output': '""'},
        {'input': '["", "eolcmznbwpiwmp", "eolcmassk", "eolcmujxbrele", "eolcm", "eolcmsipnydn", "eolcmzaerfsixqzcj", "eolcmfr", "eolcmnjtvhmf", "eolcmpouuumfh"]', 'expected_output': '""'},
        {'input': '["cgymluonbhddzbu", "cgymluonqxipr", "cgymluonu"]', 'expected_output': '"cgymluon"'},
        {'input': '["fwyybpcuauy", "fwyyb"]', 'expected_output': '"fwyyb"'},
        {'input': '["owrkiividrseurhfwg", "bjxongtkj", "dcgjwe", "owrkiivzhuq", "owrkiivlrnghcfhysk"]', 'expected_output': '""'},
        {'input': '["dmdhp", "jbjzbo", "qcyobordjqot", "b", "j", "r", "nuc", "piwztxlqnf", "ol", "sfwwqtgco"]', 'expected_output': '""'},
        {'input': '["eddwfckdohbqtq", "eddxg", "qogihjc", "edd", "edddot", "eddgolcchpph", "eddiofxbfmhls", "eddppxybcdew"]', 'expected_output': '""'},
        {'input': '["llqqt", "l", "ltlzl"]', 'expected_output': '"l"'},
        {'input': '["kjmtxmmnkoiv", "kjmarwhjsqwah", "kjmzbemgsbpsy", "kjmoyfc", "dell", "kjmuanqrwimcrk", "kjm", "kjmcmyzfnhg", "kjmrbw"]', 'expected_output': '""'},
        {'input': '["oi", "hzvejryy", "yngoulvxepfshwbgct", "yngouldldbqumtb", "yngoulufjmbn", "yngoulrkbi", "m", "yngoulnor"]', 'expected_output': '""'},
        {'input': '["umcmvufezayysuys", "umcmvufegzu", "umcmvufe", "umcmvufeejfxwkwktg", "umcmvufeajnourigfho"]', 'expected_output': '"umcmvufe"'},
        {'input': '["pw", "i", "tmbbmrjo", "mrvqydqxw"]', 'expected_output': '""'},
        {'input': '["fit", "fisihgutwvlia", "firslhuowjsigh"]', 'expected_output': '"fi"'},
        {'input': '["lqvzzwcevh", "jvjhxpllynyo", "lqvrkpustyujbd"]', 'expected_output': '""'},
        {'input': '["nhhobgco", "nhhobvryoqzljypxw", "nhhobrnziayyfia", "nhhobauekjrb", "nhhobs", "nhhob", "khzbhvwxkfgi"]', 'expected_output': '""'},
        {'input': '["glckmfryhs", "noxslzq", "glcktyrhgvt", "olxwgafslgpk"]', 'expected_output': '""'},
        {'input': '["wtmngue", "xohfieeigocpkwt", "xohficdapugsg", "xohfixdndzlkxav"]', 'expected_output': '""'},
        {'input': '["igstfkbqtfknvqv", "igstftik", "igstflugbvrztgsqc", "igstfug", "igstfdlayhicbl", "igstfrilxemre", "ykktapfa"]', 'expected_output': '""'},
        {'input': '["hglymmbdz", "dvtppy", "dlfqxvzlzk", "tvx", "zzdqep"]', 'expected_output': '""'},
        {'input': '["blsrmlousnb", "geaz", "blstptldg", "qxtdirwbnni", "blsje", "blsuyc"]', 'expected_output': '""'},
        {'input': '["yxpeqzpzzod", "yxpeqzpepwankqhbwk", "yxpeqzpiv", "yxpeqzpyfk", "yxpeqzpiq"]', 'expected_output': '"yxpeqzp"'},
        {'input': '["yr"]', 'expected_output': '"yr"'},
        {'input': '["folou", "fkdmkdgld", "f"]', 'expected_output': '"f"'},
        {'input': '["vxxlwhpxw", "vxxlwhpxxyg", "vxxlwhpxsjmvcru", "vxxlwhpxfat", "vxxlwhpxlflfd", "vxxlwhpxvgw", "vxxlwhpxfbpu", "vxxlwhpxnsxvrxk"]', 'expected_output': '"vxxlwhpx"'},
        {'input': '["zojx", "hegnpindiin", "zoyvsmzzcnmn", "", "zodjbfnjqcfy", "zolitmflhkstp"]', 'expected_output': '""'},
        {'input': '["buckp", "cpdlqubj", "cpdlcmoatlnjtxml", "cpdlmnzjzv", "cpdlogmsexux", "cpdljp", "cpdlszh", "cxlwjrm", "vsejtl"]', 'expected_output': '""'},
        {'input': '["mufaurcsyt", "mufaurcseshkk", "mufaurcszmswuphuxz", "mufaurcs", "mufaurcspcftoe", "mufaurcszntpdfa", "mufaurcsejoplgpzwob", "mufaurcsqd", "mufaurcsci"]', 'expected_output': '"mufaurcs"'},
        {'input': '["az", "l", "azf"]', 'expected_output': '""'},
        {'input': '["pudec", "puyemmtdplusbb"]', 'expected_output': '"pu"'},
        {'input': '["ipgyddrlg", "ipgyddrtutnsvytvou", "cqbystpstyl"]', 'expected_output': '""'},
        {'input': '["fayqrlqrhi"]', 'expected_output': '"fayqrlqrhi"'},
        {'input': '["zjdqikvowcz", "asm"]', 'expected_output': '""'},
        {'input': '["teaqoccfsxu", "jtgnd", "jtqjk", "jdhqrzseedcn"]', 'expected_output': '""'},
        {'input': '["wjzkwuuprpyylzbqyvgi", "wjzkwuupukuylyxnsp", "wjzkwuupjopgxyxlq", "wjzkwuupiixofnmels", "wjzkwuupnbqhchucaz", "wjzkwuupkfaon", "wjzkwuuplekz", "wjzkwuuposqhpptkprau"]', 'expected_output': '"wjzkwuup"'},
        {'input': '["gtfvcw"]', 'expected_output': '"gtfvcw"'},
        {'input': '["ris"]', 'expected_output': '"ris"'},
        {'input': '["vdnokqyhnde", "vdnokqs", "vdnokq", "vdnokqtnlvrvzxsw", "vdnokqmxjekv", "vdnokqlxscyg", "vdnokqk"]', 'expected_output': '"vdnokq"'},
        {'input': '["icipikr", "icijlndvlff", "yuehjreg"]', 'expected_output': '""'},
        {'input': '["oufaxuqeybvlrzs", "oufaxnyoooqqkxg", "oufaxeieugkvha", "czrip", "oufaxt", "avfwu", "oufaxhwwkpd", "oufaxdmjyecgl", "oufaxx", "oufaxrrlrshm"]', 'expected_output': '""'},
        {'input': '["yyuymbkgrmxknohx", "yyuymbkgu", ""]', 'expected_output': '""'},
        {'input': '["pxarbenmfueczguoxyh", "pxarbengmrpkglwx", "pxarbenoaxcng", "pxarbenc", "pxarben", "pxarbenpjuyqvjwiid", "ecjovjpdnrhv", "pxarbennvdxe", "pxarbenmclbyfojxtw"]', 'expected_output': '""'},
        {'input': '["ehqckevjr", "ehntc", "ehrcvvr", "cwpeiaxkusu"]', 'expected_output': '""'},
        {'input': '["jplsgaoddywvh", "jplsgazlqflet", "jplsgavpzkousrzlkf", "jplsgakmmqw"]', 'expected_output': '"jplsga"'},
        {'input': '["cayewlskroij"]', 'expected_output': '"cayewlskroij"'},
        {'input': '["", "fqcguyru", "nrrulo", "mfcxidhnqqti", "rptohdzrqlei", "hrpayprooqm", "pvftmuvmr", "flrvr", "xlv"]', 'expected_output': '""'},
        {'input': '["oyiytybdnodwgvqjabw", "oyiytybdxez", "rzvbtdlmex"]', 'expected_output': '""'},
        {'input': '["qzqe", "qzqenq", "qzqeqqabqpokc", "ebniiwfi"]', 'expected_output': '""'},
        {'input': '["vguwmdlobf", "vguwmpyqt", "vguwmoxahid", "xihflywmn", "vguwmmxizx", "vguwmpldjfttvln", "vguwmiqdiezx"]', 'expected_output': '""'},
        {'input': '["qrqqtm", "ashwbvpjdf", "qvlybwghp", "qvrldkub", "q"]', 'expected_output': '""'},
        {'input': '["wp", "mtfapllfs", "zfsacsefy", "", "fv", "fepq", ""]', 'expected_output': '""'},
        {'input': '["xqiuuojtrqc", "xqiuuojteydyhlneri", "xqiuuojtiftayhqick", "xqiuuojtrzl", "nk", "xqiuuojtlagkkxt", "xqiuuojtel", "xqiuuojtdnywnnbgrx"]', 'expected_output': '""'},
        {'input': '["icaoq", "ztoofznnv"]', 'expected_output': '""'},
        {'input': '["zuhgfhw", "zuhlupheiqnp"]', 'expected_output': '"zuh"'},
        {'input': '["wkoitlzatbitw", "ctkhyyxl", "wfdjbk"]', 'expected_output': '""'},
        {'input': '["rccldyd", "ctdmmxax", "ctdmmxafondzmcqasvu", "ctdmmxaqdvt", "ctdmmxaozo", "ctdmmxaufviiawg", "ctdmmxaeyqvihl", "ctdmmxaptnhcijdznmp"]', 'expected_output': '""'},
        {'input': '["emoejjv", "exw", "elawtbb", "emsoctr", "ehv", "qrmeoz", "eyrcf", "nlhniglb"]', 'expected_output': '""'},
        {'input': '["ekfcycpem", "z", "ekfcygurof", "zgjfywkxxf", "brv", "ekfcy", "ekfcyeqgxqb", "ekfcytckkgisme", "ekfcy", "ekfcyjgwhpeczqhf"]', 'expected_output': '""'},
        {'input': '["wnmdrvidmw", "zst", "vcurvmisewdlz", "adrx"]', 'expected_output': '""'},
        {'input': '["b"]', 'expected_output': '"b"'},
        {'input': '["ilicjedoe", "lfhghtczfk", "ilicjeilrbwnd", "ilicjewcdjb", "vfyvytxh", "aiuynsset", "ytvqyxufdnax", "ilicjenhbpw"]', 'expected_output': '""'},
        {'input': '["xvlesueew", "xvlesueevdldjeqrtvey", "xvlesueeac", "xvlesueefvihkqgd"]', 'expected_output': '"xvlesuee"'},
        {'input': '["jhbemlx", "jhbemlx", "jhbemlxsprtjrjlgq", "jhbemlxxlpycuf", "jhbemlxmsark", "", "jhbemlxvcinyecjrmu", "u", "jhbemlxmrc", "vkgo"]', 'expected_output': '""'},
        {'input': '["jyskdwwgkacjzc", "jyskdwwsbdixdrdm", "jyskdwwowpznjd", "jyskdwwqrnizpapyry", "wyrdwovwqzfq"]', 'expected_output': '""'},
        {'input': '["nj", "kirekjf", "n", "nrcvosmy", "nplikuzn", "nxjt", "prewncpmo", "nyusk", "npoo", "nkllrus"]', 'expected_output': '""'},
        {'input': '["yxzeo", "yxzsawwegszgi", "irpqntvkqrlt"]', 'expected_output': '""'},
        {'input': '["d"]', 'expected_output': '"d"'},
        {'input': '["wgmikahnfme", "wgmikavqeopu", "wgmikanoyniywj", "wgmikahidqnxwufn", "wgmika"]', 'expected_output': '"wgmika"'},
        {'input': '["oedio", "ecyaj", "iprhdkeqf", "oehqtqmhhbvf", "oehsycijijoo", "recer", "oechencikokhd", "oemglgqkzh", "oewvlvqmalhy"]', 'expected_output': '""'},
        {'input': '["zfwzzpnx", "zfwzzphaifdqhpc", "zfwzzpe", "zfwzzpnxev", "wqka"]', 'expected_output': '""'},
        {'input': '["wfsxzuwc"]', 'expected_output': '"wfsxzuwc"'},
        {'input': '["gzrzmtvuum", "gzrhltzelmnci", "gzryirkif", "gzrzyywes", "gzrvr"]', 'expected_output': '"gzr"'},
        {'input': '["neckcvtu", "", "cr", "vdmplnl", "avn", "iy", "brcnbztpui", "azzpsmot", "orxchycehmzv"]', 'expected_output': '""'},
        {'input': '["syljamypt", "syljaujdtxwk", "syljaolgskuxcesfe", "ob", "t"]', 'expected_output': '""'},
        {'input': '["nmewuxhinaqdrdbanrj", "nmewuxhiacgf", "nmewuxhioherg", "nmewuxhifvqrmpdhnce", "gijemtwvcnas", "nmewuxhijkseu", "", "nmewuxhilodl"]', 'expected_output': '""'},
        {'input': '["acqfciyreg"]', 'expected_output': '"acqfciyreg"'},
        {'input': '["fsoipkbqqejxwhcpktgd", "fsoipkbq"]', 'expected_output': '"fsoipkbq"'},
        {'input': '["iykwb", "knvwugnkmxyy", "nxmzwdbcuvairkjva", "nxmzwdrqonrxl"]', 'expected_output': '""'},
        {'input': '["kejorl", "ushlkb"]', 'expected_output': '""'},
        {'input': '["haspqztjjllw"]', 'expected_output': '"haspqztjjllw"'},
        {'input': '["wdzvcatexwccj", "wdzvcswrvjjbeyhn", "wdzvcdkceuxq", "vhvrnwajje", "ivjpsil", "wdzvclwu", "wdzvccchfautss"]', 'expected_output': '""'},
        {'input': '["ugqtnkwk", "ugqtnkwycz", "ugqtnkwiopujbsdxwt", "ugqtnkwoyojzxrrtg", "ugqtnkwfa", "ugqtnkwlgw", "ugqtnkwbto", "ugqtnkwevmuymmxye", "ugqtnkw"]', 'expected_output': '"ugqtnkw"'},
        {'input': '["ffqzmb", "ffqaf", "ffqcmx", "wgvuydfrx", "ffqkmhcjabam", "ffqd", "ffquv", "ffqmmgamjxiv", "ffqvmlr"]', 'expected_output': '""'},
        {'input': '["efwjznupdsjn", "ezcucidhl", "eyiiwdpymwskq", "emymor"]', 'expected_output': '"e"'},
        {'input': '["zvzewqwfoybg", "zvzedirogixt", "zvzelqdgavljaixt", "zvzeeo", "zvzeogpputhwnzm", "zvzeisrywgtk", "zvzetdccmfh", "zvzeertomcqb", "zvzeerpt"]', 'expected_output': '"zvze"'},
        {'input': '["qxdhyhobrey"]', 'expected_output': '"qxdhyhobrey"'},
        {'input': '["ugnkcxzj", "uzccth", "uhww", "uotblk", "ucbsnicey"]', 'expected_output': '"u"'},
        {'input': '["xetpbieefvtfqqo"]', 'expected_output': '"xetpbieefvtfqqo"'},
        {'input': '["", "nfxarkdo", "nfxarkdpciiykhrr", "nfxarkdicktwhbem", "nfxarkdzbah", "jlcgjti", "wqrghfts", "nfxarkdrf", "nfxarkdx", "nfxarkdhreidjogs"]', 'expected_output': '""'},
        {'input': '["pkdqp", "ssdj", "ocp", "ocpiyluwsatr", "ocpryifydh", "ocpqq", "ocpopnqzwzllay", "ocpznizycsg"]', 'expected_output': '""'},
        {'input': '["vnnjajiynkawcpravwx", "xb", "vnnjajiqaqqp", "vnnjaji", "vnnjajillxbmlq", "vnnjajiqhf", "vnnjaji", "vnnjajicyza", "vnnjajitdjkmuidb", "vnnjajixligqhqk"]', 'expected_output': '""'},
        {'input': '["guv", "ccljnotry", "cnxcwdgppucpasgsp", "cnxcw", "cnxcwkgtyyfqyeq", "cnxcw", ""]', 'expected_output': '""'},
        {'input': '["matealeblqfhhyhv", "matealffu", "dbr", "matealuhvtsv", "matealeqmu", "eppujve"]', 'expected_output': '""'},
        {'input': '["xr", "lgjgrklm", "ec", "z", "ahjczzxtiv", "kjgcbxznc"]', 'expected_output': '""'},
        {'input': '["zxvteb", "paxkn"]', 'expected_output': '""'},
        {'input': '["czwhguvo", "czwhgctwak", "czwhg", "czwhgw"]', 'expected_output': '"czwhg"'},
        {'input': '["hgipo", "hgiujxyuqtzdqf", "hgiyjpztrq", "hgiuo", "hmhiug", "hgip", "hgiisfmbisbg"]', 'expected_output': '"h"'},
        {'input': '["dpkyqxkx", "dpknus", "dpkkkjuanuxyal"]', 'expected_output': '"dpk"'},
        {'input': '["lrrtsqqnwoec", "lcxmzrtqv", "zsqst", "", "dupoo", "qobkawtfmaal"]', 'expected_output': '""'},
        {'input': '["mmvpzfwdl", "mmvpzfwrpmkpdvxvtc", "mmvpzfwe", "mmvpzfwr", "mmvpzfwsz"]', 'expected_output': '"mmvpzfw"'},
        {'input': '["tbl", "tbldbmoptyrbk", "wobarfcjkt", "tblprzimhoibna", "tblpfdraqwzn", "tblcxd"]', 'expected_output': '""'},
        {'input': '["bcaeagsrakphz", "k"]', 'expected_output': '""'},
        {'input': '["uozzjxut", "uozzjxutetuyjdg"]', 'expected_output': '"uozzjxut"'},
        {'input': '["wwmubcngsliogy", "wwmubcngraoizoopu", "wwmubcngeamdwsul", "wwmubcngzloirmiupbm", "wwmubcngwxjdtqfppcp", "wwmubcngikj"]', 'expected_output': '"wwmubcng"'},
        {'input': '["afwspaefubdcqhbivmxb", "afwspaefrgco", "afwspaefxtntvqtw", "afwspaefhyiymrzd", "afwspaefoxvo", "afwspaefxyjreutueqjz", "afwspaeffat", "afwspaefxxra", "afwspaefslhnz", "afwspaefhks"]', 'expected_output': '"afwspaef"'},
        {'input': '["zftrazbdbjyhds", "zfoixadr", "zflhfnyue", "zcvsoykgpnd", "zfxikrdt", "zfeuzcunn", "zfjmfvaibxcgx", "zfdoerwmt", "qmuokrfxlbh", "zfds"]', 'expected_output': '""'},
        {'input': '["", "dktaaksak", "dkta", "beupcdruwayy", "dktavaown", "dktawosejavbxv", "dktakrpfdaaz", "dktambpseu"]', 'expected_output': '""'},
        {'input': '["ephkxvnivqcgortn", "ephkxvni", "ephkxvnidvchk"]', 'expected_output': '"ephkxvni"'},
        {'input': '["nuisuuclyhhptl", "nuisuucqkewkbepadw", "nuisuucaxlibdkr", "nuisuuciwxmyyojjf", "nuisuucyeeq"]', 'expected_output': '"nuisuuc"'},
        {'input': '["mpqxgzvcutpjc", "mpqxz"]', 'expected_output': '"mpqx"'},
        {'input': '["prruogfdws", "qprvmeotoen", "urjbm", "vcsv"]', 'expected_output': '""'},
        {'input': '["zcioyu", "yrwm", "kltymqrlbfn"]', 'expected_output': '""'},
        {'input': '["pukdbldr", "mbiol", "sgqcntoz", "chrkyx", "mbiollz", "mbiolarz", "t"]', 'expected_output': '""'},
        {'input': '["rtzjrbta", "rnsxtjjxhybqqkfd", "spjklu", "rnsxtjj"]', 'expected_output': '""'},
        {'input': '["nsb", "nbfotr", "njziybitrbee", "ndhdiar", "n"]', 'expected_output': '"n"'},
        {'input': '["vqiythxphes", "vqiythxpio", "hukmd", "vqiythxpqxjuozxnc", "vqiythxpevlhxrrkch", "vqiythxphdabkl", "vqiythxpptprxsv", "vqiythxpaxxebuluc"]', 'expected_output': '""'},
        {'input': '["fsvrxndiyyllg"]', 'expected_output': '"fsvrxndiyyllg"'},
        {'input': '["rvqzbzll", "rvqzbjvqfx", "rvqzbyqgcnjbvn", "gres"]', 'expected_output': '""'},
        {'input': '["qpwsfhip", "pk", "qpwsfhipznnnx", "qpwsfhipwgqbw", "qpwsfhiprbl", "qpwsfhipaazfanxazcay", "qpwsfhipvag"]', 'expected_output': '""'},
        {'input': '["kikgglynike", "kirju", "kikmdjwm"]', 'expected_output': '"ki"'},
        {'input': '["gfwhszcgufybbblce", "itu"]', 'expected_output': '""'},
        {'input': '["oguxltbdqqoedt", "oguxgv", "ogux", "oguxldqxqopvaggq", "oguxgegbnitsnos", "ynipoji", "oguxjgpatuu"]', 'expected_output': '""'},
        {'input': '["dnfawvawx", "dnfawvpdwhk", "dnfawvfu"]', 'expected_output': '"dnfawv"'},
        {'input': '["rkyg", "avbdeip", "fxn", "rkafgg", "geswfjjm", "rkkfyxzysijb", "rkzjhcaz"]', 'expected_output': '""'},
        {'input': '["nmkzjxbqzqsdnbmet", "nmkzjxbzzzvu", "nmkzjxb", "nmkzjxbwfcguzakfg", "nmkzjxbjnqpl", "nmkzjxb", "nmkzjxbj", "nmkzjxbkzigpkjvpl", "nmkzjxb"]', 'expected_output': '"nmkzjxb"'},
        {'input': '["bcswxox", "kdszhva"]', 'expected_output': '""'},
    ]
    for offset, case in enumerate(cases[:count]):
        yield {
            "input": case["input"],
            "expected_output": case["expected_output"],
            "order_index": start_index + offset,
            "is_sample": False,
        }
