"""
Generate frontend/src/data/problemMetadata.js from problems/*/meta.yaml.

Usage: python -m backend.tools.generate_problem_metadata
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parents[2]
_PROBLEMS = _REPO / "problems"
_OUT = _REPO / "frontend" / "src" / "data" / "problemMetadata.js"

_DEFAULT_COMPANIES = [
    "Google", "Amazon", "Microsoft", "Meta", "Apple",
    "Netflix", "Uber", "Adobe", "Oracle", "Goldman Sachs",
    "Flipkart", "Infosys", "TCS", "Wipro", "Accenture",
]

_TOPIC_RULES: list[tuple[str, list[str]]] = [
    ("Linked List", ["linked list", "listnode", "ll", "pairs", "reverse nodes", "remove nth", "merge two sorted lists", "add two numbers", "palindrome linked", "odd even linked", "partition list", "rotate list", "swap nodes", "twin sum", "middle of the linked"]),
    ("Trees", ["tree", "bst", "binary tree", "leaf", "preorder", "inorder", "zigzag level", "kth smallest", "lca", "symmetric", "invert binary"]),
    ("String", ["string", "anagram", "palindrome", "substring", "regex", "roman", "atoi", "zigzag", "decode string", "word break", "permutation in string"]),
    ("Binary Search", ["binary search", "sorted array", "rotated sorted", "search insert", "mountain array", "median of two", "koko eating", "ship packages", "split array largest", "successful pairs"]),
    ("Sliding Window", ["sliding window", "window maximum", "minimum window", "fruit into baskets", "max consecutive ones", "permutation in string", "nice subarray", "binary subarrays"]),
    ("Greedy", ["gas station", "jump game", "candy", "interval", "non-overlapping", "partition labels", "task scheduler", "bouquet", "ipo", "assign cookies", "lemonade", "flowers", "balloons", "refueling", "bag of tokens"]),
    ("Matrix", ["matrix", "spiral", "set matrix", "game of life", "search a 2d"]),
    ("Arrays", ["array", "sum", "subarray", "duplicate", "zeroes", "rotate array", "product except", "majority", "pascal", "sort colors", "two sum", "3 sum", "container"]),
    ("Dynamic Programming", ["word break", "decode string", "house robber", "max product", "palindromic substring", "regular expression"]),
    ("Stack", ["valid parentheses", "simplify path", "daily temperatures", "decode string"]),
    ("Heap", ["kth largest", "top k", "find median"]),
]


def _infer_topic(title: str, slug: str, method_name: str | None) -> str:
    haystack = f"{title} {slug} {method_name or ''}".lower()
    for topic, keywords in _TOPIC_RULES:
        if any(kw in haystack for kw in keywords):
            return topic
    return "Arrays"


def _load_existing_titles_from_company_problems() -> dict:
    """Parse existing inline metadata from CompanyProblems if present."""
    path = _REPO / "frontend" / "src" / "pages" / "CompanyProblems.jsx"
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8")
    # Keep hand-maintained entries by extracting title keys already in file
    return {}


def main() -> None:
    metadata: dict[str, dict] = {}

    for meta_path in sorted(_PROBLEMS.glob("*/meta.yaml")):
        raw = yaml.safe_load(meta_path.read_text(encoding="utf-8"))
        if not isinstance(raw, dict):
            continue
        if raw.get("problem_type") == "cp":
            continue
        title = raw["title"]
        topic = _infer_topic(title, raw.get("slug", ""), raw.get("method_name"))
        metadata[title] = {
            "topic": topic,
            "companies": _DEFAULT_COMPANIES,
        }

    _OUT.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "// Auto-generated by backend/tools/generate_problem_metadata.py\n"
        "// Do not edit by hand — re-run the generator after adding problems.\n\n"
        f"export const DEFAULT_PROBLEM_COMPANIES = {json.dumps(_DEFAULT_COMPANIES, indent=4)};\n\n"
        f"export const PROBLEM_METADATA = {json.dumps(metadata, indent=4)};\n\n"
        "export function getProblemMetadata(title) {\n"
        "  if (!title) return null;\n"
        "  if (title.includes('Spiral')) title = 'Print the matrix in spiral manner';\n"
        "  return PROBLEM_METADATA[title] || null;\n"
        "}\n"
    )
    _OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {len(metadata)} entries to {_OUT}")


if __name__ == "__main__":
    main()
