"""Auto-migrated bulk hidden test cases."""

def generate_cases(*, count: int, seed: int, start_index: int):
    del seed
    cases = [
        {'input': '["ccbdc", "", "acceeeae", "ededcbbd", "eeebc", "ecbcbd", "cadc", "e", "bbcbccc"]', 'expected_output': '[[""], ["acceeeae"], ["bbcbccc"], ["cadc"], ["ccbdc"], ["e"], ["ecbcbd"], ["ededcbbd"], ["eeebc"]]'},
        {'input': '["dcaddae", "d", "", "adc", "ad", "bccdeee", "eeeea", "d", "", "cc", "cceaca", "c", "ccad"]', 'expected_output': '[["", ""], ["ad"], ["adc"], ["bccdeee"], ["c"], ["cc"], ["ccad"], ["cceaca"], ["d", "d"], ["dcaddae"], ["eeeea"]]'},
        {'input': '["ebbbec", "adebdcad", "ccbccde", "eeb", "baad", "bdce", "cecca", "aacbb", "", "dcace", "cbddbad", "eecd", "ec"]', 'expected_output': '[[""], ["aacbb"], ["adebdcad"], ["baad"], ["bdce"], ["cbddbad"], ["ccbccde"], ["cecca"], ["dcace"], ["ebbbec"], ["ec"], ["eeb"], ["eecd"]]'},
        {'input': '["dbdc", "cce", "beaada", "babbbae", "", "ceaddcc", "eda", "ecabaab", "da", "cad", "caeab", "aa", "eadedeed"]', 'expected_output': '[[""], ["aa"], ["babbbae"], ["beaada"], ["cad"], ["caeab"], ["cce"], ["ceaddcc"], ["da"], ["dbdc"], ["eadedeed"], ["ecabaab"], ["eda"]]'},
        {'input': '["", "ceaebbdd", "aedd", "aba", "cec", "bdcaea", "ea", "dd", "eedea", "bdccebeb", "bedead", ""]', 'expected_output': '[["", ""], ["aba"], ["aedd"], ["bdcaea"], ["bdccebeb"], ["bedead"], ["ceaebbdd"], ["cec"], ["dd"], ["ea"], ["eedea"]]'},
        {'input': '["cacbeccd", "b", "ad", "ebcabc"]', 'expected_output': '[["ad"], ["b"], ["cacbeccd"], ["ebcabc"]]'},
        {'input': '["aaeeedce", "dcb", "e", "acebae", "bccd", "bdadabc", "ebeeeeee", "ada"]', 'expected_output': '[["aaeeedce"], ["acebae"], ["ada"], ["bccd"], ["bdadabc"], ["dcb"], ["e"], ["ebeeeeee"]]'},
        {'input': '["aadbcc", "eadb", "aadacd", "c", "dbcdebc", "ceecdec", "acdcada"]', 'expected_output': '[["aadacd"], ["aadbcc"], ["acdcada"], ["c"], ["ceecdec"], ["dbcdebc"], ["eadb"]]'},
        {'input': '["ddcd", "d", "dded", "ccecdd", "bed", "bdb"]', 'expected_output': '[["bdb"], ["bed"], ["ccecdd"], ["d"], ["ddcd"], ["dded"]]'},
        {'input': '["dbde", "dbbec", "deea", "aedadaeb", "eaedca", "ebbdcb", "aa", "aeceeaea", "e", "bd", "eedbce", "abeb", "a", "dbecacd"]', 'expected_output': '[["a"], ["aa"], ["abeb"], ["aeceeaea"], ["aedadaeb"], ["bd"], ["dbbec"], ["dbde"], ["dbecacd"], ["deea"], ["e"], ["eaedca"], ["ebbdcb"], ["eedbce"]]'},
        {'input': '["d", "cbcbccbe", "deace", "decadddc", "abba", "", "abeaeee"]', 'expected_output': '[[""], ["abba"], ["abeaeee"], ["cbcbccbe"], ["d"], ["deace"], ["decadddc"]]'},
        {'input': '["", "e", "cccdcbbe", "babd", "beaaeebd", "dedcb", "eabdbebb", "d"]', 'expected_output': '[[""], ["babd"], ["beaaeebd"], ["cccdcbbe"], ["d"], ["dedcb"], ["e"], ["eabdbebb"]]'},
        {'input': '["dd", "dddae", "c", "ce", "edcde", "cdd", "cdeeceb", "dcbeeaae", "", "dec"]', 'expected_output': '[[""], ["c"], ["cdd"], ["cdeeceb"], ["ce"], ["dcbeeaae"], ["dd"], ["dddae"], ["dec"], ["edcde"]]'},
        {'input': '["cb", "", "ee", "adadaa", "cccd"]', 'expected_output': '[[""], ["adadaa"], ["cb"], ["cccd"], ["ee"]]'},
        {'input': '["dddee", "edbcb", "eacadbae", "aaace", "caeed", "cacce", "ecccaee", "b"]', 'expected_output': '[["aaace"], ["b"], ["cacce"], ["caeed"], ["dddee"], ["eacadbae"], ["ecccaee"], ["edbcb"]]'},
        {'input': '["bbacdbd", "b", "abcede", "ccbe", "", "aaaecd", "cbdde", "bc"]', 'expected_output': '[[""], ["aaaecd"], ["abcede"], ["b"], ["bbacdbd"], ["bc"], ["cbdde"], ["ccbe"]]'},
        {'input': '["cdae", "a", "", "eba", "", "ebebd", "becedad", "ddbdedc", "bab", "adca", "accb", "eddcaa", "ebcebe"]', 'expected_output': '[["", ""], ["a"], ["accb"], ["adca"], ["bab"], ["becedad"], ["cdae"], ["ddbdedc"], ["eba"], ["ebcebe"], ["ebebd"], ["eddcaa"]]'},
        {'input': '["cdbdeab", "dac", "e"]', 'expected_output': '[["cdbdeab"], ["dac"], ["e"]]'},
        {'input': '["abd", "edcee", "caaecdca", "eec", "cebbdebc", "eca", "ad", "edbde", "eebd", "ddbece"]', 'expected_output': '[["abd"], ["ad"], ["caaecdca"], ["cebbdebc"], ["ddbece"], ["eca"], ["edbde"], ["edcee"], ["eebd"], ["eec"]]'},
        {'input': '["bcad", "be", "ed", "da", "cabedced", "be", "bcacdde", "edbce", "", "b", "cddcdabc", "bebda"]', 'expected_output': '[[""], ["b"], ["bcacdde"], ["bcad"], ["be", "be"], ["bebda"], ["cabedced"], ["cddcdabc"], ["da"], ["ed"], ["edbce"]]'},
        {'input': '["deeec", "", "", "dbed", "eebddc", "bdaaccce", "edbac", "bcedac"]', 'expected_output': '[["", ""], ["bcedac"], ["bdaaccce"], ["dbed"], ["deeec"], ["edbac"], ["eebddc"]]'},
        {'input': '["edacaddb", "cddce"]', 'expected_output': '[["cddce"], ["edacaddb"]]'},
        {'input': '["a", "eaebeea", "", "bcdacb", "bbde"]', 'expected_output': '[[""], ["a"], ["bbde"], ["bcdacb"], ["eaebeea"]]'},
        {'input': '["cbcdbb", "eade"]', 'expected_output': '[["cbcdbb"], ["eade"]]'},
        {'input': '["bdacda", "deeddae", "dcae", "cbdcbaae", "ecceab", "ccddab", "cedddba", "c", "edaad", "baa", "aaedeaa"]', 'expected_output': '[["aaedeaa"], ["baa"], ["bdacda"], ["c"], ["cbdcbaae"], ["ccddab"], ["cedddba"], ["dcae"], ["deeddae"], ["ecceab"], ["edaad"]]'},
        {'input': '["deda"]', 'expected_output': '[["deda"]]'},
        {'input': '["dcccd", "dbcbbdc", "bbb", "deaa", "cc", "aeebbcd"]', 'expected_output': '[["aeebbcd"], ["bbb"], ["cc"], ["dbcbbdc"], ["dcccd"], ["deaa"]]'},
        {'input': '["edb", "e", "cbddde", "a"]', 'expected_output': '[["a"], ["cbddde"], ["e"], ["edb"]]'},
        {'input': '["cb", "aceeebbb", "a", "ca", "bea", "ea", "aabd", "aacd", "dedb", "d", "bbcb", "a", "d", ""]', 'expected_output': '[[""], ["a", "a"], ["aabd"], ["aacd"], ["aceeebbb"], ["bbcb"], ["bea"], ["ca"], ["cb"], ["d", "d"], ["dedb"], ["ea"]]'},
        {'input': '["cae", "badecb", "d", "a", "dbbeeed"]', 'expected_output': '[["a"], ["badecb"], ["cae"], ["d"], ["dbbeeed"]]'},
        {'input': '["ebd", "bba"]', 'expected_output': '[["bba"], ["ebd"]]'},
        {'input': '["adaae", ""]', 'expected_output': '[[""], ["adaae"]]'},
        {'input': '["", "daacbced", "aec", "bdcaaab", "b", "dbebcaa"]', 'expected_output': '[[""], ["aec"], ["b"], ["bdcaaab"], ["daacbced"], ["dbebcaa"]]'},
        {'input': '["abbcdba", "a", "bbec", "bc", "", "b", "daaeddec"]', 'expected_output': '[[""], ["a"], ["abbcdba"], ["b"], ["bbec"], ["bc"], ["daaeddec"]]'},
        {'input': '["bcea"]', 'expected_output': '[["bcea"]]'},
        {'input': '["e", "bba", "dcbee", "bdecba", "abaab", "adeabe", "ceedca", "c"]', 'expected_output': '[["abaab"], ["adeabe"], ["bba"], ["bdecba"], ["c"], ["ceedca"], ["dcbee"], ["e"]]'},
        {'input': '["deadbec", "c", "ed", "", "aedbe", "eabd", "be", "aae", "cbeca", "a", ""]', 'expected_output': '[["", ""], ["a"], ["aae"], ["aedbe"], ["be"], ["c"], ["cbeca"], ["deadbec"], ["eabd"], ["ed"]]'},
        {'input': '["adbb", "debbd", "bbddbedb", "e", "", "e", "aaeaa", "debaee", "e", "cebdd", "acde", "edcbaed", "dea"]', 'expected_output': '[[""], ["aaeaa"], ["acde"], ["adbb"], ["bbddbedb"], ["cebdd"], ["dea"], ["debaee"], ["debbd"], ["e", "e", "e"], ["edcbaed"]]'},
        {'input': '["eddba", "cdcbc", "beebbaba", "daecdd", "dbaecb", "cd", "deaacb", ""]', 'expected_output': '[[""], ["beebbaba"], ["cd"], ["cdcbc"], ["daecdd"], ["dbaecb"], ["deaacb"], ["eddba"]]'},
        {'input': '["e", "eddae", "cbbac", "cddeeae", "bcbaedc", "bb", "bb", "aba", "", "edecaedd", "eedcdbbb", "cddaaabe", "dddbddee", "bddda"]', 'expected_output': '[[""], ["aba"], ["bb", "bb"], ["bcbaedc"], ["bddda"], ["cbbac"], ["cddaaabe"], ["cddeeae"], ["dddbddee"], ["e"], ["eddae"], ["edecaedd"], ["eedcdbbb"]]'},
        {'input': '["eabe", "eceb", "c", "ecbcbacb", "c", "", "ddbbdbcc"]', 'expected_output': '[[""], ["c", "c"], ["ddbbdbcc"], ["eabe"], ["ecbcbacb"], ["eceb"]]'},
        {'input': '["", "bcebccb", "cac", "d", "aeebecd"]', 'expected_output': '[[""], ["aeebecd"], ["bcebccb"], ["cac"], ["d"]]'},
        {'input': '["accdcb", "bddbae", "abec", "", "", "a", "cdadacae", "aabd", "beb"]', 'expected_output': '[["", ""], ["a"], ["aabd"], ["abec"], ["accdcb"], ["bddbae"], ["beb"], ["cdadacae"]]'},
        {'input': '["ace", "bbcabbab", "bc", "cdabeec", "ee", "bbeadaea", "beddcbca"]', 'expected_output': '[["ace"], ["bbcabbab"], ["bbeadaea"], ["bc"], ["beddcbca"], ["cdabeec"], ["ee"]]'},
        {'input': '["deba", "becb", "", "ace", "ddd", "d", "daaa", "bccd", "dbeadbe"]', 'expected_output': '[[""], ["ace"], ["bccd"], ["becb"], ["d"], ["daaa"], ["dbeadbe"], ["ddd"], ["deba"]]'},
        {'input': '["eabdd", "bda", "bedeaca", "bbe", "ca", "be", "bdabcdc", "cbacded", "eedacda", "", "", "deaac"]', 'expected_output': '[["", ""], ["bbe"], ["bda"], ["bdabcdc"], ["be"], ["bedeaca"], ["ca"], ["cbacded"], ["deaac"], ["eabdd"], ["eedacda"]]'},
        {'input': '["dbc", "aebacc", "cba", "beacb", "ddbea", "aebadcc", "", "c"]', 'expected_output': '[[""], ["aebacc"], ["aebadcc"], ["beacb"], ["c"], ["cba"], ["dbc"], ["ddbea"]]'},
        {'input': '["b", ""]', 'expected_output': '[[""], ["b"]]'},
        {'input': '["dbee", "aeb", "c", "aebddabe", "", "ab", "eecc", "dcdd", "", "ebbddc", "ddceab", "ecc", ""]', 'expected_output': '[["", "", ""], ["ab"], ["aeb"], ["aebddabe"], ["c"], ["dbee"], ["dcdd"], ["ddceab"], ["ebbddc"], ["ecc"], ["eecc"]]'},
        {'input': '["ebcebeb", "daddeb", "cbea", "ceb", "", "acb", "a", "ecaaecaa", "c", "ed"]', 'expected_output': '[[""], ["a"], ["acb"], ["c"], ["cbea"], ["ceb"], ["daddeb"], ["ebcebeb"], ["ecaaecaa"], ["ed"]]'},
        {'input': '["ddbbace", "cdae", "", "c"]', 'expected_output': '[[""], ["c"], ["cdae"], ["ddbbace"]]'},
        {'input': '["aeecdeb", "c", "aeebcbce", "dba", "bae", "daecec", "b", "", "acdbcd"]', 'expected_output': '[[""], ["acdbcd"], ["aeebcbce"], ["aeecdeb"], ["b"], ["bae"], ["c"], ["daecec"], ["dba"]]'},
        {'input': '["aaca", "ddcbcabd", "bceed", "decda", "beca", "cada", "ecaa", "cdaed", "dcadee", "eb", "a", "dda"]', 'expected_output': '[["a"], ["aaca"], ["bceed"], ["beca"], ["cada"], ["cdaed", "decda"], ["dcadee"], ["dda"], ["ddcbcabd"], ["eb"], ["ecaa"]]'},
        {'input': '["daac"]', 'expected_output': '[["daac"]]'},
        {'input': '["aceead", "adabccbd", "bde", "ccc", "bbbebddd", "abd", "bb", "bddacc", "aad", "", "ccbece", "bedbbad", "cbddc"]', 'expected_output': '[[""], ["aad"], ["abd"], ["aceead"], ["adabccbd"], ["bb"], ["bbbebddd"], ["bddacc"], ["bde"], ["bedbbad"], ["cbddc"], ["ccbece"], ["ccc"]]'},
        {'input': '["aecdcee", "", "", "cdcbcb", "", "bbcc", "adabdcec", "daaeeaed", "bcad", "", ""]', 'expected_output': '[["", "", "", "", ""], ["adabdcec"], ["aecdcee"], ["bbcc"], ["bcad"], ["cdcbcb"], ["daaeeaed"]]'},
        {'input': '["eee", "aaada", "dc", "dccbabe", "", "cebea", "ddebc", "eee"]', 'expected_output': '[[""], ["aaada"], ["cebea"], ["dc"], ["dccbabe"], ["ddebc"], ["eee", "eee"]]'},
        {'input': '["dbdeaeb", "cb", "a", "adcad"]', 'expected_output': '[["a"], ["adcad"], ["cb"], ["dbdeaeb"]]'},
        {'input': '["dccbdeb", "bdac", "cdba", "", "eb", "bcedbe"]', 'expected_output': '[[""], ["bcedbe"], ["bdac", "cdba"], ["dccbdeb"], ["eb"]]'},
        {'input': '["bbabeab", "a", "bbace"]', 'expected_output': '[["a"], ["bbabeab"], ["bbace"]]'},
        {'input': '["a", "addbc", "dbeebe", "dcde"]', 'expected_output': '[["a"], ["addbc"], ["dbeebe"], ["dcde"]]'},
        {'input': '["dd", "ee", "cabeb", "ade", "ceedeae", ""]', 'expected_output': '[[""], ["ade"], ["cabeb"], ["ceedeae"], ["dd"], ["ee"]]'},
        {'input': '["bdbbe", "dc", "cbcaaeee", "", "cbcc", "badcbdae"]', 'expected_output': '[[""], ["badcbdae"], ["bdbbe"], ["cbcaaeee"], ["cbcc"], ["dc"]]'},
        {'input': '["e", "dabc", "bcdda", "aecd", "abebccab", "ada", "cbdbb", "ccbeaecd", "bdbccaca", "d"]', 'expected_output': '[["abebccab"], ["ada"], ["aecd"], ["bcdda"], ["bdbccaca"], ["cbdbb"], ["ccbeaecd"], ["d"], ["dabc"], ["e"]]'},
        {'input': '["bddaedca", "b", "aeadbe"]', 'expected_output': '[["aeadbe"], ["b"], ["bddaedca"]]'},
        {'input': '["dcbabea", "dbeecbaa", "a", "cecdacde", "cb", "a"]', 'expected_output': '[["a", "a"], ["cb"], ["cecdacde"], ["dbeecbaa"], ["dcbabea"]]'},
        {'input': '["deccbcbb", "bbebddbb", "", "dda", "dcaeabd", "eabbedde", "", "debe"]', 'expected_output': '[["", ""], ["bbebddbb"], ["dcaeabd"], ["dda"], ["debe"], ["deccbcbb"], ["eabbedde"]]'},
        {'input': '["", "ebb", "ebaa", "ceb"]', 'expected_output': '[[""], ["ceb"], ["ebaa"], ["ebb"]]'},
        {'input': '["bacadaea", "", "ee", "edebbed", "deeccb", "ee", "bbedcbed", "ede"]', 'expected_output': '[[""], ["bacadaea"], ["bbedcbed"], ["deeccb"], ["ede"], ["edebbed"], ["ee", "ee"]]'},
        {'input': '["ddcdead", "eedde"]', 'expected_output': '[["ddcdead"], ["eedde"]]'},
        {'input': '["adddadaa", "dbaccb", "", "aceccdc", "bccabce", "cebdb", "cadeae"]', 'expected_output': '[[""], ["aceccdc"], ["adddadaa"], ["bccabce"], ["cadeae"], ["cebdb"], ["dbaccb"]]'},
        {'input': '["edea", "edddaed", "ba", "cb", "aaac", "ebacbc", "bdda", "", "bedaecd", "de"]', 'expected_output': '[[""], ["aaac"], ["ba"], ["bdda"], ["bedaecd"], ["cb"], ["de"], ["ebacbc"], ["edddaed"], ["edea"]]'},
        {'input': '["acdec", "bcded", "ca", "bbcbbdb", "eecdaebd", "bea"]', 'expected_output': '[["acdec"], ["bbcbbdb"], ["bcded"], ["bea"], ["ca"], ["eecdaebd"]]'},
        {'input': '["ddb", "", "", "bccaec", "dadabcbd"]', 'expected_output': '[["", ""], ["bccaec"], ["dadabcbd"], ["ddb"]]'},
        {'input': '["babae"]', 'expected_output': '[["babae"]]'},
        {'input': '["", "aabcadc", "aadacb", "c", "cdaaabb", "ddeccbdd"]', 'expected_output': '[[""], ["aabcadc"], ["aadacb"], ["c"], ["cdaaabb"], ["ddeccbdd"]]'},
        {'input': '["eba"]', 'expected_output': '[["eba"]]'},
        {'input': '["a", "ad"]', 'expected_output': '[["a"], ["ad"]]'},
        {'input': '["ccaee", "cc", "cbac", "b", "cb", "dcacbc", "dceb", "", "adeceb", "ccadeb"]', 'expected_output': '[[""], ["adeceb"], ["b"], ["cb"], ["cbac"], ["cc"], ["ccadeb"], ["ccaee"], ["dcacbc"], ["dceb"]]'},
        {'input': '["cbaade", "bdd", "eccdb", "bedbdd", "dbcee", "", "ed", "c", "abbbbabc", "add"]', 'expected_output': '[[""], ["abbbbabc"], ["add"], ["bdd"], ["bedbdd"], ["c"], ["cbaade"], ["dbcee"], ["eccdb"], ["ed"]]'},
        {'input': '["", "", "cabad", "beaac", "", "e"]', 'expected_output': '[["", "", ""], ["beaac"], ["cabad"], ["e"]]'},
        {'input': '["ebae"]', 'expected_output': '[["ebae"]]'},
        {'input': '["a"]', 'expected_output': '[["a"]]'},
        {'input': '["caecba", "dbcb", "aabcd", "b", "aeacae", "dccbaa"]', 'expected_output': '[["aabcd"], ["aeacae"], ["b"], ["caecba"], ["dbcb"], ["dccbaa"]]'},
        {'input': '["bdddbccd", "", "ddd", "bd", "", "ecadcca", "c", "e", "dde", "ddacaaab", "adaeb", "", "aedec", ""]', 'expected_output': '[["", "", "", ""], ["adaeb"], ["aedec"], ["bd"], ["bdddbccd"], ["c"], ["ddacaaab"], ["ddd"], ["dde"], ["e"], ["ecadcca"]]'},
        {'input': '["aaeda", "acdbcaad", "ec", "eb", "eabadba", "ebbeccca", "ae", "bdc"]', 'expected_output': '[["aaeda"], ["acdbcaad"], ["ae"], ["bdc"], ["eabadba"], ["eb"], ["ebbeccca"], ["ec"]]'},
        {'input': '["cc", "baddcd", "ccddcbed", "", "dcd", "ccaccba", "ecacc", "bbeceaa"]', 'expected_output': '[[""], ["baddcd"], ["bbeceaa"], ["cc"], ["ccaccba"], ["ccddcbed"], ["dcd"], ["ecacc"]]'},
        {'input': '["b", "be"]', 'expected_output': '[["b"], ["be"]]'},
        {'input': '["", "ee", "cbcbcca", "abeeacab", "babdbeb", "ceace", "cab", "bda", "dac", "aad"]', 'expected_output': '[[""], ["aad"], ["abeeacab"], ["babdbeb"], ["bda"], ["cab"], ["cbcbcca"], ["ceace"], ["dac"], ["ee"]]'},
        {'input': '["ded", "ccdcacac", "cabacdc", "", "cdce", "badee", "ddabdca", "cbdecd", "eedebbaa", "e", "bacbb", "ddeba", "", "bbeaeebe"]', 'expected_output': '[["", ""], ["bacbb"], ["badee"], ["bbeaeebe"], ["cabacdc"], ["cbdecd"], ["ccdcacac"], ["cdce"], ["ddabdca"], ["ddeba"], ["ded"], ["e"], ["eedebbaa"]]'},
        {'input': '["bcb", "ac", "cbdbaeeb"]', 'expected_output': '[["ac"], ["bcb"], ["cbdbaeeb"]]'},
        {'input': '["e", "dbbeb", "aadde", "d", "", "", "ebd"]', 'expected_output': '[["", ""], ["aadde"], ["d"], ["dbbeb"], ["e"], ["ebd"]]'},
        {'input': '["e", "ecabaec", "cca", "ed", "abc", "bdb", "accd"]', 'expected_output': '[["abc"], ["accd"], ["bdb"], ["cca"], ["e"], ["ecabaec"], ["ed"]]'},
        {'input': '["", "abe", "edeccda"]', 'expected_output': '[[""], ["abe"], ["edeccda"]]'},
        {'input': '["cacbc", "ecbceab", "eaa", "beddac", "baebda", "", "c", "abedeb", "a", "bceaed", "bdd", "ecd", "d", "ebcdb"]', 'expected_output': '[[""], ["a"], ["abedeb"], ["baebda"], ["bceaed"], ["bdd"], ["beddac"], ["c"], ["cacbc"], ["d"], ["eaa"], ["ebcdb"], ["ecbceab"], ["ecd"]]'},
        {'input': '["eeeecd", "eadcbc", "babbcb", "ad", "bd", "acbbbbdc", "acca", "aac", "a"]', 'expected_output': '[["a"], ["aac"], ["acbbbbdc"], ["acca"], ["ad"], ["babbcb"], ["bd"], ["eadcbc"], ["eeeecd"]]'},
        {'input': '["", "", "bc", "e", "be"]', 'expected_output': '[["", ""], ["bc"], ["be"], ["e"]]'},
        {'input': '["ccccac", "dcdadca", "db", "bdcaad", "cabeced", "ac", "cadcdb", "ebaab", "d", "cadcec"]', 'expected_output': '[["ac"], ["bdcaad"], ["cabeced"], ["cadcdb"], ["cadcec"], ["ccccac"], ["d"], ["db"], ["dcdadca"], ["ebaab"]]'},
        {'input': '["aeded", "eb", "cdadb"]', 'expected_output': '[["aeded"], ["cdadb"], ["eb"]]'},
        {'input': '["cbcaca", "", "bebebb", "bbbebd", "bacbdee", "be", "adbdcd", "a", "bcbd", "cce", "dcadadbc"]', 'expected_output': '[[""], ["a"], ["adbdcd"], ["bacbdee"], ["bbbebd"], ["bcbd"], ["be"], ["bebebb"], ["cbcaca"], ["cce"], ["dcadadbc"]]'},
        {'input': '["", "e"]', 'expected_output': '[[""], ["e"]]'},
        {'input': '["", "daceae", "c", "a"]', 'expected_output': '[[""], ["a"], ["c"], ["daceae"]]'},
        {'input': '["deebdec", "ea", "cebecba", "cddea", "cecdb", "dcbe", "da", "cc", "bba", "caaadd"]', 'expected_output': '[["bba"], ["caaadd"], ["cc"], ["cddea"], ["cebecba"], ["cecdb"], ["da"], ["dcbe"], ["deebdec"], ["ea"]]'},
        {'input': '["dd", "ecbe"]', 'expected_output': '[["dd"], ["ecbe"]]'},
        {'input': '["", "badbdee", "aeeed", "ab", "b", "adceeb", "bcbcbe", "bd", "eb", "bc", "cbae", "ecacda", "bc", "ea"]', 'expected_output': '[[""], ["ab"], ["adceeb"], ["aeeed"], ["b"], ["badbdee"], ["bc", "bc"], ["bcbcbe"], ["bd"], ["cbae"], ["ea"], ["eb"], ["ecacda"]]'},
        {'input': '["ececbedb", "eccddbc", "bddc", "aadeeacc", "beeacbb", "ecc", "aadadea", ""]', 'expected_output': '[[""], ["aadadea"], ["aadeeacc"], ["bddc"], ["beeacbb"], ["ecc"], ["eccddbc"], ["ececbedb"]]'},
        {'input': '["cde", "", "eed", "dcba", "c", "cadc", "bbd", "ba", "ebdacaba", "baecdde", "bececdd", "abdea", "bbbdbee"]', 'expected_output': '[[""], ["abdea"], ["ba"], ["baecdde"], ["bbbdbee"], ["bbd"], ["bececdd"], ["c"], ["cadc"], ["cde"], ["dcba"], ["ebdacaba"], ["eed"]]'},
        {'input': '["bbae", "de"]', 'expected_output': '[["bbae"], ["de"]]'},
        {'input': '["ee", "bdbcaee", "aacaddc", "dcccb", "aaeedaaa", "cebcdad", "de", "cbc", "ae", "ba", "eaadedbd", "ea", "ccd", ""]', 'expected_output': '[[""], ["aacaddc"], ["aaeedaaa"], ["ae", "ea"], ["ba"], ["bdbcaee"], ["cbc"], ["ccd"], ["cebcdad"], ["dcccb"], ["de"], ["eaadedbd"], ["ee"]]'},
        {'input': '["bd", "abb", "cca", "adccdaea", ""]', 'expected_output': '[[""], ["abb"], ["adccdaea"], ["bd"], ["cca"]]'},
        {'input': '["bbc", "cbd"]', 'expected_output': '[["bbc"], ["cbd"]]'},
        {'input': '["a", "bebc", "be", "cbc", "beadc", "aecbcb", "eeeceedc", "dade", "ecead", "d", "b", "ecbe", "", "bd"]', 'expected_output': '[[""], ["a"], ["aecbcb"], ["b"], ["bd"], ["be"], ["beadc"], ["bebc"], ["cbc"], ["d"], ["dade"], ["ecbe"], ["ecead"], ["eeeceedc"]]'},
        {'input': '["ddeae", "cdddb", "e", "d", "baabed", "ae", "ce", "ceaadbdd", "", "bb"]', 'expected_output': '[[""], ["ae"], ["baabed"], ["bb"], ["cdddb"], ["ce"], ["ceaadbdd"], ["d"], ["ddeae"], ["e"]]'},
        {'input': '["eeebdae", "a", "eaec", "caddeddc", "dc", "adbab", "accb", "cbeca"]', 'expected_output': '[["a"], ["accb"], ["adbab"], ["caddeddc"], ["cbeca"], ["dc"], ["eaec"], ["eeebdae"]]'},
        {'input': '["ea", "dacbbb", "acd", "ddedcadd", "eddcbcda", "ea", "baada", "bd", "ddbdcbbc", "eaecceee", "bddb", "bdcba"]', 'expected_output': '[["acd"], ["baada"], ["bd"], ["bdcba"], ["bddb"], ["dacbbb"], ["ddbdcbbc"], ["ddedcadd"], ["ea", "ea"], ["eaecceee"], ["eddcbcda"]]'},
        {'input': '["dae", "becd", "ed", "", "cba", "ae", "caaed", "ba", "aecc", "e"]', 'expected_output': '[[""], ["ae"], ["aecc"], ["ba"], ["becd"], ["caaed"], ["cba"], ["dae"], ["e"], ["ed"]]'},
        {'input': '["", "ceacac", "ccc"]', 'expected_output': '[[""], ["ccc"], ["ceacac"]]'},
        {'input': '["dbcbcbeb", "eebabbec", "d", "", "bb", "dedaede", "ecedabeb", "b", "ebbcaed", "d", "ea", "ab", "cddedbcd"]', 'expected_output': '[[""], ["ab"], ["b"], ["bb"], ["cddedbcd"], ["d", "d"], ["dbcbcbeb"], ["dedaede"], ["ea"], ["ebbcaed"], ["ecedabeb"], ["eebabbec"]]'},
        {'input': '["cde", "abcceb", "badbeec", "bad", "b", "acacba", "d", "b", "", "ccbcacad"]', 'expected_output': '[[""], ["abcceb"], ["acacba"], ["b", "b"], ["bad"], ["badbeec"], ["ccbcacad"], ["cde"], ["d"]]'},
        {'input': '["", "cacbb", "", "e", "", "d"]', 'expected_output': '[["", "", ""], ["cacbb"], ["d"], ["e"]]'},
        {'input': '["abddddc", "daeadca", "bdce", "bacdcab", "bdebb", "eddccdab", "abba", "", "ab", "ddc", "accac", "bad", "d", ""]', 'expected_output': '[["", ""], ["ab"], ["abba"], ["abddddc"], ["accac"], ["bacdcab"], ["bad"], ["bdce"], ["bdebb"], ["d"], ["daeadca"], ["ddc"], ["eddccdab"]]'},
        {'input': '["ecbd", "dace", "ccad", "ebdaaad", "bacccc", "bcd", ""]', 'expected_output': '[[""], ["bacccc"], ["bcd"], ["ccad"], ["dace"], ["ebdaaad"], ["ecbd"]]'},
        {'input': '["ceabad", "bdbadcbd", "", "a", "c", "bcdee", "eabcbeea", "d", "ddededb"]', 'expected_output': '[[""], ["a"], ["bcdee"], ["bdbadcbd"], ["c"], ["ceabad"], ["d"], ["ddededb"], ["eabcbeea"]]'},
        {'input': '["dbda", "cdeddc", "cdaa", "e", "cbadd", "e", "bdae"]', 'expected_output': '[["bdae"], ["cbadd"], ["cdaa"], ["cdeddc"], ["dbda"], ["e", "e"]]'},
        {'input': '["ebadd", "bcaceebe", "ebbed", "caecda", "dab", "abb", "cbbde", "e", "be", "edeac", "bcce", "dc"]', 'expected_output': '[["abb"], ["bcaceebe"], ["bcce"], ["be"], ["caecda"], ["cbbde"], ["dab"], ["dc"], ["e"], ["ebadd"], ["ebbed"], ["edeac"]]'},
        {'input': '["c", "cabde", "dbaebec", "ebdcecba", "eaee", "cdabba", "bbce", "cebed", ""]', 'expected_output': '[[""], ["bbce"], ["c"], ["cabde"], ["cdabba"], ["cebed"], ["dbaebec"], ["eaee"], ["ebdcecba"]]'},
        {'input': '["a", "aceeecdc", "baacbad", "abbed", "bced", "cccebb", "", "cc", "dd", "d"]', 'expected_output': '[[""], ["a"], ["abbed"], ["aceeecdc"], ["baacbad"], ["bced"], ["cc"], ["cccebb"], ["d"], ["dd"]]'},
        {'input': '["daec", "ccadcba", "", "deabeb"]', 'expected_output': '[[""], ["ccadcba"], ["daec"], ["deabeb"]]'},
        {'input': '["bebbcbed", "ebacaeee", "de"]', 'expected_output': '[["bebbcbed"], ["de"], ["ebacaeee"]]'},
        {'input': '["eabba", "bae", "beebbd", "ab", "cdecd", "a", "cccbeb", "eebccd", "eec", "aad", "cbbedae", "", "aadccc"]', 'expected_output': '[[""], ["a"], ["aad"], ["aadccc"], ["ab"], ["bae"], ["beebbd"], ["cbbedae"], ["cccbeb"], ["cdecd"], ["eabba"], ["eebccd"], ["eec"]]'},
        {'input': '["", "ccdaee", "daecc", "bddbb", "dcb"]', 'expected_output': '[[""], ["bddbb"], ["ccdaee"], ["daecc"], ["dcb"]]'},
        {'input': '["cdb", "adedadee", "daaeb", "aca", "adbcac", "edbdcb", "", "eeb", "cecd", "cb", "abdeeeba", "", "eae", "aadd"]', 'expected_output': '[["", ""], ["aadd"], ["abdeeeba"], ["aca"], ["adbcac"], ["adedadee"], ["cb"], ["cdb"], ["cecd"], ["daaeb"], ["eae"], ["edbdcb"], ["eeb"]]'},
        {'input': '["ebcbaaac", "bdbdead"]', 'expected_output': '[["bdbdead"], ["ebcbaaac"]]'},
        {'input': '["cce", "dadceccc", "ba", "ccadcd"]', 'expected_output': '[["ba"], ["ccadcd"], ["cce"], ["dadceccc"]]'},
        {'input': '["dcbba", "bad", "", "ee", "beccc", "cbbbae", "bebbb"]', 'expected_output': '[[""], ["bad"], ["bebbb"], ["beccc"], ["cbbbae"], ["dcbba"], ["ee"]]'},
        {'input': '["bdaeea", "dbc", "dadadbaa", "cd", "dedc"]', 'expected_output': '[["bdaeea"], ["cd"], ["dadadbaa"], ["dbc"], ["dedc"]]'},
        {'input': '["beddec", "bcabeaaa", "daccdc", "bdcacdbb", "d", "ba", "bacaa"]', 'expected_output': '[["ba"], ["bacaa"], ["bcabeaaa"], ["bdcacdbb"], ["beddec"], ["d"], ["daccdc"]]'},
        {'input': '["", "a", "bea", "cddacbc", "dccdab", "ae"]', 'expected_output': '[[""], ["a"], ["ae"], ["bea"], ["cddacbc"], ["dccdab"]]'},
        {'input': '["bbcd", "cbcee", "da", "a", "badcbbdd", "bea", "be"]', 'expected_output': '[["a"], ["badcbbdd"], ["bbcd"], ["be"], ["bea"], ["cbcee"], ["da"]]'},
        {'input': '["dcc", "d", "acbecabd", "adbebdc", "dedade", "aacd", "", "", "bbba", "aabacdc", "beced"]', 'expected_output': '[["", ""], ["aabacdc"], ["aacd"], ["acbecabd"], ["adbebdc"], ["bbba"], ["beced"], ["d"], ["dcc"], ["dedade"]]'},
        {'input': '[""]', 'expected_output': '[[""]]'},
        {'input': '["dcdddb", "deca", "ecbad", "cebacdc", "aeaeaae", "aacabebd", "c", "dca", "cdccaced", "cbceaa", "cdae", "c", "bcdeaea"]', 'expected_output': '[["aacabebd"], ["aeaeaae"], ["bcdeaea"], ["c", "c"], ["cbceaa"], ["cdae", "deca"], ["cdccaced"], ["cebacdc"], ["dca"], ["dcdddb"], ["ecbad"]]'},
        {'input': '["adea", "cabebdb", "cbce", "", "eeedd", "db"]', 'expected_output': '[[""], ["adea"], ["cabebdb"], ["cbce"], ["db"], ["eeedd"]]'},
        {'input': '["cac", "", "ae", "a"]', 'expected_output': '[[""], ["a"], ["ae"], ["cac"]]'},
        {'input': '["bbdddc", "d", "adeea", "ebaeed", "", "bdcbc", "decabbde", "", "dddadcbd", "aaeea", "adbaab", "", "aabededc"]', 'expected_output': '[["", "", ""], ["aabededc"], ["aaeea"], ["adbaab"], ["adeea"], ["bbdddc"], ["bdcbc"], ["d"], ["dddadcbd"], ["decabbde"], ["ebaeed"]]'},
        {'input': '["bdcbdecd", "bdacceda", "cdbdba", "daab", "abbbc", "bdbbab", "abd", "acae", "bdecac", "aeebaedc", "adec", "e", ""]', 'expected_output': '[[""], ["abbbc"], ["abd"], ["acae"], ["adec"], ["aeebaedc"], ["bdacceda"], ["bdbbab"], ["bdcbdecd"], ["bdecac"], ["cdbdba"], ["daab"], ["e"]]'},
        {'input': '["aaeed", "ccda", "add", "", "bca", "abb"]', 'expected_output': '[[""], ["aaeed"], ["abb"], ["add"], ["bca"], ["ccda"]]'},
        {'input': '["cc", "dcccce", "aeb", "addcbe", "cae", "ddddade", "db", ""]', 'expected_output': '[[""], ["addcbe"], ["aeb"], ["cae"], ["cc"], ["db"], ["dcccce"], ["ddddade"]]'},
        {'input': '["cecca", "aeae", "", "ea", "e", "e", ""]', 'expected_output': '[["", ""], ["aeae"], ["cecca"], ["e", "e"], ["ea"]]'},
        {'input': '["dcadedc", "ba", "b", "bade"]', 'expected_output': '[["b"], ["ba"], ["bade"], ["dcadedc"]]'},
        {'input': '["b", "bacbd", "abbbdbe", "dbda", "", "edacab", "", "a", "debbcded", "d", "dedceaed", "d"]', 'expected_output': '[["", ""], ["a"], ["abbbdbe"], ["b"], ["bacbd"], ["d", "d"], ["dbda"], ["debbcded"], ["dedceaed"], ["edacab"]]'},
        {'input': '["ccb", "eadbad", "ecebd"]', 'expected_output': '[["ccb"], ["eadbad"], ["ecebd"]]'},
        {'input': '["", "cabebadb", "", "", "", "ebd", ""]', 'expected_output': '[["", "", "", "", ""], ["cabebadb"], ["ebd"]]'},
        {'input': '["eacbbab", "abd", "e", "bceeadad", "d", "aedbcace", "bab", "ccdbcb", "bdd", "eedaa", "bedece", ""]', 'expected_output': '[[""], ["abd"], ["aedbcace"], ["bab"], ["bceeadad"], ["bdd"], ["bedece"], ["ccdbcb"], ["d"], ["e"], ["eacbbab"], ["eedaa"]]'},
        {'input': '["ccaeecd", "ba", ""]', 'expected_output': '[[""], ["ba"], ["ccaeecd"]]'},
        {'input': '["", "ededcd", "a"]', 'expected_output': '[[""], ["a"], ["ededcd"]]'},
        {'input': '["bbaaed", "bbaaad"]', 'expected_output': '[["bbaaad"], ["bbaaed"]]'},
        {'input': '["ecb", "bb", "cead", "eed", "", "bbcea"]', 'expected_output': '[[""], ["bb"], ["bbcea"], ["cead"], ["ecb"], ["eed"]]'},
        {'input': '["ab", "dbebdd", "eddec", "dcbbe", "ccad", "c"]', 'expected_output': '[["ab"], ["c"], ["ccad"], ["dbebdd"], ["dcbbe"], ["eddec"]]'},
        {'input': '["aebeee", "d", "", "ebedb", "dc", "bebeeea", "bebdde", "eabedbc", "abcb"]', 'expected_output': '[[""], ["abcb"], ["aebeee"], ["bebdde"], ["bebeeea"], ["d"], ["dc"], ["eabedbc"], ["ebedb"]]'},
        {'input': '["cadaacbe", "ddd", "aaacb", "dcaeda", "becb", "cb", "ad", "dcdeebe", "bccaebcd", "adb", "adcb", "eebaed", ""]', 'expected_output': '[[""], ["aaacb"], ["ad"], ["adb"], ["adcb"], ["bccaebcd"], ["becb"], ["cadaacbe"], ["cb"], ["dcaeda"], ["dcdeebe"], ["ddd"], ["eebaed"]]'},
        {'input': '["bbbcdaa", "acb", "dc", "eaeba", "aceabd", "b", "ededab", "eacbcdd", "eeeb", "abbbd", "ebadd", "deceba", "cbce"]', 'expected_output': '[["abbbd"], ["acb"], ["aceabd"], ["b"], ["bbbcdaa"], ["cbce"], ["dc"], ["deceba"], ["eacbcdd"], ["eaeba"], ["ebadd"], ["ededab"], ["eeeb"]]'},
        {'input': '["a", "abbaeb", "cdd", "ebdeaeca", "aea", "bedcc", "cebccd"]', 'expected_output': '[["a"], ["abbaeb"], ["aea"], ["bedcc"], ["cdd"], ["cebccd"], ["ebdeaeca"]]'},
        {'input': '["", "bcadde", "d", "dad", "aecbcc", "d", "bdbdecdc", "c", "bca", "bcb"]', 'expected_output': '[[""], ["aecbcc"], ["bca"], ["bcadde"], ["bcb"], ["bdbdecdc"], ["c"], ["d", "d"], ["dad"]]'},
        {'input': '["cb", "dcabceba", "cdd", "ac"]', 'expected_output': '[["ac"], ["cb"], ["cdd"], ["dcabceba"]]'},
        {'input': '["a", "bbead", "ecccbcb", "bdaada", "dacd", "b", "bdcbd", "ccc", "eba", "aacbcd", "ced"]', 'expected_output': '[["a"], ["aacbcd"], ["b"], ["bbead"], ["bdaada"], ["bdcbd"], ["ccc"], ["ced"], ["dacd"], ["eba"], ["ecccbcb"]]'},
        {'input': '["cbbdddd", "ecba", "acddebc", "cb", "", "bbbdccca", "dadd", "d", "bd", "abcaebe", "", "accbabcc", "dcaeadc"]', 'expected_output': '[["", ""], ["abcaebe"], ["accbabcc"], ["acddebc"], ["bbbdccca"], ["bd"], ["cb"], ["cbbdddd"], ["d"], ["dadd"], ["dcaeadc"], ["ecba"]]'},
        {'input': '["bbcdbee", "bc", "", "ccadb", "aebbca", "dde", "ea", "d", "de", "bccbed"]', 'expected_output': '[[""], ["aebbca"], ["bbcdbee"], ["bc"], ["bccbed"], ["ccadb"], ["d"], ["dde"], ["de"], ["ea"]]'},
        {'input': '["aceebbbc", "", "debda", "adc", "dcb", "c", "", "", "c", "aa", "abbbcad", "cadb", "", "aaee"]', 'expected_output': '[["", "", "", ""], ["aa"], ["aaee"], ["abbbcad"], ["aceebbbc"], ["adc"], ["c", "c"], ["cadb"], ["dcb"], ["debda"]]'},
        {'input': '["aa", "dc", "ddbaba", "dbdad", "aeadbdd", "dbbcaaa", "dacbbde", "cbede"]', 'expected_output': '[["aa"], ["aeadbdd"], ["cbede"], ["dacbbde"], ["dbbcaaa"], ["dbdad"], ["dc"], ["ddbaba"]]'},
        {'input': '["ebcdd", "dbbdec"]', 'expected_output': '[["dbbdec"], ["ebcdd"]]'},
        {'input': '["e", "", "dccbabb", "bbbcacd", "bc", "ceecce", "cdb", "ce", "accecca", "acb", "dbea", "cb", "abc"]', 'expected_output': '[[""], ["abc", "acb"], ["accecca"], ["bbbcacd", "dccbabb"], ["bc", "cb"], ["cdb"], ["ce"], ["ceecce"], ["dbea"], ["e"]]'},
        {'input': '["beaad", "bee", "ea", "ccaace"]', 'expected_output': '[["beaad"], ["bee"], ["ccaace"], ["ea"]]'},
        {'input': '["bbaeaaac", "eaddda", "cecbcb", "cdc", "dbceb", "cceb", "c", "cceab", "", "aed"]', 'expected_output': '[[""], ["aed"], ["bbaeaaac"], ["c"], ["cceab"], ["cceb"], ["cdc"], ["cecbcb"], ["dbceb"], ["eaddda"]]'},
        {'input': '["eacdbbd", "", "aabbac", "e"]', 'expected_output': '[[""], ["aabbac"], ["e"], ["eacdbbd"]]'},
        {'input': '["cbedea", "da", "adcab", "cdcdd", "aaddceb"]', 'expected_output': '[["aaddceb"], ["adcab"], ["cbedea"], ["cdcdd"], ["da"]]'},
        {'input': '["dcdc", "e", "da", "", "ee", "b", "ea", "cedabcac", "ddad", "a", "ee", "cccdcce", "d", "cadebcc"]', 'expected_output': '[[""], ["a"], ["b"], ["cadebcc"], ["cccdcce"], ["cedabcac"], ["d"], ["da"], ["dcdc"], ["ddad"], ["e"], ["ea"], ["ee", "ee"]]'},
        {'input': '["b", "b"]', 'expected_output': '[["b", "b"]]'},
        {'input': '["cdaed", "bcce", "bcaa", "ddbadde", "d", "decaebce", "dbcb", "adee"]', 'expected_output': '[["adee"], ["bcaa"], ["bcce"], ["cdaed"], ["d"], ["dbcb"], ["ddbadde"], ["decaebce"]]'},
        {'input': '["dba", "bbdebda", "badd", "cacbb", "ecebbeae", "", "edebbd", "a", "ddbdd", "eeae", ""]', 'expected_output': '[["", ""], ["a"], ["badd"], ["bbdebda"], ["cacbb"], ["dba"], ["ddbdd"], ["ecebbeae"], ["edebbd"], ["eeae"]]'},
        {'input': '["bebdbdb", "ae", "", "a", "b", "cbc"]', 'expected_output': '[[""], ["a"], ["ae"], ["b"], ["bebdbdb"], ["cbc"]]'},
        {'input': '["dcbbd", "ad", "ce", "cddbbbb", "eecbddbe", "dcddd", "dccaaacb", ""]', 'expected_output': '[[""], ["ad"], ["cddbbbb"], ["ce"], ["dcbbd"], ["dccaaacb"], ["dcddd"], ["eecbddbe"]]'},
        {'input': '["ebdccbb", "", "", "", "cdabcd", "edbeec", "c", "bb", "cae", "ec", "e"]', 'expected_output': '[["", "", ""], ["bb"], ["c"], ["cae"], ["cdabcd"], ["e"], ["ebdccbb"], ["ec"], ["edbeec"]]'},
        {'input': '["dbbcac", "babbeb", "e", "eeded", "aeeba", "dae", "dbcebd", "eebcdcaa"]', 'expected_output': '[["aeeba"], ["babbeb"], ["dae"], ["dbbcac"], ["dbcebd"], ["e"], ["eebcdcaa"], ["eeded"]]'},
        {'input': '["bace", "b", "be", "deedabb", "ddddaba", "aecddd", "abbed"]', 'expected_output': '[["abbed"], ["aecddd"], ["b"], ["bace"], ["be"], ["ddddaba"], ["deedabb"]]'},
        {'input': '["aeec", "d", "acaba", "", "dcbbabd", "ecab", "bddbca", "cdca", "d", "d", "dabbd", "a", "ecaaecda"]', 'expected_output': '[[""], ["a"], ["acaba"], ["aeec"], ["bddbca"], ["cdca"], ["d", "d", "d"], ["dabbd"], ["dcbbabd"], ["ecaaecda"], ["ecab"]]'},
        {'input': '["ddccda", "", "baa", "abdb", "deca", "a", "caadbab", "cab", "ccbda", "daacca", "deddb", "cbee", "cdec", "ecbcceea"]', 'expected_output': '[[""], ["a"], ["abdb"], ["baa"], ["caadbab"], ["cab"], ["cbee"], ["ccbda"], ["cdec"], ["daacca"], ["ddccda"], ["deca"], ["deddb"], ["ecbcceea"]]'},
        {'input': '["cdadbbab", "e", "ad", "", "dbbe", "beea"]', 'expected_output': '[[""], ["ad"], ["beea"], ["cdadbbab"], ["dbbe"], ["e"]]'},
        {'input': '["cbebcdca", "a", "c", "deceaa", "bae", "cdebdad", "aeceb", "abab", "d"]', 'expected_output': '[["a"], ["abab"], ["aeceb"], ["bae"], ["c"], ["cbebcdca"], ["cdebdad"], ["d"], ["deceaa"]]'},
        {'input': '["cadaa", "aaedbbe", "cddcc", "a", "ecca", "", "dce", "cec", "bc", "c", "bdd", "acadeb", ""]', 'expected_output': '[["", ""], ["a"], ["aaedbbe"], ["acadeb"], ["bc"], ["bdd"], ["c"], ["cadaa"], ["cddcc"], ["cec"], ["dce"], ["ecca"]]'},
        {'input': '["eccebc", "cabebbcd", ""]', 'expected_output': '[[""], ["cabebbcd"], ["eccebc"]]'},
        {'input': '["dade", "ecbd", "db", "cbbaca"]', 'expected_output': '[["cbbaca"], ["dade"], ["db"], ["ecbd"]]'},
        {'input': '["cacbda", "ac", "dbbbacbe", "ccce", "ddacedd", "daeeccc", "dddc", "ecd"]', 'expected_output': '[["ac"], ["cacbda"], ["ccce"], ["daeeccc"], ["dbbbacbe"], ["ddacedd"], ["dddc"], ["ecd"]]'},
        {'input': '["e", "ae", "", "bacaabe", "ce", "acbdacbd", "cebeb", "bebbe", "db", "bae", "bea", "", "cbccebaa", "dcee"]', 'expected_output': '[["", ""], ["acbdacbd"], ["ae"], ["bacaabe"], ["bae", "bea"], ["bebbe"], ["cbccebaa"], ["ce"], ["cebeb"], ["db"], ["dcee"], ["e"]]'},
        {'input': '["d", "dac", "db", "ebdba", "ecaaeaaa", "acbdecda"]', 'expected_output': '[["acbdecda"], ["d"], ["dac"], ["db"], ["ebdba"], ["ecaaeaaa"]]'},
        {'input': '["be", "cdeace"]', 'expected_output': '[["be"], ["cdeace"]]'},
        {'input': '["adde"]', 'expected_output': '[["adde"]]'},
        {'input': '["d", "cdacdbc", "", "bdb", "ad", "e", "cedace"]', 'expected_output': '[[""], ["ad"], ["bdb"], ["cdacdbc"], ["cedace"], ["d"], ["e"]]'},
        {'input': '["eadece", "bddcb", "eb"]', 'expected_output': '[["bddcb"], ["eadece"], ["eb"]]'},
        {'input': '["aaeb", "ad", "aecdbe", "bdcdcd", "dcdecbb", "abcaa", "aecce", "", "a", "cbeeca", "cb", "cbbe", "", "d"]', 'expected_output': '[["", ""], ["a"], ["aaeb"], ["abcaa"], ["ad"], ["aecce"], ["aecdbe"], ["bdcdcd"], ["cb"], ["cbbe"], ["cbeeca"], ["d"], ["dcdecbb"]]'},
        {'input': '["dddbccab"]', 'expected_output': '[["dddbccab"]]'},
        {'input': '["baeab", "cdaabc", "cdbee", ""]', 'expected_output': '[[""], ["baeab"], ["cdaabc"], ["cdbee"]]'},
        {'input': '["ddac", "", "dbabaae", "acdba", "becac", "baaacbed", "ddbeaecb", "baddcbac", "cdebce", "beeaebde", "aaaabdd"]', 'expected_output': '[[""], ["aaaabdd"], ["acdba"], ["baaacbed"], ["baddcbac"], ["becac"], ["beeaebde"], ["cdebce"], ["dbabaae"], ["ddac"], ["ddbeaecb"]]'},
        {'input': '["ecc", "dcace", "ebbb", "cbbdb", "aaadaeab", "eae", "aec", "aaeae", "", "dc", "cdccbe", "cca", "daaecda"]', 'expected_output': '[[""], ["aaadaeab"], ["aaeae"], ["aec"], ["cbbdb"], ["cca"], ["cdccbe"], ["daaecda"], ["dc"], ["dcace"], ["eae"], ["ebbb"], ["ecc"]]'},
        {'input': '["daaada", "edc", "aeeccd", "de", "eacca", "", "bddacdea"]', 'expected_output': '[[""], ["aeeccd"], ["bddacdea"], ["daaada"], ["de"], ["eacca"], ["edc"]]'},
        {'input': '["ec", "bdeb", "b", "cad", "eade"]', 'expected_output': '[["b"], ["bdeb"], ["cad"], ["eade"], ["ec"]]'},
        {'input': '["", "cebddeba", "ebbde", "eebbcb", "b"]', 'expected_output': '[[""], ["b"], ["cebddeba"], ["ebbde"], ["eebbcb"]]'},
        {'input': '["cacde", "c", "acceeb", "ebcacd", "bcecbcb", "aaa", "bdeede"]', 'expected_output': '[["aaa"], ["acceeb"], ["bcecbcb"], ["bdeede"], ["c"], ["cacde"], ["ebcacd"]]'},
        {'input': '["eaeeada", "ba", "cba", "", "bcbeaa", "dad", "ebeeda", "aa", "be", "aee", ""]', 'expected_output': '[["", ""], ["aa"], ["aee"], ["ba"], ["bcbeaa"], ["be"], ["cba"], ["dad"], ["eaeeada"], ["ebeeda"]]'},
        {'input': '["ce", "aeaba", "ae", "d", "babbb", "bbaeccd", "ebabe", "ebbd"]', 'expected_output': '[["ae"], ["aeaba"], ["babbb"], ["bbaeccd"], ["ce"], ["d"], ["ebabe"], ["ebbd"]]'},
        {'input': '["cdeace", "", "ccbc", "b", "aeb", "d", "c", "eadb", "dee", "a", "edbbeceb"]', 'expected_output': '[[""], ["a"], ["aeb"], ["b"], ["c"], ["ccbc"], ["cdeace"], ["d"], ["dee"], ["eadb"], ["edbbeceb"]]'},
        {'input': '["ddae", "decea", "daeedc", "ceed", "ea", "ed", "cbcbceab", "", "bac"]', 'expected_output': '[[""], ["bac"], ["cbcbceab"], ["ceed"], ["daeedc"], ["ddae"], ["decea"], ["ea"], ["ed"]]'},
        {'input': '["c", "eac", "cbcb", "aa", "cae", "acdd", "eaa", "dd", "cc", "bcbebaca", "", "bb"]', 'expected_output': '[[""], ["aa"], ["acdd"], ["bb"], ["bcbebaca"], ["c"], ["cae", "eac"], ["cbcb"], ["cc"], ["dd"], ["eaa"]]'},
        {'input': '["aadacdee", "ddccacea", "bab", "cdbdcbb", "bcbbbab"]', 'expected_output': '[["aadacdee"], ["bab"], ["bcbbbab"], ["cdbdcbb"], ["ddccacea"]]'},
        {'input': '["eed", "cc", "e", "ccbc", "bedabb", "cc", "beaaa", "ceacdabc"]', 'expected_output': '[["beaaa"], ["bedabb"], ["cc", "cc"], ["ccbc"], ["ceacdabc"], ["e"], ["eed"]]'},
        {'input': '["eadbaad", "aeaade", "dcca", "ccacbd", "deeebba", "ceeea", "edbeebce", "d", "dc"]', 'expected_output': '[["aeaade"], ["ccacbd"], ["ceeea"], ["d"], ["dc"], ["dcca"], ["deeebba"], ["eadbaad"], ["edbeebce"]]'},
        {'input': '["ec", "dea", "bc", "edda", "eeabd", "caceaa", "daaeee", "ebc", "e", "cbb"]', 'expected_output': '[["bc"], ["caceaa"], ["cbb"], ["daaeee"], ["dea"], ["e"], ["ebc"], ["ec"], ["edda"], ["eeabd"]]'},
        {'input': '["bdca", "babedc", "a", "d", "ccaabbd", "cbade", "ee"]', 'expected_output': '[["a"], ["babedc"], ["bdca"], ["cbade"], ["ccaabbd"], ["d"], ["ee"]]'},
        {'input': '["ccbacde", "cbdacbcd", "cebbacac", "cbce", "eb", "eaebe"]', 'expected_output': '[["cbce"], ["cbdacbcd"], ["ccbacde"], ["cebbacac"], ["eaebe"], ["eb"]]'},
        {'input': '["ccdb", "aad", "adab", "accd", "ddbebdbc", "d", "bada", "ce", "bccceb", "dccb"]', 'expected_output': '[["aad"], ["accd"], ["adab", "bada"], ["bccceb"], ["ccdb", "dccb"], ["ce"], ["d"], ["ddbebdbc"]]'},
        {'input': '["adceecce", "db", "", "", "ea", "ecbe", "cd", "bdec", "dbeded", "b"]', 'expected_output': '[["", ""], ["adceecce"], ["b"], ["bdec"], ["cd"], ["db"], ["dbeded"], ["ea"], ["ecbe"]]'},
        {'input': '["dda", "dcadeeb", "ed", "", "a"]', 'expected_output': '[[""], ["a"], ["dcadeeb"], ["dda"], ["ed"]]'},
        {'input': '["cb", "ebed", "adcadce", "caa", "eaeebbae", "cbaadebc", "cba", "eaecd", "eecddcb"]', 'expected_output': '[["adcadce"], ["caa"], ["cb"], ["cba"], ["cbaadebc"], ["eaecd"], ["eaeebbae"], ["ebed"], ["eecddcb"]]'},
        {'input': '["deadccdb", "bcedc", "c", "baba", "", "baee", "a", "ee", "ccbebcdb", "aceba", "c"]', 'expected_output': '[[""], ["a"], ["aceba"], ["baba"], ["baee"], ["bcedc"], ["c", "c"], ["ccbebcdb"], ["deadccdb"], ["ee"]]'},
        {'input': '["cadbe", "cadcace", "eadddede", "aeaaacb", "caaddcc", "eedd"]', 'expected_output': '[["aeaaacb"], ["caaddcc"], ["cadbe"], ["cadcace"], ["eadddede"], ["eedd"]]'},
        {'input': '["caae", "aebabee", "c", "edb", "bbaa"]', 'expected_output': '[["aebabee"], ["bbaa"], ["c"], ["caae"], ["edb"]]'},
        {'input': '["ec", "", "eacceb", "b", "aebaeba", "", "dbeedbca", "ccdeebdc", "cdba", "edbcbeca", "a", "beaedbae", "aed", "cabbaea"]', 'expected_output': '[["", ""], ["a"], ["aebaeba"], ["aed"], ["b"], ["beaedbae"], ["cabbaea"], ["ccdeebdc"], ["cdba"], ["dbeedbca"], ["eacceb"], ["ec"], ["edbcbeca"]]'},
        {'input': '["edacbbb", "dee", "bbeca"]', 'expected_output': '[["bbeca"], ["dee"], ["edacbbb"]]'},
        {'input': '["abd", "edc", "", "babbc", "d"]', 'expected_output': '[[""], ["abd"], ["babbc"], ["d"], ["edc"]]'},
        {'input': '["bbcaebd", "", "eeaacead", "dbadbe"]', 'expected_output': '[[""], ["bbcaebd"], ["dbadbe"], ["eeaacead"]]'},
        {'input': '["bbd", "", "ecedc", "daedeb", "ccaa", "ceadb"]', 'expected_output': '[[""], ["bbd"], ["ccaa"], ["ceadb"], ["daedeb"], ["ecedc"]]'},
        {'input': '["ecbd", "cbddaab", "c", "e", "aaea", "bdb", "baebbcca", "ebceabee", "aacb", "cdbeeece"]', 'expected_output': '[["aacb"], ["aaea"], ["baebbcca"], ["bdb"], ["c"], ["cbddaab"], ["cdbeeece"], ["e"], ["ebceabee"], ["ecbd"]]'},
        {'input': '["adccdcaa", "c", "eedcdcc", "", "eccea", "ccee"]', 'expected_output': '[[""], ["adccdcaa"], ["c"], ["ccee"], ["eccea"], ["eedcdcc"]]'},
        {'input': '["cdd", "dcbb", "b"]', 'expected_output': '[["b"], ["cdd"], ["dcbb"]]'},
        {'input': '["acbcac", "dedacb", "badd", "ee"]', 'expected_output': '[["acbcac"], ["badd"], ["dedacb"], ["ee"]]'},
        {'input': '["bce", "bdaacbbb", "eeaca", "cd", "abac", "", "abcbbe", "de", "bebdcdb", "babedcd", "a", "bec", "abcabe"]', 'expected_output': '[[""], ["a"], ["abac"], ["abcabe"], ["abcbbe"], ["babedcd"], ["bce", "bec"], ["bdaacbbb"], ["bebdcdb"], ["cd"], ["de"], ["eeaca"]]'},
        {'input': '["cecdbdb", "", "ddbadb", "aec", "bab", "deeaccc", "dbdedbe", "aadbeca", "dd", "ea", "", "", "eb"]', 'expected_output': '[["", "", ""], ["aadbeca"], ["aec"], ["bab"], ["cecdbdb"], ["dbdedbe"], ["dd"], ["ddbadb"], ["deeaccc"], ["ea"], ["eb"]]'},
        {'input': '["ca", "cd", "bbabab", "abeadab", "bbd", "dcce", ""]', 'expected_output': '[[""], ["abeadab"], ["bbabab"], ["bbd"], ["ca"], ["cd"], ["dcce"]]'},
        {'input': '["ad", "cdec", "e", "abaece", "aabcaccc", "cddaa", "dcabd", "dadaabcc", "", "dcbeeee", "ed", "d", "cceba", ""]', 'expected_output': '[["", ""], ["aabcaccc"], ["abaece"], ["ad"], ["cceba"], ["cddaa"], ["cdec"], ["d"], ["dadaabcc"], ["dcabd"], ["dcbeeee"], ["e"], ["ed"]]'},
        {'input': '["ab", "ba", "a", "cadabdb", "daadeec", "cdbe", "caaeedab"]', 'expected_output': '[["a"], ["ab", "ba"], ["caaeedab"], ["cadabdb"], ["cdbe"], ["daadeec"]]'},
        {'input': '["ddda", "caeae", "beaba", "ecd"]', 'expected_output': '[["beaba"], ["caeae"], ["ddda"], ["ecd"]]'},
        {'input': '["ceeba", "bcbbeaae", "aabe", "bbcecbeb", "eb"]', 'expected_output': '[["aabe"], ["bbcecbeb"], ["bcbbeaae"], ["ceeba"], ["eb"]]'},
        {'input': '["", "acdac", "c", "ebd"]', 'expected_output': '[[""], ["acdac"], ["c"], ["ebd"]]'},
        {'input': '["bcccecdd", "cbe", "", "bdabda", "eda", "aeee", "e", "dbecbeed", "bceabc"]', 'expected_output': '[[""], ["aeee"], ["bcccecdd"], ["bceabc"], ["bdabda"], ["cbe"], ["dbecbeed"], ["e"], ["eda"]]'},
        {'input': '[""]', 'expected_output': '[[""]]'},
        {'input': '["dbb", "ccdc", "", "beee", "cabc", "ea", "bd", "aeb", "bdda", "b", "dd", "bebdbadb", "eedbcabe"]', 'expected_output': '[[""], ["aeb"], ["b"], ["bd"], ["bdda"], ["bebdbadb"], ["beee"], ["cabc"], ["ccdc"], ["dbb"], ["dd"], ["ea"], ["eedbcabe"]]'},
        {'input': '["baaaeb", "db", "d"]', 'expected_output': '[["baaaeb"], ["d"], ["db"]]'},
        {'input': '["bebc", "cbbaecbc", "adcee"]', 'expected_output': '[["adcee"], ["bebc"], ["cbbaecbc"]]'},
        {'input': '["aecccc", "a", "ae", "d", "", "dabccba", "c", "c", "bc", "bddccbe", "cecbdab", "cccac", "aeadc", "dcccdde"]', 'expected_output': '[[""], ["a"], ["ae"], ["aeadc"], ["aecccc"], ["bc"], ["bddccbe"], ["c", "c"], ["cccac"], ["cecbdab"], ["d"], ["dabccba"], ["dcccdde"]]'},
        {'input': '["abcedae", "", "bcc"]', 'expected_output': '[[""], ["abcedae"], ["bcc"]]'},
        {'input': '["deddece", "ab", "bebbbec", "caedbeed", "cacc", "eee", "db", "e"]', 'expected_output': '[["ab"], ["bebbbec"], ["cacc"], ["caedbeed"], ["db"], ["deddece"], ["e"], ["eee"]]'},
        {'input': '["ecdbe", "bc", "eddede", "", "accbbeda", "dacebaee"]', 'expected_output': '[[""], ["accbbeda"], ["bc"], ["dacebaee"], ["ecdbe"], ["eddede"]]'},
        {'input': '["bbba", "eaebeb", "decaca", "dcde", "dde", "edda", "e", "ebcaca", "debbaac", "d", "acdeead", "deabceb", "adb"]', 'expected_output': '[["acdeead"], ["adb"], ["bbba"], ["d"], ["dcde"], ["dde"], ["deabceb"], ["debbaac"], ["decaca"], ["e"], ["eaebeb"], ["ebcaca"], ["edda"]]'},
        {'input': '["c"]', 'expected_output': '[["c"]]'},
        {'input': '["abaeee", "e", "adcbae", "a", "ade", "dcbcabcb", "bd", "ac", "edccdac", "dbaebdae", "aed", "ded"]', 'expected_output': '[["a"], ["abaeee"], ["ac"], ["adcbae"], ["ade", "aed"], ["bd"], ["dbaebdae"], ["dcbcabcb"], ["ded"], ["e"], ["edccdac"]]'},
        {'input': '["cedc", "a", "adb", "beeea", "acbb", "deca", "", "dabcea", "aeebde", "dbeccaca", "", "ecba", "b", ""]', 'expected_output': '[["", "", ""], ["a"], ["acbb"], ["adb"], ["aeebde"], ["b"], ["beeea"], ["cedc"], ["dabcea"], ["dbeccaca"], ["deca"], ["ecba"]]'},
        {'input': '["bed", "ce", "bce", "be", "aaadc", "cedebdb", "badbd", "b"]', 'expected_output': '[["aaadc"], ["b"], ["badbd"], ["bce"], ["be"], ["bed"], ["ce"], ["cedebdb"]]'},
        {'input': '["", "e", "ccc", "eaebcce", "cddccb", "ae", "ac", "b", "aa", "dceecabe", "ebabbcbb", "cd", "", "ae"]', 'expected_output': '[["", ""], ["aa"], ["ac"], ["ae", "ae"], ["b"], ["ccc"], ["cd"], ["cddccb"], ["dceecabe"], ["e"], ["eaebcce"], ["ebabbcbb"]]'},
        {'input': '["cba", "abddbda", "bee", "babab", "dab", "", "bedeb", "aabeea", "cac", "b"]', 'expected_output': '[[""], ["aabeea"], ["abddbda"], ["b"], ["babab"], ["bedeb"], ["bee"], ["cac"], ["cba"], ["dab"]]'},
        {'input': '["ed", "ecddaa", "adbdeea", "cd", "eabbbb", "b", "aadbaed", "debaa", "debccdcb"]', 'expected_output': '[["aadbaed"], ["adbdeea"], ["b"], ["cd"], ["debaa"], ["debccdcb"], ["eabbbb"], ["ecddaa"], ["ed"]]'},
        {'input': '["cbcdaabb", "", "aaedacc", "beb", "d", "deabb", "eedabddc", "eacea", "ccec", "db", "b", "cdeee", "eb"]', 'expected_output': '[[""], ["aaedacc"], ["b"], ["beb"], ["cbcdaabb"], ["ccec"], ["cdeee"], ["d"], ["db"], ["deabb"], ["eacea"], ["eb"], ["eedabddc"]]'},
        {'input': '["dc", "acaebc", "aecab", "e", "", "eceab"]', 'expected_output': '[[""], ["acaebc"], ["aecab"], ["dc"], ["e"], ["eceab"]]'},
        {'input': '["bab", "bcbdad", "", "cdabdba", "", "dcedbee", "aeec", "aecaadde", "c", "abaaaca", "bad"]', 'expected_output': '[["", ""], ["abaaaca"], ["aecaadde"], ["aeec"], ["bab"], ["bad"], ["bcbdad"], ["c"], ["cdabdba"], ["dcedbee"]]'},
        {'input': '["dbddbdb", "a"]', 'expected_output': '[["a"], ["dbddbdb"]]'},
        {'input': '["adddcd", "", "ccbbe", "cde", "aabc", "cd", "", "", "dabeae"]', 'expected_output': '[["", "", ""], ["aabc"], ["adddcd"], ["ccbbe"], ["cd"], ["cde"], ["dabeae"]]'},
        {'input': '["beebeeca", "aabbd", "cb", "beacdbb", "e"]', 'expected_output': '[["aabbd"], ["beacdbb"], ["beebeeca"], ["cb"], ["e"]]'},
        {'input': '["eaba", "a", "", "d", "eabaaac", "cdaea", "ddaeeada", "d", "beededce", "b"]', 'expected_output': '[[""], ["a"], ["b"], ["beededce"], ["cdaea"], ["d", "d"], ["ddaeeada"], ["eaba"], ["eabaaac"]]'},
        {'input': '["e", "ecbabc", "adcdbd", "bdcd", "a", "d", "", "b", "caeebdaa", "ad"]', 'expected_output': '[[""], ["a"], ["ad"], ["adcdbd"], ["b"], ["bdcd"], ["caeebdaa"], ["d"], ["e"], ["ecbabc"]]'},
        {'input': '["cddbc", "ededee"]', 'expected_output': '[["cddbc"], ["ededee"]]'},
        {'input': '["dbadab", "dbedec"]', 'expected_output': '[["dbadab"], ["dbedec"]]'},
        {'input': '["cca", "ceeb", "ba"]', 'expected_output': '[["ba"], ["cca"], ["ceeb"]]'},
        {'input': '["c", "dedcbea", "ecadb", "db", "dbaecec", "cede", "eaeceae", "c"]', 'expected_output': '[["c", "c"], ["cede"], ["db"], ["dbaecec"], ["dedcbea"], ["eaeceae"], ["ecadb"]]'},
        {'input': '["badbe", "bdacd"]', 'expected_output': '[["badbe"], ["bdacd"]]'},
        {'input': '["cdcebe", "acdabe"]', 'expected_output': '[["acdabe"], ["cdcebe"]]'},
        {'input': '["ddc", "d", "ea", "abda", "baad", "c", "cddaedae", "bdb", "eeeaa", "c", "cebdc", "ecbabbc"]', 'expected_output': '[["abda", "baad"], ["bdb"], ["c", "c"], ["cddaedae"], ["cebdc"], ["d"], ["ddc"], ["ea"], ["ecbabbc"], ["eeeaa"]]'},
        {'input': '["cdddbcb", "cd", "dde", "eacc", "", "cbedab", "cdaacddb", "cddc", "dcbaecec", "", ""]', 'expected_output': '[["", "", ""], ["cbedab"], ["cd"], ["cdaacddb"], ["cddc"], ["cdddbcb"], ["dcbaecec"], ["dde"], ["eacc"]]'},
        {'input': '["b", "bebdb", "dedaddca", "acedeb", "d", "bbccedaa", "ae", "dbebea", "ccaba", "aeebaac", "bdecddd", "ebaa"]', 'expected_output': '[["acedeb"], ["ae"], ["aeebaac"], ["b"], ["bbccedaa"], ["bdecddd"], ["bebdb"], ["ccaba"], ["d"], ["dbebea"], ["dedaddca"], ["ebaa"]]'},
        {'input': '["ebab", "ecc", "decbee", "bdcdd", ""]', 'expected_output': '[[""], ["bdcdd"], ["decbee"], ["ebab"], ["ecc"]]'},
        {'input': '["aaeec", "cad", "aadee"]', 'expected_output': '[["aadee"], ["aaeec"], ["cad"]]'},
        {'input': '["ccedb", "a", "cbcad", "adaa", "ccbcbe", "bc", "bacecc", "", "e", "acc"]', 'expected_output': '[[""], ["a"], ["acc"], ["adaa"], ["bacecc"], ["bc"], ["cbcad"], ["ccbcbe"], ["ccedb"], ["e"]]'},
        {'input': '["ecdcb", "bad", "ad", "eccddb"]', 'expected_output': '[["ad"], ["bad"], ["eccddb"], ["ecdcb"]]'},
        {'input': '["aaddad", "ecdcb", "edb", "ccbeed", "abeed", "acddaa", "aaeaebde", "a", "a", "eac", "dddac"]', 'expected_output': '[["a", "a"], ["aaddad"], ["aaeaebde"], ["abeed"], ["acddaa"], ["ccbeed"], ["dddac"], ["eac"], ["ecdcb"], ["edb"]]'},
        {'input': '["bced"]', 'expected_output': '[["bced"]]'},
        {'input': '["cebecba", "e", "a"]', 'expected_output': '[["a"], ["cebecba"], ["e"]]'},
        {'input': '["cccc", "aa", "", "dec", "ea", "a", "ab", "deacb", "db", "c", "edcdbabc", "b", "ccbaba"]', 'expected_output': '[[""], ["a"], ["aa"], ["ab"], ["b"], ["c"], ["ccbaba"], ["cccc"], ["db"], ["deacb"], ["dec"], ["ea"], ["edcdbabc"]]'},
        {'input': '["", "be", "baddac", "acda", "eace", "aed", "becdcc"]', 'expected_output': '[[""], ["acda"], ["aed"], ["baddac"], ["be"], ["becdcc"], ["eace"]]'},
        {'input': '["e", "ceeaadc", "eacaacc", "d", "", "be", "ba", ""]', 'expected_output': '[["", ""], ["ba"], ["be"], ["ceeaadc"], ["d"], ["e"], ["eacaacc"]]'},
        {'input': '["baaecad", "ccec", "bdeeb", "adeeec", "ebebbdc", "ad", "bdb"]', 'expected_output': '[["ad"], ["adeeec"], ["baaecad"], ["bdb"], ["bdeeb"], ["ccec"], ["ebebbdc"]]'},
        {'input': '["aac", "e", "eadeeae", "adadb", "d", "dadabbed", "bcccdbc", "edabcdeb", "d", "ebace"]', 'expected_output': '[["aac"], ["adadb"], ["bcccdbc"], ["d", "d"], ["dadabbed"], ["e"], ["eadeeae"], ["ebace"], ["edabcdeb"]]'},
        {'input': '["eea", "caedcbca", "abca", "dd", "", "eecdd", "edde", "ddadbe", "d", "aacbe", "c", "c"]', 'expected_output': '[[""], ["aacbe"], ["abca"], ["c", "c"], ["caedcbca"], ["d"], ["dd"], ["ddadbe"], ["edde"], ["eea"], ["eecdd"]]'},
        {'input': '["aebecdb", "bbaa", "e", "deb", "dddcb", "dbabebbb", "ddcc", "bbd", "", "edba", "c", "adbcbdca", "bebedaab", ""]', 'expected_output': '[["", ""], ["adbcbdca"], ["aebecdb"], ["bbaa"], ["bbd"], ["bebedaab"], ["c"], ["dbabebbb"], ["ddcc"], ["dddcb"], ["deb"], ["e"], ["edba"]]'},
        {'input': '["", "aed", "cab", "cbe", "bcdcdeec", "caa", "eeccb"]', 'expected_output': '[[""], ["aed"], ["bcdcdeec"], ["caa"], ["cab"], ["cbe"], ["eeccb"]]'},
        {'input': '["bbd", "", "adcbda", "", "bd", "", "debeaea", "", "aed", "cadaaec"]', 'expected_output': '[["", "", "", ""], ["adcbda"], ["aed"], ["bbd"], ["bd"], ["cadaaec"], ["debeaea"]]'},
        {'input': '["", "acdcaccd", "dc", "bce", "cdedcd", "cbab", "e", "eadaeab", "dc", "beacadee", "e", "ebadedd", "ececac"]', 'expected_output': '[[""], ["acdcaccd"], ["bce"], ["beacadee"], ["cbab"], ["cdedcd"], ["dc", "dc"], ["e", "e"], ["eadaeab"], ["ebadedd"], ["ececac"]]'},
        {'input': '["dededeb", "c"]', 'expected_output': '[["c"], ["dededeb"]]'},
        {'input': '["bbc", "", "c"]', 'expected_output': '[[""], ["bbc"], ["c"]]'},
        {'input': '["dcbbecd", "eeebdb", "bdea", "dedbe", "ecd"]', 'expected_output': '[["bdea"], ["dcbbecd"], ["dedbe"], ["ecd"], ["eeebdb"]]'},
        {'input': '["bbceacb", "eadb", "aecaebda", "baceaa", "aaaadab", "ddecdece", "", "aebcbc", "aeae", "daeba", "d", "d", "dbceeab"]', 'expected_output': '[[""], ["aaaadab"], ["aeae"], ["aebcbc"], ["aecaebda"], ["baceaa"], ["bbceacb"], ["d", "d"], ["daeba"], ["dbceeab"], ["ddecdece"], ["eadb"]]'},
        {'input': '["addbdbe", ""]', 'expected_output': '[[""], ["addbdbe"]]'},
        {'input': '["bdedce", "", "ccdcccca", "d", "bace"]', 'expected_output': '[[""], ["bace"], ["bdedce"], ["ccdcccca"], ["d"]]'},
        {'input': '["ecebad", "ac", "dbeb", "aaceaec", "cbbae", "ccacb", "eaceca", "ed", "ecddbcdc"]', 'expected_output': '[["aaceaec"], ["ac"], ["cbbae"], ["ccacb"], ["dbeb"], ["eaceca"], ["ecddbcdc"], ["ecebad"], ["ed"]]'},
        {'input': '["dae", "acdcd", "bed", "dabba", "edd", "cd"]', 'expected_output': '[["acdcd"], ["bed"], ["cd"], ["dabba"], ["dae"], ["edd"]]'},
        {'input': '["bacdba", "bce"]', 'expected_output': '[["bacdba"], ["bce"]]'},
        {'input': '["becba", "c", "eedcaeb", "caeebd", "abcdcebd", "da", "abbbad", "ba", "ddeaade", "daedd", "", "acb"]', 'expected_output': '[[""], ["abbbad"], ["abcdcebd"], ["acb"], ["ba"], ["becba"], ["c"], ["caeebd"], ["da"], ["daedd"], ["ddeaade"], ["eedcaeb"]]'},
        {'input': '["ddedaab", "a", "bac", "ccdaeea", "bd", "", "dab", "ba", "aed", "e", "dab"]', 'expected_output': '[[""], ["a"], ["aed"], ["ba"], ["bac"], ["bd"], ["ccdaeea"], ["dab", "dab"], ["ddedaab"], ["e"]]'},
        {'input': '["d"]', 'expected_output': '[["d"]]'},
        {'input': '["c", "", "", "", "aebdce", "abaa", "ccc", "bd", "aabeecad", "debda", "cdccdbec"]', 'expected_output': '[["", "", ""], ["aabeecad"], ["abaa"], ["aebdce"], ["bd"], ["c"], ["ccc"], ["cdccdbec"], ["debda"]]'},
        {'input': '["ddedbc", "cabdaa", "cb", "edadc", "ed", "", "bbea", "aeecedcc", "bdacacca", "accb", "ddeedbab", "cddbbbcc", "dcdedb"]', 'expected_output': '[[""], ["accb"], ["aeecedcc"], ["bbea"], ["bdacacca"], ["cabdaa"], ["cb"], ["cddbbbcc"], ["dcdedb", "ddedbc"], ["ddeedbab"], ["ed"], ["edadc"]]'},
        {'input': '["cedbeead", "aeac", "db", "eddcae", "dae", "c", ""]', 'expected_output': '[[""], ["aeac"], ["c"], ["cedbeead"], ["dae"], ["db"], ["eddcae"]]'},
        {'input': '["c", "", "aacaa", "", "babcbe"]', 'expected_output': '[["", ""], ["aacaa"], ["babcbe"], ["c"]]'},
        {'input': '["beab", "beee", "", "bbdcd", "eddbbe", "aa", "badeead", "bcaa"]', 'expected_output': '[[""], ["aa"], ["badeead"], ["bbdcd"], ["bcaa"], ["beab"], ["beee"], ["eddbbe"]]'},
        {'input': '["bddde", "cdbaeda", "bbeecbd", "acbee", "bacbbea", "eaedaebc", "", "ac", "eacb", "b"]', 'expected_output': '[[""], ["ac"], ["acbee"], ["b"], ["bacbbea"], ["bbeecbd"], ["bddde"], ["cdbaeda"], ["eacb"], ["eaedaebc"]]'},
        {'input': '["abe", "dcceaad", "ac", "", "adc", "eee", "dbeaeb", "abacea", "eebabbc", "eb", "daabccab", "cba"]', 'expected_output': '[[""], ["abacea"], ["abe"], ["ac"], ["adc"], ["cba"], ["daabccab"], ["dbeaeb"], ["dcceaad"], ["eb"], ["eebabbc"], ["eee"]]'},
        {'input': '["bbde", "cde", "edced", "cdccdbbd", "cdebbbd", "eadeeaa", "", "edabbc", "dcc", "abbdd", "cbaccb", "bceca", "bdcdab", "accdcae"]', 'expected_output': '[[""], ["abbdd"], ["accdcae"], ["bbde"], ["bceca"], ["bdcdab"], ["cbaccb"], ["cdccdbbd"], ["cde"], ["cdebbbd"], ["dcc"], ["eadeeaa"], ["edabbc"], ["edced"]]'},
        {'input': '["daadeccc", "cc", "edca", "", "beddbade", "cb", "dae", "cae", "aadc"]', 'expected_output': '[[""], ["aadc"], ["beddbade"], ["cae"], ["cb"], ["cc"], ["daadeccc"], ["dae"], ["edca"]]'},
        {'input': '["e", "adcee", "bacdc", "", "aabac", "eaaadbdb", "abcbe", "aaa", "aadeaabd", "ccbd"]', 'expected_output': '[[""], ["aaa"], ["aabac"], ["aadeaabd"], ["abcbe"], ["adcee"], ["bacdc"], ["ccbd"], ["e"], ["eaaadbdb"]]'},
        {'input': '["ecec"]', 'expected_output': '[["ecec"]]'},
        {'input': '["", "cad", "acdee", "dda", "a", "", "ecabec", "da"]', 'expected_output': '[["", ""], ["a"], ["acdee"], ["cad"], ["da"], ["dda"], ["ecabec"]]'},
        {'input': '["debad", "abbcacd", "abd", "", "ed", "b", "adca", "", "dcb", "", "d", "c", ""]', 'expected_output': '[["", "", "", ""], ["abbcacd"], ["abd"], ["adca"], ["b"], ["c"], ["d"], ["dcb"], ["debad"], ["ed"]]'},
        {'input': '["ac", "d", "baebaecb", "deaebee", "deeee", "a", "ebbabbee", "ee", "adc", "", "", "aaad", ""]', 'expected_output': '[["", "", ""], ["a"], ["aaad"], ["ac"], ["adc"], ["baebaecb"], ["d"], ["deaebee"], ["deeee"], ["ebbabbee"], ["ee"]]'},
        {'input': '["a", "cdeed"]', 'expected_output': '[["a"], ["cdeed"]]'},
        {'input': '["cbcd", "ad", "dabebbdc", "accbaa", "beeeacb", "b"]', 'expected_output': '[["accbaa"], ["ad"], ["b"], ["beeeacb"], ["cbcd"], ["dabebbdc"]]'},
        {'input': '["c", "", "adeed", "bae", "dde"]', 'expected_output': '[[""], ["adeed"], ["bae"], ["c"], ["dde"]]'},
        {'input': '["dee", "bc", "dacbdbd", "bbdceeda", "acb", "cbbaabc"]', 'expected_output': '[["acb"], ["bbdceeda"], ["bc"], ["cbbaabc"], ["dacbdbd"], ["dee"]]'},
        {'input': '["edba", "cea", "eced", "", "b", "adcbaad"]', 'expected_output': '[[""], ["adcbaad"], ["b"], ["cea"], ["eced"], ["edba"]]'},
        {'input': '["cdcce", "bc", "ddaca", "abecaa", "cece", "ddaeed"]', 'expected_output': '[["abecaa"], ["bc"], ["cdcce"], ["cece"], ["ddaca"], ["ddaeed"]]'},
        {'input': '["edcdceb", "decdba", "eacedcbe", "d", "b", "bb", "d", "cbdd", "a"]', 'expected_output': '[["a"], ["b"], ["bb"], ["cbdd"], ["d", "d"], ["decdba"], ["eacedcbe"], ["edcdceb"]]'},
        {'input': '["bae", "a", "aaae", "ceeacdbe", "acbedc", "cd", "ccce", "cb", "cdb", "cbcaa", "", "eab", "d", "eaddde"]', 'expected_output': '[[""], ["a"], ["aaae"], ["acbedc"], ["bae", "eab"], ["cb"], ["cbcaa"], ["ccce"], ["cd"], ["cdb"], ["ceeacdbe"], ["d"], ["eaddde"]]'},
        {'input': '["edbcae", "acdebacc", "abdcc", "a"]', 'expected_output': '[["a"], ["abdcc"], ["acdebacc"], ["edbcae"]]'},
        {'input': '["cbac", "bddbc", "acea", "ebc", "ccecc", "addaabae", "cde", "eccdcde", "c", "adec", "abdac", "db"]', 'expected_output': '[["abdac"], ["acea"], ["addaabae"], ["adec"], ["bddbc"], ["c"], ["cbac"], ["ccecc"], ["cde"], ["db"], ["ebc"], ["eccdcde"]]'},
        {'input': '["db", "eccaecd", "e", "cbeeace", "a", "c", "", "a", "ac", "acd", "aebeaae", "ceeebdde"]', 'expected_output': '[[""], ["a", "a"], ["ac"], ["acd"], ["aebeaae"], ["c"], ["cbeeace"], ["ceeebdde"], ["db"], ["e"], ["eccaecd"]]'},
        {'input': '["bbcbdaa", "d", "a", "e", "deddeba", "e", "ebbadbb", "daeeda", "bdcacdb", "cd", "be", "dee", "aacecb"]', 'expected_output': '[["a"], ["aacecb"], ["bbcbdaa"], ["bdcacdb"], ["be"], ["cd"], ["d"], ["daeeda"], ["deddeba"], ["dee"], ["e", "e"], ["ebbadbb"]]'},
        {'input': '["cbbea", "aeeceea", "abb", "c", "adbac", "abdc"]', 'expected_output': '[["abb"], ["abdc"], ["adbac"], ["aeeceea"], ["c"], ["cbbea"]]'},
        {'input': '["a"]', 'expected_output': '[["a"]]'},
        {'input': '["", "acdaa", "eeec", "", "cd", "", "bdbd", "bd", "ecdbcbcd", "bcdcd", "ab", "bac", "acece"]', 'expected_output': '[["", "", ""], ["ab"], ["acdaa"], ["acece"], ["bac"], ["bcdcd"], ["bd"], ["bdbd"], ["cd"], ["ecdbcbcd"], ["eeec"]]'},
        {'input': '["ae", "abaaab", "d", "abcdeeab", "d", "ceb", "aadecb", "eaad"]', 'expected_output': '[["aadecb"], ["abaaab"], ["abcdeeab"], ["ae"], ["ceb"], ["d", "d"], ["eaad"]]'},
        {'input': '["aebcace", "cbdd", "", "", "eebceb", "eb", "eabedc", "a", "ccdbda"]', 'expected_output': '[["", ""], ["a"], ["aebcace"], ["cbdd"], ["ccdbda"], ["eabedc"], ["eb"], ["eebceb"]]'},
        {'input': '["cda", "", "adabaeec", "deb", "ae", "c", "cdcc", "adeedd", "abbcaebe"]', 'expected_output': '[[""], ["abbcaebe"], ["adabaeec"], ["adeedd"], ["ae"], ["c"], ["cda"], ["cdcc"], ["deb"]]'},
        {'input': '["baaadbd", "eeed", "cd", "ceabbadd", "cdca", "c", "dacdbd", "", "bee", "dbbaed"]', 'expected_output': '[[""], ["baaadbd"], ["bee"], ["c"], ["cd"], ["cdca"], ["ceabbadd"], ["dacdbd"], ["dbbaed"], ["eeed"]]'},
        {'input': '[""]', 'expected_output': '[[""]]'},
        {'input': '["acbb", "edad", "eddb"]', 'expected_output': '[["acbb"], ["edad"], ["eddb"]]'},
        {'input': '["a", "dbeadede", "eb"]', 'expected_output': '[["a"], ["dbeadede"], ["eb"]]'},
        {'input': '["cabd", "ccdcb", "ddeedb", "abedce", "", "eca", "bdcbbbad", "ca", "acedb", "dbe"]', 'expected_output': '[[""], ["abedce"], ["acedb"], ["bdcbbbad"], ["ca"], ["cabd"], ["ccdcb"], ["dbe"], ["ddeedb"], ["eca"]]'},
        {'input': '["ecad", "cc", "cabdb", "", "cbceaeed", "ecaceaec", "ebbade", "eccb", "cedab", "ac", "ebdabdba", "da", "ee"]', 'expected_output': '[[""], ["ac"], ["cabdb"], ["cbceaeed"], ["cc"], ["cedab"], ["da"], ["ebbade"], ["ebdabdba"], ["ecaceaec"], ["ecad"], ["eccb"], ["ee"]]'},
        {'input': '["a", "c", "cabe", "ceaca", "aa", "ced"]', 'expected_output': '[["a"], ["aa"], ["c"], ["cabe"], ["ceaca"], ["ced"]]'},
        {'input': '["dbbeaadb", "b", "ddcbae", "ec", "ac", "abc", "bbcbadc", "bca", "c"]', 'expected_output': '[["abc", "bca"], ["ac"], ["b"], ["bbcbadc"], ["c"], ["dbbeaadb"], ["ddcbae"], ["ec"]]'},
        {'input': '["ddbebddd", "", "ee", "cbecb", "ddaec", "aeb"]', 'expected_output': '[[""], ["aeb"], ["cbecb"], ["ddaec"], ["ddbebddd"], ["ee"]]'},
        {'input': '["bdcc", "badacc", "aeeecccd", "", "dadadde"]', 'expected_output': '[[""], ["aeeecccd"], ["badacc"], ["bdcc"], ["dadadde"]]'},
        {'input': '["cabcddd", "d", "bada", "dbdcd", "dadcccee", "dc", "dba", "cbb", "d", "e"]', 'expected_output': '[["bada"], ["cabcddd"], ["cbb"], ["d", "d"], ["dadcccee"], ["dba"], ["dbdcd"], ["dc"], ["e"]]'},
        {'input': '["eaadda", "", "edd", "dccb", "dbb", "d", "cd", "accb", "", "ebbc", "bbeddecc", "aee"]', 'expected_output': '[["", ""], ["accb"], ["aee"], ["bbeddecc"], ["cd"], ["d"], ["dbb"], ["dccb"], ["eaadda"], ["ebbc"], ["edd"]]'},
        {'input': '["cbbabcbb", "ebbaccea", "bcdcdbbc", "aec", "dde"]', 'expected_output': '[["aec"], ["bcdcdbbc"], ["cbbabcbb"], ["dde"], ["ebbaccea"]]'},
        {'input': '["bdecda", "ceddcb", "a", "ddebd", "eac", "", "bbacd", "caccea", "dbbccaac", "bed", "eae"]', 'expected_output': '[[""], ["a"], ["bbacd"], ["bdecda"], ["bed"], ["caccea"], ["ceddcb"], ["dbbccaac"], ["ddebd"], ["eac"], ["eae"]]'},
        {'input': '["cdea", "", "d", "dbeeb", "bcbaaab", "cdda"]', 'expected_output': '[[""], ["bcbaaab"], ["cdda"], ["cdea"], ["d"], ["dbeeb"]]'},
        {'input': '["ecc", "bab", "ddceabea", "eaecec", "cd", "dbadec", "bdcdaedc"]', 'expected_output': '[["bab"], ["bdcdaedc"], ["cd"], ["dbadec"], ["ddceabea"], ["eaecec"], ["ecc"]]'},
        {'input': '["bdddcdec", "bdbdcd", "cdcebbc", "b", "c", "dcbcbc", "eaeac", "eabdacb", "ebbebde", "da", "", "cecddcb"]', 'expected_output': '[[""], ["b"], ["bdbdcd"], ["bdddcdec"], ["c"], ["cdcebbc"], ["cecddcb"], ["da"], ["dcbcbc"], ["eabdacb"], ["eaeac"], ["ebbebde"]]'},
        {'input': '["dce", "de", "ab", "bedbcceb", "edaee", "abd", "dbb", "caebc", "dc", "d", "ae", "bbceaba"]', 'expected_output': '[["ab"], ["abd"], ["ae"], ["bbceaba"], ["bedbcceb"], ["caebc"], ["d"], ["dbb"], ["dc"], ["dce"], ["de"], ["edaee"]]'},
        {'input': '["caca", "bdcee", "bacdcddc", "", "ee", "", "ecc"]', 'expected_output': '[["", ""], ["bacdcddc"], ["bdcee"], ["caca"], ["ecc"], ["ee"]]'},
        {'input': '["ac", "bccecbea", "acceac", "dbbc", "", "ceccedd", "ad", "edeec", "c", "b", "bb", "becbabdb"]', 'expected_output': '[[""], ["ac"], ["acceac"], ["ad"], ["b"], ["bb"], ["bccecbea"], ["becbabdb"], ["c"], ["ceccedd"], ["dbbc"], ["edeec"]]'},
        {'input': '["", "eaccec", "dee", "cdabee", "ac", "", "caaaaee", "be"]', 'expected_output': '[["", ""], ["ac"], ["be"], ["caaaaee"], ["cdabee"], ["dee"], ["eaccec"]]'},
        {'input': '["aaebde", "ad", "c", "da", "e", "adbdca", "adde", "daabbc", "eecb", "bcaee"]', 'expected_output': '[["aaebde"], ["ad", "da"], ["adbdca"], ["adde"], ["bcaee"], ["c"], ["daabbc"], ["e"], ["eecb"]]'},
        {'input': '["acdcadc"]', 'expected_output': '[["acdcadc"]]'},
        {'input': '["bbaae", "dabddeba", "dcdbeaae", "dd", "", "dddadcda", "adddbca", "", "e", "ee", "ca", "bdcbbc"]', 'expected_output': '[["", ""], ["adddbca"], ["bbaae"], ["bdcbbc"], ["ca"], ["dabddeba"], ["dcdbeaae"], ["dd"], ["dddadcda"], ["e"], ["ee"]]'},
        {'input': '["eeaca", "cdbc", "", "aebeceb", "dabe", "", "", "ba"]', 'expected_output': '[["", "", ""], ["aebeceb"], ["ba"], ["cdbc"], ["dabe"], ["eeaca"]]'},
        {'input': '["ada", "acaa", "bacbbccd", "cbcce", "b", "", "cbe", "acd", "abdadeb", "bbeeabad"]', 'expected_output': '[[""], ["abdadeb"], ["acaa"], ["acd"], ["ada"], ["b"], ["bacbbccd"], ["bbeeabad"], ["cbcce"], ["cbe"]]'},
        {'input': '["e", "caecbcdb", "ecebbddd", "bd", "aeaa", "ddee", "aecb"]', 'expected_output': '[["aeaa"], ["aecb"], ["bd"], ["caecbcdb"], ["ddee"], ["e"], ["ecebbddd"]]'},
        {'input': '["a", "bc"]', 'expected_output': '[["a"], ["bc"]]'},
        {'input': '["bbb", "", "abcdbbe", "", "ae", "dc", "caddece", "bdaecacd", "bdbe"]', 'expected_output': '[["", ""], ["abcdbbe"], ["ae"], ["bbb"], ["bdaecacd"], ["bdbe"], ["caddece"], ["dc"]]'},
        {'input': '["baeddc", "dbbcbdec", ""]', 'expected_output': '[[""], ["baeddc"], ["dbbcbdec"]]'},
        {'input': '["adac", "ecaecc"]', 'expected_output': '[["adac"], ["ecaecc"]]'},
        {'input': '["eebebaa", "ca", "cae", "dccbccb", "dcbbb", "ecaeaa", "ddcccc", "c", "eddd", "", "cdeacad", "bedb", "a"]', 'expected_output': '[[""], ["a"], ["bedb"], ["c"], ["ca"], ["cae"], ["cdeacad"], ["dcbbb"], ["dccbccb"], ["ddcccc"], ["ecaeaa"], ["eddd"], ["eebebaa"]]'},
        {'input': '["acbeec", ""]', 'expected_output': '[[""], ["acbeec"]]'},
        {'input': '["bdadcc", "", "dbcaedaa", "bb", "", "c", "ba", "aa"]', 'expected_output': '[["", ""], ["aa"], ["ba"], ["bb"], ["bdadcc"], ["c"], ["dbcaedaa"]]'},
        {'input': '["bdc", "b", "dcb", "aaada", "", "bce", "ebabdbe"]', 'expected_output': '[[""], ["aaada"], ["b"], ["bce"], ["bdc", "dcb"], ["ebabdbe"]]'},
        {'input': '["bbc", "dadaa", "ee", "ecacd", "bbeeb", "bacb", "", "bebeeb", "de", "caaebe", "addbddb"]', 'expected_output': '[[""], ["addbddb"], ["bacb"], ["bbc"], ["bbeeb"], ["bebeeb"], ["caaebe"], ["dadaa"], ["de"], ["ecacd"], ["ee"]]'},
        {'input': '[""]', 'expected_output': '[[""]]'},
        {'input': '["bdbcb", "ededda", "c", "adaa", "d", "a", "bd"]', 'expected_output': '[["a"], ["adaa"], ["bd"], ["bdbcb"], ["c"], ["d"], ["ededda"]]'},
        {'input': '["dac", "ce", "e", "dbdbecd"]', 'expected_output': '[["ce"], ["dac"], ["dbdbecd"], ["e"]]'},
        {'input': '["aa", "aca", "bdcccce", "", "cb", "accbabd"]', 'expected_output': '[[""], ["aa"], ["aca"], ["accbabd"], ["bdcccce"], ["cb"]]'},
        {'input': '["bceecce", "ecacce", ""]', 'expected_output': '[[""], ["bceecce"], ["ecacce"]]'},
        {'input': '["", "caceaacb", "eadbbe", "a"]', 'expected_output': '[[""], ["a"], ["caceaacb"], ["eadbbe"]]'},
        {'input': '["eabcb", "bdabccaa", "ebcbedd", "dbac", "abb"]', 'expected_output': '[["abb"], ["bdabccaa"], ["dbac"], ["eabcb"], ["ebcbedd"]]'},
        {'input': '["ccbcadda", "eeac", "c", "edeabb", "d", "ddd", "ddcaede", "eeadde", "cdcbdc", "caa", "edacbbd", "dcee", "e", "dcaa"]', 'expected_output': '[["c"], ["caa"], ["ccbcadda"], ["cdcbdc"], ["d"], ["dcaa"], ["dcee"], ["ddcaede"], ["ddd"], ["e"], ["edacbbd"], ["edeabb"], ["eeac"], ["eeadde"]]'},
        {'input': '["dc", "cbe", "ddebec", "a", "bcdcbbea", "eedeb", "bca", "", "edd", "bbc", "bbcdeddd", "eed"]', 'expected_output': '[[""], ["a"], ["bbc"], ["bbcdeddd"], ["bca"], ["bcdcbbea"], ["cbe"], ["dc"], ["ddebec"], ["edd"], ["eed"], ["eedeb"]]'},
        {'input': '["eedeecee", "bbbcdbed", "dacaddc", "eeedcda", "aade", "cdec", "cc", "a", ""]', 'expected_output': '[[""], ["a"], ["aade"], ["bbbcdbed"], ["cc"], ["cdec"], ["dacaddc"], ["eedeecee"], ["eeedcda"]]'},
        {'input': '["dcaebdc", "a", "ea", "dcbdac", "dcdd", "eecaacca", "e"]', 'expected_output': '[["a"], ["dcaebdc"], ["dcbdac"], ["dcdd"], ["e"], ["ea"], ["eecaacca"]]'},
        {'input': '["dbb", "eccc", "dcaed", ""]', 'expected_output': '[[""], ["dbb"], ["dcaed"], ["eccc"]]'},
        {'input': '["cdeab", "ba", "dbadcc"]', 'expected_output': '[["ba"], ["cdeab"], ["dbadcc"]]'},
        {'input': '["ebbe", "bbe", "debaedcd", "bcec", ""]', 'expected_output': '[[""], ["bbe"], ["bcec"], ["debaedcd"], ["ebbe"]]'},
        {'input': '["", "aaebca", "ddeabed", "a", "eb", "", "deabb", "eed", "ebb", "acbade", "bcbcc", "", "ccdeacc", ""]', 'expected_output': '[["", "", "", ""], ["a"], ["aaebca"], ["acbade"], ["bcbcc"], ["ccdeacc"], ["ddeabed"], ["deabb"], ["eb"], ["ebb"], ["eed"]]'},
        {'input': '["a", "adbeadb", "acbebcb", "", "adcc", "bcae", "ad", "dbaebebe", "c", "", "bcaaedc", "ceaaebdd", "c", "bdcdaad"]', 'expected_output': '[["", ""], ["a"], ["acbebcb"], ["ad"], ["adbeadb"], ["adcc"], ["bcaaedc"], ["bcae"], ["bdcdaad"], ["c", "c"], ["ceaaebdd"], ["dbaebebe"]]'},
        {'input': '["adeadbdb", "edadd", "acdc", "cdbadd", "dd", "eabcaeb", "cded"]', 'expected_output': '[["acdc"], ["adeadbdb"], ["cdbadd"], ["cded"], ["dd"], ["eabcaeb"], ["edadd"]]'},
        {'input': '["ecdecbb", "", "ddeeeae", "daa", "eebadac"]', 'expected_output': '[[""], ["daa"], ["ddeeeae"], ["ecdecbb"], ["eebadac"]]'},
        {'input': '["abaacdec", "addb", "", "aeebaaec", "ace"]', 'expected_output': '[[""], ["abaacdec"], ["ace"], ["addb"], ["aeebaaec"]]'},
        {'input': '["adcd", "ecebcada"]', 'expected_output': '[["adcd"], ["ecebcada"]]'},
        {'input': '["cdbdeada", "aeac", "babe", "ecd", "ccbacca"]', 'expected_output': '[["aeac"], ["babe"], ["ccbacca"], ["cdbdeada"], ["ecd"]]'},
        {'input': '["caedbe", "ebecbdc", "edea", "db", "", "ebeccb", "dea", "edacd", "bdcaeda", "ec", "eeeaba", "cba", "", "bcdbeecb"]', 'expected_output': '[["", ""], ["bcdbeecb"], ["bdcaeda"], ["caedbe"], ["cba"], ["db"], ["dea"], ["ebecbdc"], ["ebeccb"], ["ec"], ["edacd"], ["edea"], ["eeeaba"]]'},
        {'input': '["debdbcd", "", "cebeb", "", "de", "acaeecc", "baa", "aa", "ecededc", "cb", "ddbda", "daadeea", "ee"]', 'expected_output': '[["", ""], ["aa"], ["acaeecc"], ["baa"], ["cb"], ["cebeb"], ["daadeea"], ["ddbda"], ["de"], ["debdbcd"], ["ecededc"], ["ee"]]'},
        {'input': '["dbd", "cac", "ad", "ae", "ecdbd", "", "ebcddc", "bea", "cbcda", "bbaeb", "d", "a"]', 'expected_output': '[[""], ["a"], ["ad"], ["ae"], ["bbaeb"], ["bea"], ["cac"], ["cbcda"], ["d"], ["dbd"], ["ebcddc"], ["ecdbd"]]'},
        {'input': '["bbcdbb", "dccb", "eb", "dcbabeea", "bebdd", "c", "", "d", "c", "", "d", "", "aecdcb", "e"]', 'expected_output': '[["", "", ""], ["aecdcb"], ["bbcdbb"], ["bebdd"], ["c", "c"], ["d", "d"], ["dcbabeea"], ["dccb"], ["e"], ["eb"]]'},
        {'input': '["bad", "", "ddbcbadd", "eddd", "de", "eaabded", "bced", "caea", "edbe"]', 'expected_output': '[[""], ["bad"], ["bced"], ["caea"], ["ddbcbadd"], ["de"], ["eaabded"], ["edbe"], ["eddd"]]'},
        {'input': '["bdddd", "bbbddeec", "eebdd", "cadeb", "eccdcbb", "c", "dbcca", "cecbde"]', 'expected_output': '[["bbbddeec"], ["bdddd"], ["c"], ["cadeb"], ["cecbde"], ["dbcca"], ["eccdcbb"], ["eebdd"]]'},
        {'input': '["eceeb", "bdedcd", "bc"]', 'expected_output': '[["bc"], ["bdedcd"], ["eceeb"]]'},
        {'input': '["eededacc", "cdcaac", ""]', 'expected_output': '[[""], ["cdcaac"], ["eededacc"]]'},
        {'input': '["bbdbdbcd"]', 'expected_output': '[["bbdbdbcd"]]'},
        {'input': '["ebcec", "eea"]', 'expected_output': '[["ebcec"], ["eea"]]'},
        {'input': '["bcc", "", "ebbb", "acd", "acaddaac", "ea", "dadebdb"]', 'expected_output': '[[""], ["acaddaac"], ["acd"], ["bcc"], ["dadebdb"], ["ea"], ["ebbb"]]'},
        {'input': '["ab"]', 'expected_output': '[["ab"]]'},
        {'input': '["dbceaacd", "dedcddea", "eb", "dbbdb", "bacdacdd", "d", "dedadbd", ""]', 'expected_output': '[[""], ["bacdacdd"], ["d"], ["dbbdb"], ["dbceaacd"], ["dedadbd"], ["dedcddea"], ["eb"]]'},
        {'input': '["dddae", "d", "eaeebb", "ed", "cd", "cdbedcaa", "bebbacd", "ee"]', 'expected_output': '[["bebbacd"], ["cd"], ["cdbedcaa"], ["d"], ["dddae"], ["eaeebb"], ["ed"], ["ee"]]'},
        {'input': '["babcccbc", "bbabebbe", "eaacdc", "db", "dcaacccb", "", "", "ebebcc", "bcacb", "", "cab"]', 'expected_output': '[["", "", ""], ["babcccbc"], ["bbabebbe"], ["bcacb"], ["cab"], ["db"], ["dcaacccb"], ["eaacdc"], ["ebebcc"]]'},
        {'input': '["ddd"]', 'expected_output': '[["ddd"]]'},
        {'input': '["ee"]', 'expected_output': '[["ee"]]'},
        {'input': '["cdbbdcca", "bdddad"]', 'expected_output': '[["bdddad"], ["cdbbdcca"]]'},
        {'input': '["ddaac", "edaa", "c", "dd"]', 'expected_output': '[["c"], ["dd"], ["ddaac"], ["edaa"]]'},
        {'input': '["", "beba", "cbbebe", "ebdd", "ec", "bdebba"]', 'expected_output': '[[""], ["bdebba"], ["beba"], ["cbbebe"], ["ebdd"], ["ec"]]'},
        {'input': '["a", "c", "adade", "eabb", "", "bbd", "aabab", "e"]', 'expected_output': '[[""], ["a"], ["aabab"], ["adade"], ["bbd"], ["c"], ["e"], ["eabb"]]'},
        {'input': '["", "ebedb", "daad", "daebcce", "dada", "d", "", "abbbaa"]', 'expected_output': '[["", ""], ["abbbaa"], ["d"], ["daad", "dada"], ["daebcce"], ["ebedb"]]'},
        {'input': '["aceaca", "ebabddd", "ebdaccd"]', 'expected_output': '[["aceaca"], ["ebabddd"], ["ebdaccd"]]'},
        {'input': '["", "abc"]', 'expected_output': '[[""], ["abc"]]'},
        {'input': '["bdc"]', 'expected_output': '[["bdc"]]'},
        {'input': '["cccbb", "", "", "beeab", "ddaedc"]', 'expected_output': '[["", ""], ["beeab"], ["cccbb"], ["ddaedc"]]'},
        {'input': '["ed", "eacbb", "aaeaec", "adbadbad", "", "bce", "ba", "eac", "", "b"]', 'expected_output': '[["", ""], ["aaeaec"], ["adbadbad"], ["b"], ["ba"], ["bce"], ["eac"], ["eacbb"], ["ed"]]'},
        {'input': '["badebbdb", "bcecaecb", "aedceb", "acd", "abacdd", "e"]', 'expected_output': '[["abacdd"], ["acd"], ["aedceb"], ["badebbdb"], ["bcecaecb"], ["e"]]'},
        {'input': '["eababec", "dcdaec", "", "bbbdd", "abcebb", "eacacaea", "e", "cae", "ad", "adccbcbd", "abadecdd", "aedcbeee"]', 'expected_output': '[[""], ["abadecdd"], ["abcebb"], ["ad"], ["adccbcbd"], ["aedcbeee"], ["bbbdd"], ["cae"], ["dcdaec"], ["e"], ["eababec"], ["eacacaea"]]'},
        {'input': '["acb", "ad", "bbdda", "ee", "", "e"]', 'expected_output': '[[""], ["acb"], ["ad"], ["bbdda"], ["e"], ["ee"]]'},
        {'input': '["edcde", "bbbdaceb", "bebcee", "", "cabcd", "bbcb"]', 'expected_output': '[[""], ["bbbdaceb"], ["bbcb"], ["bebcee"], ["cabcd"], ["edcde"]]'},
        {'input': '["bbdada", "bddeec", "b", "ded", "ddccbead", "acecddd", "bbdbc", "d", "debc", "dacba", "", "cb", "dbaaeac", "cbcae"]', 'expected_output': '[[""], ["acecddd"], ["b"], ["bbdada"], ["bbdbc"], ["bddeec"], ["cb"], ["cbcae"], ["d"], ["dacba"], ["dbaaeac"], ["ddccbead"], ["debc"], ["ded"]]'},
        {'input': '["ceeedb", "bddb", "bbccedbc", "ceeb", "", "dbca", "abd", "cdab", "bbdd", "edcbceb"]', 'expected_output': '[[""], ["abd"], ["bbccedbc"], ["bbdd", "bddb"], ["cdab", "dbca"], ["ceeb"], ["ceeedb"], ["edcbceb"]]'},
        {'input': '["eebae", "aeeb", "ebaaceae", "c", "eb", "ddeb", "cae", "eba", "bada", "ebbdea"]', 'expected_output': '[["aeeb"], ["bada"], ["c"], ["cae"], ["ddeb"], ["eb"], ["eba"], ["ebaaceae"], ["ebbdea"], ["eebae"]]'},
        {'input': '["cbabc", "bdbedade", "", "dcdbcb", "", "adedae", "daea", "bbebeacb"]', 'expected_output': '[["", ""], ["adedae"], ["bbebeacb"], ["bdbedade"], ["cbabc"], ["daea"], ["dcdbcb"]]'},
        {'input': '["adc", "ebccdaee", "dd", "ab", "deedaaba", "abdd", "acaeb", "caeaece", "addd"]', 'expected_output': '[["ab"], ["abdd"], ["acaeb"], ["adc"], ["addd"], ["caeaece"], ["dd"], ["deedaaba"], ["ebccdaee"]]'},
        {'input': '["ceebde", "aacedbeb", "dd", "beacccae", "ecbe", "dcbbccdc", "", "ce", "daaa"]', 'expected_output': '[[""], ["aacedbeb"], ["beacccae"], ["ce"], ["ceebde"], ["daaa"], ["dcbbccdc"], ["dd"], ["ecbe"]]'},
        {'input': '["deaadac", "dc", "a"]', 'expected_output': '[["a"], ["dc"], ["deaadac"]]'},
        {'input': '["deebeacc", "aca", "", "eacacc", "beeedcb", "cdba", "aaaecbb", "", "dbcbbdba", "ecabcadc", "eba"]', 'expected_output': '[["", ""], ["aaaecbb"], ["aca"], ["beeedcb"], ["cdba"], ["dbcbbdba"], ["deebeacc"], ["eacacc"], ["eba"], ["ecabcadc"]]'},
        {'input': '["cacecb", "bdbe", "dcdadd", "dab", "ddcd", "dcc", "aebcbdb", "dbdddc", "", "eadbbecc", "ebad", "ceeac", "adeed", "cc"]', 'expected_output': '[[""], ["adeed"], ["aebcbdb"], ["bdbe"], ["cacecb"], ["cc"], ["ceeac"], ["dab"], ["dbdddc"], ["dcc"], ["dcdadd"], ["ddcd"], ["eadbbecc"], ["ebad"]]'},
        {'input': '["bcabdaa", "abbec", "d"]', 'expected_output': '[["abbec"], ["bcabdaa"], ["d"]]'},
        {'input': '["b", "ddea", "ebebdeda", "c", "bbade", "cceed", "ecc", "abd", ""]', 'expected_output': '[[""], ["abd"], ["b"], ["bbade"], ["c"], ["cceed"], ["ddea"], ["ebebdeda"], ["ecc"]]'},
        {'input': '["", "baaddb", "ded", "eca"]', 'expected_output': '[[""], ["baaddb"], ["ded"], ["eca"]]'},
        {'input': '["cb", "", "", "e", "caadd", "adeaade", "bbb", "ccdbd", "", "cebcbde"]', 'expected_output': '[["", "", ""], ["adeaade"], ["bbb"], ["caadd"], ["cb"], ["ccdbd"], ["cebcbde"], ["e"]]'},
        {'input': '["", "caabdea", "dddc", "c", "cadd", "bd", "", "cedab", "dedbea", "bd", "aa"]', 'expected_output': '[["", ""], ["aa"], ["bd", "bd"], ["c"], ["caabdea"], ["cadd"], ["cedab"], ["dddc"], ["dedbea"]]'},
        {'input': '["dc"]', 'expected_output': '[["dc"]]'},
        {'input': '["abacb", "eb", "", "e", "bceab", "abbd", "bbacee"]', 'expected_output': '[[""], ["abacb"], ["abbd"], ["bbacee"], ["bceab"], ["e"], ["eb"]]'},
        {'input': '["ece", "deded", "a", "a", "bddccdad", "cab", "bcbaebbe", "e", "deb", "ac", "bcbce", "edaccc"]', 'expected_output': '[["a", "a"], ["ac"], ["bcbaebbe"], ["bcbce"], ["bddccdad"], ["cab"], ["deb"], ["deded"], ["e"], ["ece"], ["edaccc"]]'},
        {'input': '["a", "caadcdea"]', 'expected_output': '[["a"], ["caadcdea"]]'},
        {'input': '["deeae"]', 'expected_output': '[["deeae"]]'},
        {'input': '["", "edabebae", "ccdb", "", "a", "beddacc", "accd"]', 'expected_output': '[["", ""], ["a"], ["accd"], ["beddacc"], ["ccdb"], ["edabebae"]]'},
        {'input': '["bccaeec", "bdb"]', 'expected_output': '[["bccaeec"], ["bdb"]]'},
        {'input': '["ceca", "edaae", "b", "edaadabb", "", "ecbbdb", "eeea", "abba"]', 'expected_output': '[[""], ["abba"], ["b"], ["ceca"], ["ecbbdb"], ["edaadabb"], ["edaae"], ["eeea"]]'},
        {'input': '["", "", "deabe", "ed", "bceab"]', 'expected_output': '[["", ""], ["bceab"], ["deabe"], ["ed"]]'},
        {'input': '["badeaeb", "", "caeceaab", "bbaa", "edac", "bbdbdebb", "eadebcd", "baea", "dbbbac"]', 'expected_output': '[[""], ["badeaeb"], ["baea"], ["bbaa"], ["bbdbdebb"], ["caeceaab"], ["dbbbac"], ["eadebcd"], ["edac"]]'},
        {'input': '["d", "abdedbec", "b", "eeeec", "eb", "ecbcceba", "", "", "e", ""]', 'expected_output': '[["", "", ""], ["abdedbec"], ["b"], ["d"], ["e"], ["eb"], ["ecbcceba"], ["eeeec"]]'},
        {'input': '["", "dccecca", "da", "dcebeca", "bccadd", "cbb", "bcacaaab", "ceeabbbc"]', 'expected_output': '[[""], ["bcacaaab"], ["bccadd"], ["cbb"], ["ceeabbbc"], ["da"], ["dccecca"], ["dcebeca"]]'},
        {'input': '["aeaebce"]', 'expected_output': '[["aeaebce"]]'},
        {'input': '["abda", "adccb"]', 'expected_output': '[["abda"], ["adccb"]]'},
        {'input': '["", "bbadec", "ebcd", "bbccbd", "badec", "", "acaabede", "caaca", "accaa", "dcbdabc"]', 'expected_output': '[["", ""], ["acaabede"], ["accaa", "caaca"], ["badec"], ["bbadec"], ["bbccbd"], ["dcbdabc"], ["ebcd"]]'},
        {'input': '["dbcddbe", "cdbeda", "de", "ec", "eccbcbb"]', 'expected_output': '[["cdbeda"], ["dbcddbe"], ["de"], ["ec"], ["eccbcbb"]]'},
        {'input': '["abcd", "", "ddecace", "ca", "bdd", "ddba", "b", "bbc"]', 'expected_output': '[[""], ["abcd"], ["b"], ["bbc"], ["bdd"], ["ca"], ["ddba"], ["ddecace"]]'},
        {'input': '["", "cacbdac", "dad", "a", "beebb", "cecdcddb", "dd", "de", "", "b", "d", "ecee", "e", "e"]', 'expected_output': '[["", ""], ["a"], ["b"], ["beebb"], ["cacbdac"], ["cecdcddb"], ["d"], ["dad"], ["dd"], ["de"], ["e", "e"], ["ecee"]]'},
        {'input': '["decad", "bcebea", "c", "bace", "", "ec", "dbeea", "ebcacaab", "ccddccb"]', 'expected_output': '[[""], ["bace"], ["bcebea"], ["c"], ["ccddccb"], ["dbeea"], ["decad"], ["ebcacaab"], ["ec"]]'},
        {'input': '["ceadcea", "e", "ce", "eabacaed", "dceaac", "adcdbec", "ecabbded", "cceaec", "edddbeba", "cdccdc", "", "debaca", "eb", ""]', 'expected_output': '[["", ""], ["adcdbec"], ["cceaec"], ["cdccdc"], ["ce"], ["ceadcea"], ["dceaac"], ["debaca"], ["e"], ["eabacaed"], ["eb"], ["ecabbded"], ["edddbeba"]]'},
        {'input': '["dcecaea", "cec", "ddcdee", "acecedad", "ddecb", "bd", "eabeca", "bccedabe"]', 'expected_output': '[["acecedad"], ["bccedabe"], ["bd"], ["cec"], ["dcecaea"], ["ddcdee"], ["ddecb"], ["eabeca"]]'},
        {'input': '["e"]', 'expected_output': '[["e"]]'},
        {'input': '["dbbdc", "bc", "abce", "edeaac", "b", "acbea", ""]', 'expected_output': '[[""], ["abce"], ["acbea"], ["b"], ["bc"], ["dbbdc"], ["edeaac"]]'},
        {'input': '["abebbbdc", "", "abcec", "eccdddc"]', 'expected_output': '[[""], ["abcec"], ["abebbbdc"], ["eccdddc"]]'},
        {'input': '["cae", "cbb", "bd", "bdecdbdc", "", "", "ab", "bebdeec", "bbbbb", "dbececce", "edccbcee", "cabdeaaa"]', 'expected_output': '[["", ""], ["ab"], ["bbbbb"], ["bd"], ["bdecdbdc"], ["bebdeec"], ["cabdeaaa"], ["cae"], ["cbb"], ["dbececce", "edccbcee"]]'},
        {'input': '["d", "dedaaaca", "becdc", "dbdbada"]', 'expected_output': '[["becdc"], ["d"], ["dbdbada"], ["dedaaaca"]]'},
        {'input': '["", "aacecdee", "", "ebadbcca"]', 'expected_output': '[["", ""], ["aacecdee"], ["ebadbcca"]]'},
        {'input': '["aad", "aeca", "bce", "be", "", "", "cbed", "ec", "eeaaad", "eddcd", "", "babac", "eedcaebc"]', 'expected_output': '[["", "", ""], ["aad"], ["aeca"], ["babac"], ["bce"], ["be"], ["cbed"], ["ec"], ["eddcd"], ["eeaaad"], ["eedcaebc"]]'},
        {'input': '["cececaec", "cccebebb", "", "dbecc", "ddd", "abdbdee", "ed"]', 'expected_output': '[[""], ["abdbdee"], ["cccebebb"], ["cececaec"], ["dbecc"], ["ddd"], ["ed"]]'},
        {'input': '["edd", "cccbddac"]', 'expected_output': '[["cccbddac"], ["edd"]]'},
        {'input': '["ba", "ded", "aba", "ecdccb", "", "eb", "ca", "eaddcbab"]', 'expected_output': '[[""], ["aba"], ["ba"], ["ca"], ["ded"], ["eaddcbab"], ["eb"], ["ecdccb"]]'},
        {'input': '["eaa"]', 'expected_output': '[["eaa"]]'},
        {'input': '["cc", "baaeac", "", "cdbabcaa", "b", "debd"]', 'expected_output': '[[""], ["b"], ["baaeac"], ["cc"], ["cdbabcaa"], ["debd"]]'},
        {'input': '["", "bebedc", "be", "d", ""]', 'expected_output': '[["", ""], ["be"], ["bebedc"], ["d"]]'},
        {'input': '["ccdbda", "abaeebeb", "", ""]', 'expected_output': '[["", ""], ["abaeebeb"], ["ccdbda"]]'},
        {'input': '["dd", "", "", "cbd", "deaa"]', 'expected_output': '[["", ""], ["cbd"], ["dd"], ["deaa"]]'},
        {'input': '["dcebbee", "ebbd"]', 'expected_output': '[["dcebbee"], ["ebbd"]]'},
        {'input': '["aebccbb", "bac", "bcbdcacb", "", "bbbb", "abba", "adb", "ccecdabb"]', 'expected_output': '[[""], ["abba"], ["adb"], ["aebccbb"], ["bac"], ["bbbb"], ["bcbdcacb"], ["ccecdabb"]]'},
        {'input': '["cceed", "dcdd"]', 'expected_output': '[["cceed"], ["dcdd"]]'},
        {'input': '["baaaeb", "", "beccdce", "", "abbcb"]', 'expected_output': '[["", ""], ["abbcb"], ["baaaeb"], ["beccdce"]]'},
        {'input': '["bdbbacc", "bdcbc", "eaadecc", "daadcadb", "c", "dbeacb", "ada", "ce", "b"]', 'expected_output': '[["ada"], ["b"], ["bdbbacc"], ["bdcbc"], ["c"], ["ce"], ["daadcadb"], ["dbeacb"], ["eaadecc"]]'},
        {'input': '["cecccdda", "dcddb", "ed", "edeedad", "cdc", "cdcb", "bb", "bdead", "ea", "aa", "ecbba", "beacac", "ac", ""]', 'expected_output': '[[""], ["aa"], ["ac"], ["bb"], ["bdead"], ["beacac"], ["cdc"], ["cdcb"], ["cecccdda"], ["dcddb"], ["ea"], ["ecbba"], ["ed"], ["edeedad"]]'},
        {'input': '["baebed", "ebcbedb", "cbddcdcc", "daeeae"]', 'expected_output': '[["baebed"], ["cbddcdcc"], ["daeeae"], ["ebcbedb"]]'},
        {'input': '["", "dcabe"]', 'expected_output': '[[""], ["dcabe"]]'},
        {'input': '["bbbd", "dbacbba", "cb", "a", "da"]', 'expected_output': '[["a"], ["bbbd"], ["cb"], ["da"], ["dbacbba"]]'},
        {'input': '["", "aedbdec", "cdad", "dbced"]', 'expected_output': '[[""], ["aedbdec"], ["cdad"], ["dbced"]]'},
        {'input': '["bbda", "ba", "aaecb"]', 'expected_output': '[["aaecb"], ["ba"], ["bbda"]]'},
        {'input': '["b", "ee", "ed", "c", "e"]', 'expected_output': '[["b"], ["c"], ["e"], ["ed"], ["ee"]]'},
        {'input': '["", "a", "bbb", "cdc", "cdbcaad"]', 'expected_output': '[[""], ["a"], ["bbb"], ["cdbcaad"], ["cdc"]]'},
        {'input': '["ceebc", "b", "ddcbeced", "bc", "", "dedbbad"]', 'expected_output': '[[""], ["b"], ["bc"], ["ceebc"], ["ddcbeced"], ["dedbbad"]]'},
        {'input': '["ee", "bdbaeca", "ecbc", "bac", "cbddbdb", "", "da", "e", "abaee"]', 'expected_output': '[[""], ["abaee"], ["bac"], ["bdbaeca"], ["cbddbdb"], ["da"], ["e"], ["ecbc"], ["ee"]]'},
        {'input': '["", "dcee", "eeed", "dbbc", "cbd", "b", "ec", "cedeea"]', 'expected_output': '[[""], ["b"], ["cbd"], ["cedeea"], ["dbbc"], ["dcee"], ["ec"], ["eeed"]]'},
        {'input': '["aa", "dbbabee", "bcd", "", "cdbb", "deddc", "debea", "dcd"]', 'expected_output': '[[""], ["aa"], ["bcd"], ["cdbb"], ["dbbabee"], ["dcd"], ["debea"], ["deddc"]]'},
        {'input': '["dbaeea", "ebeecd", "d", "", "ee", "eeeeabae", "dc", "eceddb", "ad"]', 'expected_output': '[[""], ["ad"], ["d"], ["dbaeea"], ["dc"], ["ebeecd"], ["eceddb"], ["ee"], ["eeeeabae"]]'},
        {'input': '["bb", "eddb", "", "a", "ccdc", "ac", "bca", "", "bbdaceba", "adb", "c", "cedea", "cada"]', 'expected_output': '[["", ""], ["a"], ["ac"], ["adb"], ["bb"], ["bbdaceba"], ["bca"], ["c"], ["cada"], ["ccdc"], ["cedea"], ["eddb"]]'},
        {'input': '["aa", "aedadbdc", "ac", "adb", "cbccdea", "d"]', 'expected_output': '[["aa"], ["ac"], ["adb"], ["aedadbdc"], ["cbccdea"], ["d"]]'},
        {'input': '["bccdcc", "ce", "ad", "dbbcbbd", "", "ceacabc", "ae"]', 'expected_output': '[[""], ["ad"], ["ae"], ["bccdcc"], ["ce"], ["ceacabc"], ["dbbcbbd"]]'},
        {'input': '["baeebcbb", "ecdd", "bbcedb", "baebcca", "aacaade", "bc", "adecacbe", "ceb", "", "dcc", "eacedc", "abcb", "d", "cccbacbb"]', 'expected_output': '[[""], ["aacaade"], ["abcb"], ["adecacbe"], ["baebcca"], ["baeebcbb"], ["bbcedb"], ["bc"], ["cccbacbb"], ["ceb"], ["d"], ["dcc"], ["eacedc"], ["ecdd"]]'},
        {'input': '["dbccdd", "c", "edcadd", "", "eabbdede", "b", "eabdbaed", "a", "ebdbcb", "caebce"]', 'expected_output': '[[""], ["a"], ["b"], ["c"], ["caebce"], ["dbccdd"], ["eabbdede"], ["eabdbaed"], ["ebdbcb"], ["edcadd"]]'},
        {'input': '["baac", "cd", "a", "c", "cebeca", "cbe", "dbbdeba"]', 'expected_output': '[["a"], ["baac"], ["c"], ["cbe"], ["cd"], ["cebeca"], ["dbbdeba"]]'},
        {'input': '["baadedac", "cddebb", "", "be", "dcbeebab", "cbad", "cdceba", "bcca", "ddbdcad", "edcada"]', 'expected_output': '[[""], ["baadedac"], ["bcca"], ["be"], ["cbad"], ["cdceba"], ["cddebb"], ["dcbeebab"], ["ddbdcad"], ["edcada"]]'},
        {'input': '["adacb", "eaeecb", "a", "dc", "", "abbce", "decbae", "cd"]', 'expected_output': '[[""], ["a"], ["abbce"], ["adacb"], ["cd", "dc"], ["decbae"], ["eaeecb"]]'},
        {'input': '["ad"]', 'expected_output': '[["ad"]]'},
        {'input': '["ed", "a"]', 'expected_output': '[["a"], ["ed"]]'},
        {'input': '["dcedbeee", "e"]', 'expected_output': '[["dcedbeee"], ["e"]]'},
        {'input': '["cdadbcda", "edcd", "cebed", "", "abe", "e", "cdbeb", "c", "cccdebb", "dbcd", "ebdcaaa", "abcaeeba", "bcba", "abdebed"]', 'expected_output': '[[""], ["abcaeeba"], ["abdebed"], ["abe"], ["bcba"], ["c"], ["cccdebb"], ["cdadbcda"], ["cdbeb"], ["cebed"], ["dbcd"], ["e"], ["ebdcaaa"], ["edcd"]]'},
        {'input': '["eeabacb"]', 'expected_output': '[["eeabacb"]]'},
        {'input': '["baad", "cacbdcd"]', 'expected_output': '[["baad"], ["cacbdcd"]]'},
        {'input': '["be", "dc", "dcda", "abeba", "abdeec", "aea", "c", "cebbabab", "ecace", "bcbcc", "deadde", "bdec", "aed"]', 'expected_output': '[["abdeec"], ["abeba"], ["aea"], ["aed"], ["bcbcc"], ["bdec"], ["be"], ["c"], ["cebbabab"], ["dc"], ["dcda"], ["deadde"], ["ecace"]]'},
        {'input': '["da", "", "eda", "cabadad", "", "cdec", "aab", "caabda", "ebeb", "ab", "babace", "", "b", "bdcabbe"]', 'expected_output': '[["", "", ""], ["aab"], ["ab"], ["b"], ["babace"], ["bdcabbe"], ["caabda"], ["cabadad"], ["cdec"], ["da"], ["ebeb"], ["eda"]]'},
        {'input': '["aebcca", "e", "", "", "daa", "", "bbcdb", "dadadac", "ceeebccc"]', 'expected_output': '[["", "", ""], ["aebcca"], ["bbcdb"], ["ceeebccc"], ["daa"], ["dadadac"], ["e"]]'},
        {'input': '["eab", "eccac", "ca", "cea", "babdbed", "e", "cbcd", "dac"]', 'expected_output': '[["babdbed"], ["ca"], ["cbcd"], ["cea"], ["dac"], ["e"], ["eab"], ["eccac"]]'},
    ]
    for offset, case in enumerate(cases[:count]):
        yield {
            "input": case["input"],
            "expected_output": case["expected_output"],
            "order_index": start_index + offset,
            "is_sample": False,
        }
