"""Auto-migrated bulk hidden test cases."""

def generate_cases(*, count: int, seed: int, start_index: int):
    del seed
    cases = [
        {'input': '"bcababccaacabcc"\n["abcc", "cd", "bdabb", "ab", "c", "a", "b"]', 'expected_output': 'true'},
        {'input': '"eeaabdbccadedd"\n["aed"]', 'expected_output': 'false'},
        {'input': '"ebcec"\n["eaab", "dc", "daeb"]', 'expected_output': 'false'},
        {'input': '"baccdaecbdeca"\n["ed", "caec"]', 'expected_output': 'false'},
        {'input': '"eb"\n["e", "bdbe", "da", "dbd", "baba", "c"]', 'expected_output': 'false'},
        {'input': '"d"\n["ecadb", "aaec", "a", "ecaec", "d"]', 'expected_output': 'true'},
        {'input': '"dbdea"\n["eb"]', 'expected_output': 'false'},
        {'input': '"abdbececcabdbe"\n["abdbe", "da", "cecc"]', 'expected_output': 'true'},
        {'input': '"adcbebbceecbedecaa"\n["cbbc", "eadae", "e", "c", "ce", "d"]', 'expected_output': 'false'},
        {'input': '"ededed"\n["ed"]', 'expected_output': 'true'},
        {'input': '""\n["abed", "ede", "bb", "becd", "c"]', 'expected_output': 'true'},
        {'input': '"adecdeaebeeced"\n["eca", "d", "deed", "dd", "bcbcd", "dcd"]', 'expected_output': 'false'},
        {'input': '"eaeeccdcadeadb"\n["c", "e", "bbc", "cceba", "cabd", "a", "cbec", "acbb"]', 'expected_output': 'false'},
        {'input': '"aaab"\n["c"]', 'expected_output': 'false'},
        {'input': '"b"\n["aac", "edccb", "b", "aa", "acdeb", "a"]', 'expected_output': 'true'},
        {'input': '"a"\n["bce", "a", "cbea", "decb", "eca", "cbe"]', 'expected_output': 'true'},
        {'input': '"ed"\n["daa", "a", "beddb", "ee", "accde", "ccecd"]', 'expected_output': 'false'},
        {'input': '""\n["ddcac"]', 'expected_output': 'true'},
        {'input': '"eddedeab"\n["edea", "edd", "dea", "b", "e"]', 'expected_output': 'true'},
        {'input': '"eecabb"\n["b", "ab", "eec", "bac"]', 'expected_output': 'true'},
        {'input': '"cbad"\n["c", "bad", "ecb", "cbdea", "aadeb"]', 'expected_output': 'true'},
        {'input': '"ec"\n["bbe", "dabbd", "cc", "dbaeb", "cdcbd"]', 'expected_output': 'false'},
        {'input': '"c"\n["d", "aae", "baa", "cd", "dcd"]', 'expected_output': 'false'},
        {'input': '"aacbbdebccccaa"\n["e"]', 'expected_output': 'false'},
        {'input': '"cdaaaecccacadbe"\n["ced", "bbd", "c", "cdcc"]', 'expected_output': 'false'},
        {'input': '"bdecabebaecde"\n["aba", "aabd", "ec", "be", "bd"]', 'expected_output': 'false'},
        {'input': '"becdeb"\n["ddeec", "eb", "bec", "dccde", "dcaeb", "d", "bb", "e"]', 'expected_output': 'true'},
        {'input': '"bdd"\n["bdd"]', 'expected_output': 'true'},
        {'input': '"edbdedbdedbdbeecb"\n["ddd", "edbd", "b", "da", "beecb", "bab", "cacdc"]', 'expected_output': 'true'},
        {'input': '"bcededadaabdbaaabded"\n["be", "eaecb"]', 'expected_output': 'false'},
        {'input': '"decbecccbadecde"\n["e", "b", "eecdc", "dada", "ecd"]', 'expected_output': 'false'},
        {'input': '"cecadcaaeecbc"\n["dbaae", "ddcba", "baaa"]', 'expected_output': 'false'},
        {'input': '"aaaaa"\n["a"]', 'expected_output': 'true'},
        {'input': '"badaecccebba"\n["ccdcd", "c", "dae", "ccceb", "aed", "ceebb", "ba", "a"]', 'expected_output': 'true'},
        {'input': '"bbcbbcbbcbbcbbcbbcbbcbbc"\n["bbc"]', 'expected_output': 'true'},
        {'input': '"ecc"\n["bde", "b", "ebdb", "dcdb", "eeea", "bdaec", "ddad"]', 'expected_output': 'false'},
        {'input': '"deeedaceccacbedeadcb"\n["ea", "a", "b", "abe"]', 'expected_output': 'false'},
        {'input': '"cdceecaaaaaadbeeaeaa"\n["be", "ccd", "eedac", "aacbb", "bc"]', 'expected_output': 'false'},
        {'input': '""\n["d", "b", "dc", "cc", "cad"]', 'expected_output': 'true'},
        {'input': '"adbea"\n["cd", "ddcbc", "aec", "aace"]', 'expected_output': 'false'},
        {'input': '"dea"\n["aabee"]', 'expected_output': 'false'},
        {'input': '"dddeaaacaaaacba"\n["d", "c", "dde", "aaa", "dd", "acba"]', 'expected_output': 'true'},
        {'input': '""\n["dceb", "dae"]', 'expected_output': 'true'},
        {'input': '"bcaeacdbaee"\n["a", "bccc", "aee", "ddae"]', 'expected_output': 'false'},
        {'input': '"eceedccdeceeecece"\n["edccd", "eec", "ece", "bae", "dc"]', 'expected_output': 'true'},
        {'input': '"beceacbcbdbeceabecea"\n["becea", "cbd", "d", "cb", "aaed"]', 'expected_output': 'true'},
        {'input': '"bbccbbedbbed"\n["bbc", "eab", "aeb", "bbed", "c", "bab", "b"]', 'expected_output': 'true'},
        {'input': '"cbacaaccecbacacaedbcaedb"\n["cbaca", "caedb", "acce"]', 'expected_output': 'true'},
        {'input': '"abd"\n["b", "abd"]', 'expected_output': 'true'},
        {'input': '"cdbedddbececedbe"\n["d", "dbccc", "c", "dbe", "ce"]', 'expected_output': 'true'},
        {'input': '""\n["cdba", "ccabe", "aeb", "bee", "bbe", "bbaa"]', 'expected_output': 'true'},
        {'input': '"adbaaabaaecdcbed"\n["cbed", "bcbba", "cbc", "a", "abaae", "dba", "bcee", "cd"]', 'expected_output': 'true'},
        {'input': '"edda"\n["dc", "ac", "baded", "deed", "bacad", "b", "eecc"]', 'expected_output': 'false'},
        {'input': '"dcbeaaadacbcab"\n["eeac", "e", "dcbe", "ab", "dacbc", "a", "aa"]', 'expected_output': 'true'},
        {'input': '"addccbe"\n["bddcc", "cb", "dd"]', 'expected_output': 'false'},
        {'input': '"ddecdde"\n["acdd", "c", "acded", "dde", "eccbe", "bbedb", "ccb"]', 'expected_output': 'true'},
        {'input': '"bcdcbcbebebe"\n["bcd", "be", "cbc", "aa", "aaabb"]', 'expected_output': 'true'},
        {'input': '"bbc"\n["c", "bc", "ce", "deada", "deba", "bbc", "dbce", "e"]', 'expected_output': 'true'},
        {'input': '"cadbddabdda"\n["cad", "bdda"]', 'expected_output': 'true'},
        {'input': '"ba"\n["dcb", "dbbda", "ba", "dacd"]', 'expected_output': 'true'},
        {'input': '"aecac"\n["ac"]', 'expected_output': 'false'},
        {'input': '"badbeccac"\n["ddb", "eccac", "badb"]', 'expected_output': 'true'},
        {'input': '"a"\n["a", "e", "d", "ceeda", "da", "aec", "ae"]', 'expected_output': 'true'},
        {'input': '"eacbaecdbdabcbaeabcbbcb"\n["ea", "cbaec", "dbda", "bcb", "a"]', 'expected_output': 'true'},
        {'input': '"aaaa"\n["a"]', 'expected_output': 'true'},
        {'input': '"accbeccadddadbaddb"\n["cabd", "bcde", "ccbc", "aebb"]', 'expected_output': 'false'},
        {'input': '"bedcebedce"\n["ce", "daae", "b", "ad", "bedce", "d", "decb", "abda"]', 'expected_output': 'true'},
        {'input': '""\n["be", "c", "dda"]', 'expected_output': 'true'},
        {'input': '"ddadcdcceaddadc"\n["ddadc", "ccea", "debc", "cc", "d"]', 'expected_output': 'true'},
        {'input': '"aedceedbecbebcbd"\n["eebbd", "abeae", "baec"]', 'expected_output': 'false'},
        {'input': '"cdbd"\n["cdbd", "cee", "a", "bbc"]', 'expected_output': 'true'},
        {'input': '"dbcdd"\n["bed", "ceb", "a", "c", "ddaa", "baada", "dbcdd"]', 'expected_output': 'true'},
        {'input': '"cabeacbcabcabebcabacaccebea"\n["ac", "cabe", "cebea", "bcab"]', 'expected_output': 'true'},
        {'input': '"dbeabec"\n["ee", "c", "deee", "cace", "bd", "dce"]', 'expected_output': 'false'},
        {'input': '"abb"\n["ec", "becec", "abb"]', 'expected_output': 'true'},
        {'input': '"cabcabbbeecbaeccecbabbeecc"\n["daab", "dedec", "cab", "ecba", "da", "cb", "bbe", "ecc"]', 'expected_output': 'true'},
        {'input': '"bdccacbdccac"\n["ebeec", "eced", "c", "bdcca", "adebd"]', 'expected_output': 'true'},
        {'input': '"ddddbdddbdddbdddbcadaccddcad"\n["cecad", "d", "dddb", "cad", "aadeb", "accdd"]', 'expected_output': 'true'},
        {'input': '"dbddbddbd"\n["c", "eabee", "ae", "e", "addb", "dbd", "bbceb", "cab"]', 'expected_output': 'true'},
        {'input': '"ebabeaeaeba"\n["eaeeb", "eba", "beaea", "aeac", "d", "ecba"]', 'expected_output': 'true'},
        {'input': '"bccbbccbeeaebccbbccbbccbbccb"\n["bccb", "eeae"]', 'expected_output': 'true'},
        {'input': '"ababdababdcd"\n["cd", "ababd"]', 'expected_output': 'true'},
        {'input': '"c"\n["b", "cec", "dd", "ee", "cede", "e", "eedec"]', 'expected_output': 'false'},
        {'input': '"ede"\n["ede"]', 'expected_output': 'true'},
        {'input': '"ebeeeacbaddecebeeaabaabebeeaab"\n["ebee", "dcb", "eacba", "ddec", "cbde", "c", "aab", "be"]', 'expected_output': 'true'},
        {'input': '"aeeabcaccac"\n["bca", "aee", "cbccb", "e", "ccac", "a"]', 'expected_output': 'true'},
        {'input': '"abedd"\n["cb"]', 'expected_output': 'false'},
        {'input': '"beacdbebcdbe"\n["cdbe", "b", "deb", "d", "bea", "ebe", "bbabb"]', 'expected_output': 'true'},
        {'input': '"dcebdcebdcebdceb"\n["ea", "dceb"]', 'expected_output': 'true'},
        {'input': '"edeadd"\n["dcb", "bb", "add", "ede", "aea", "ab"]', 'expected_output': 'true'},
        {'input': '"eebbabbecbc"\n["ab", "e", "ecbc", "a", "b"]', 'expected_output': 'true'},
        {'input': '""\n["bec", "dec", "bbaa", "dda", "dca", "edebd", "ecc", "bbab"]', 'expected_output': 'true'},
        {'input': '"ccdccd"\n["c", "ccd"]', 'expected_output': 'true'},
        {'input': '"eecdaceecdacecba"\n["c", "cdccd", "eecda", "ecba", "eb", "ad"]', 'expected_output': 'true'},
        {'input': '"adacbeecc"\n["c", "adacb", "aeaed", "e", "deda"]', 'expected_output': 'true'},
        {'input': '"edabecaedabeca"\n["cab", "abeca", "ed", "de"]', 'expected_output': 'true'},
        {'input': '""\n["eabed", "cdaca", "ea", "b"]', 'expected_output': 'true'},
        {'input': '"ccaaeacbcbabbaaaccaae"\n["abba", "bbe", "bc", "a", "ccaae", "e", "cb", "cbcb"]', 'expected_output': 'true'},
        {'input': '"aeaaea"\n["aea"]', 'expected_output': 'true'},
        {'input': '"eadadcdcae"\n["eee", "b", "cdb", "adaed", "c", "bbccd", "bcbec", "dd"]', 'expected_output': 'false'},
        {'input': '"cadccadcebeba"\n["dbd", "dcbb", "cadc", "eaba", "a", "eb", "bcac"]', 'expected_output': 'true'},
        {'input': '"cd"\n["cd"]', 'expected_output': 'true'},
        {'input': '"addbeeda"\n["bcbbd", "ebad", "ddaad", "ae", "cab", "eadd", "aceab"]', 'expected_output': 'false'},
        {'input': '"aeeebaeebb"\n["e", "aee", "bb", "b"]', 'expected_output': 'true'},
        {'input': '"ccabacccabaecc"\n["caba", "c", "ec"]', 'expected_output': 'true'},
        {'input': '"ccedacacebcacebadb"\n["cceda", "caceb", "dbada", "adb", "ceac", "cbdce"]', 'expected_output': 'true'},
        {'input': '"de"\n["abeaa", "aea", "aeaba"]', 'expected_output': 'false'},
        {'input': '"eceacbaa"\n["cde", "babe", "cbaa", "e", "cea"]', 'expected_output': 'true'},
        {'input': '"baaccedeade"\n["de", "ad", "abc", "cac", "aaec", "b"]', 'expected_output': 'false'},
        {'input': '"d"\n["ceed", "dcaa", "d", "bc", "e", "dece", "ceeea", "c"]', 'expected_output': 'true'},
        {'input': '"ddbec"\n["ddbec", "bddcc", "eba", "aabb", "abdb", "dcd", "da", "cd"]', 'expected_output': 'true'},
        {'input': '"bccaabccaa"\n["bccaa"]', 'expected_output': 'true'},
        {'input': '"a"\n["a", "ac"]', 'expected_output': 'true'},
        {'input': '"caabcbcbeadbccaab"\n["cb", "eadbc", "caab"]', 'expected_output': 'true'},
        {'input': '"cdaeb"\n["ecb", "bb", "eaeaa", "cdaeb"]', 'expected_output': 'true'},
        {'input': '"becd"\n["becd", "ca"]', 'expected_output': 'true'},
        {'input': '"aeeac"\n["ce"]', 'expected_output': 'false'},
        {'input': '"babcbabcadad"\n["eee", "ed", "ededb", "adad", "dac", "cebad", "babc"]', 'expected_output': 'true'},
        {'input': '"bcbabecaeaa"\n["cbc", "a"]', 'expected_output': 'false'},
        {'input': '"bedaebedaebedaebedaeccdbedaeccd"\n["ccd", "bedae"]', 'expected_output': 'true'},
        {'input': '"badedaceebaedddbaccc"\n["eedad", "eee", "ccad", "abd"]', 'expected_output': 'false'},
        {'input': '"bdbbbccccece"\n["cc", "bdbbb", "ece", "e", "cbbbc"]', 'expected_output': 'true'},
        {'input': '"aaddbcaaa"\n["becbe", "a", "ea", "accdb", "e", "bbcab", "eeb"]', 'expected_output': 'false'},
        {'input': '""\n["bac", "ddb", "d", "a", "ec"]', 'expected_output': 'true'},
        {'input': '"beeacadcbcedbbbcaeb"\n["cab", "dbadc", "aabae", "bbad"]', 'expected_output': 'false'},
        {'input': '"daddad"\n["dad"]', 'expected_output': 'true'},
        {'input': '"d"\n["bba", "d"]', 'expected_output': 'true'},
        {'input': '"caaaabcdbcaaabcdaaabceb"\n["d", "aaabc", "eb", "ca", "bc"]', 'expected_output': 'true'},
        {'input': '"bebdcbacedccacabeb"\n["aeae", "ecedc", "dc", "bace", "d", "ca", "beb"]', 'expected_output': 'true'},
        {'input': '"bcc"\n["ecada"]', 'expected_output': 'false'},
        {'input': '"dbeadacd"\n["bddd"]', 'expected_output': 'false'},
        {'input': '"aae"\n["dbbcc"]', 'expected_output': 'false'},
        {'input': '"dcbaede"\n["cedc", "cee"]', 'expected_output': 'false'},
        {'input': '"cdeedeaccdadbcad"\n["babae", "bc", "adce", "dd"]', 'expected_output': 'false'},
        {'input': '""\n["beaec", "abae", "adde"]', 'expected_output': 'true'},
        {'input': '"eaedaaeabaa"\n["e", "ce", "bad", "cebd", "c"]', 'expected_output': 'false'},
        {'input': '"bb"\n["ecaa", "daa", "aeeae", "c", "bc"]', 'expected_output': 'false'},
        {'input': '"ed"\n["cbcec", "bbed", "d", "a"]', 'expected_output': 'false'},
        {'input': '"aeaeaeeaabbeccabbccabbadc"\n["ccabb", "ae", "bbe", "eaa", "adc"]', 'expected_output': 'true'},
        {'input': '"badbbdeddcccccbbadbbccdcbe"\n["cdcbe", "d", "eddc", "ccccb", "c", "badbb", "bee"]', 'expected_output': 'true'},
        {'input': '"bcbccabccabbcbccab"\n["bcb", "ccab"]', 'expected_output': 'true'},
        {'input': '"cccddecadeeccc"\n["cce", "ec", "cdd", "bb", "ecaea", "adeec", "cc"]', 'expected_output': 'true'},
        {'input': '"babdcadb"\n["e", "ededa", "cedee", "ceca", "ee"]', 'expected_output': 'false'},
        {'input': '"eabd"\n["bd", "b", "ea"]', 'expected_output': 'true'},
        {'input': '"cbecccbec"\n["be", "c"]', 'expected_output': 'true'},
        {'input': '""\n["edbd", "aecc", "dab", "d", "edb", "cec", "cdcdd"]', 'expected_output': 'true'},
        {'input': '"ebdbaeddcbdbbceed"\n["e"]', 'expected_output': 'false'},
        {'input': '"cccdbdbbebc"\n["bebc", "cdbdb", "cc", "bdebb"]', 'expected_output': 'true'},
        {'input': '"adabbdcebbbdcebbdcebbdcebbdceb"\n["e", "b", "adbe", "bdceb", "ada"]', 'expected_output': 'true'},
        {'input': '"ccbcedab"\n["edab", "eaecd", "bb", "bdba", "adeac", "c", "b", "bacad"]', 'expected_output': 'true'},
        {'input': '"daddceadcdaddaaedabe"\n["da", "ec", "bea", "daab", "bbbcd", "aeaec", "bae", "d"]', 'expected_output': 'false'},
        {'input': '"aaaabdaabdaa"\n["a", "abda"]', 'expected_output': 'true'},
        {'input': '"ddaabddaab"\n["cccbd", "ddaab", "da"]', 'expected_output': 'true'},
        {'input': '"cccccccc"\n["cc"]', 'expected_output': 'true'},
        {'input': '"aecaec"\n["c", "aecae"]', 'expected_output': 'true'},
        {'input': '"dccdac"\n["caed"]', 'expected_output': 'false'},
        {'input': '"debaeaecdebaeecdaadbeca"\n["a", "daadb", "debae", "ec"]', 'expected_output': 'true'},
        {'input': '"eaceaceaceaceaceaceac"\n["eac"]', 'expected_output': 'true'},
        {'input': '"ddebdecbadabdbeababd"\n["abd", "ede", "be", "beab", "ddeb", "de", "cbad"]', 'expected_output': 'true'},
        {'input': '"daaaaaacb"\n["aa", "cb", "da", "a"]', 'expected_output': 'true'},
        {'input': '"bdcbeadcebbebbebbeacdbacdb"\n["c", "acdb", "eadce", "bbe", "bdcb"]', 'expected_output': 'true'},
        {'input': '"bdacd"\n["dc", "ced"]', 'expected_output': 'false'},
        {'input': '"b"\n["cca", "b"]', 'expected_output': 'true'},
        {'input': '"eecbeabeeecbeecceeecbeecce"\n["eecce", "eecb", "eabe"]', 'expected_output': 'true'},
        {'input': '"edeedccde"\n["ad", "d", "dbcea", "cbee", "ecca", "deed", "e", "ccd"]', 'expected_output': 'true'},
        {'input': '"abeadaedabeeaed"\n["ab", "abee", "edcbe", "ead", "adcd", "abd", "aed"]', 'expected_output': 'true'},
        {'input': '"bbccbbbbbccb"\n["cec", "bbccb", "b"]', 'expected_output': 'true'},
        {'input': '"caeeeddbedeeeeee"\n["ee", "ddbed", "e", "ca"]', 'expected_output': 'true'},
        {'input': '"aa"\n["eabc", "dc", "dd", "a"]', 'expected_output': 'true'},
        {'input': '"dcc"\n["ad", "c", "dc"]', 'expected_output': 'true'},
        {'input': '""\n["e", "c", "daa"]', 'expected_output': 'true'},
        {'input': '"dabaca"\n["ce", "ecb"]', 'expected_output': 'false'},
        {'input': '"cccdaadebcbdbd"\n["ebbbb"]', 'expected_output': 'false'},
        {'input': '"eaceebabceebbc"\n["aacc", "ede"]', 'expected_output': 'false'},
        {'input': '"caabacbadccbbbbcbbbbaaeee"\n["aaeee", "be", "decee", "aba", "cead", "cbadc", "ca", "cbbbb"]', 'expected_output': 'true'},
        {'input': '"aceccadacecc"\n["d", "a", "acecc", "eadad", "bdd"]', 'expected_output': 'true'},
        {'input': '"cecdececdececde"\n["cecde"]', 'expected_output': 'true'},
        {'input': '"bdbaeaadad"\n["aada", "bb", "bdbae", "d"]', 'expected_output': 'true'},
        {'input': '"bcccabecacbadcacebd"\n["e", "edcba", "abeea", "cb"]', 'expected_output': 'false'},
        {'input': '"aecacb"\n["eeadc", "eb", "d", "ab", "bdb", "cbd", "bdcba"]', 'expected_output': 'false'},
        {'input': '"daeabaaeabaaeabacdcaeabadaeaba"\n["aeaba", "ca", "cdc", "d"]', 'expected_output': 'true'},
        {'input': '"cbcdcdbddcccaebcacbeccbaebca"\n["ccb", "aebca", "cbe", "db", "cbcdc", "ddccc"]', 'expected_output': 'true'},
        {'input': '"bcbacdadadabccdbccd"\n["eba", "bccd", "bcbac", "c", "da", "deebd", "ae"]', 'expected_output': 'true'},
        {'input': '"ddbacd"\n["bacd", "d", "dced", "beb", "bd", "cbb"]', 'expected_output': 'true'},
        {'input': '"dabeaaeaeda"\n["eda", "acba", "dcab"]', 'expected_output': 'false'},
        {'input': '"ccbcbdbdddbceb"\n["cd", "dcae", "e", "ba", "edabe", "c", "dbce"]', 'expected_output': 'false'},
        {'input': '"cbccbcbbcbccaca"\n["b", "ca", "cbc"]', 'expected_output': 'true'},
        {'input': '"aaeadbbcb"\n["a", "ee", "edc", "cbb", "ea", "dbbcb"]', 'expected_output': 'true'},
        {'input': '"cebecccecc"\n["cec", "c", "ebec"]', 'expected_output': 'true'},
        {'input': '"caaebdbd"\n["ec", "ba", "d", "caae", "bbc", "bd", "bcbbb", "bbb"]', 'expected_output': 'true'},
        {'input': '"dbbaeaedcadcceacbaa"\n["bce", "bea", "e", "adbbd", "eae", "cdcdc"]', 'expected_output': 'false'},
        {'input': '"ddddbbbb"\n["dd", "b", "bea"]', 'expected_output': 'true'},
        {'input': '"bededd"\n["aeeac", "cdab"]', 'expected_output': 'false'},
        {'input': '"babadbedbcbed"\n["caaae", "ceddd", "ccda", "c", "cbda", "bbebd", "ccab", "ab"]', 'expected_output': 'false'},
        {'input': '"aaccaacababbe"\n["c", "ad", "abbe", "adcc", "abb", "abaee", "aac", "ab"]', 'expected_output': 'true'},
        {'input': '"adabaecadadad"\n["bae", "c", "ada", "dad"]', 'expected_output': 'true'},
        {'input': '"ebbbcaabeaaddae"\n["ccc"]', 'expected_output': 'false'},
        {'input': '"beceecaabccaabceddcdecaabc"\n["e", "bec", "caabc", "ddcde"]', 'expected_output': 'true'},
        {'input': '"ddddddccdddacdddaddda"\n["c", "ddda", "ddd"]', 'expected_output': 'true'},
        {'input': '"eaababddaae"\n["ee", "dd", "edd"]', 'expected_output': 'false'},
        {'input': '"bebedcedcbebbeb"\n["edc", "beb"]', 'expected_output': 'true'},
        {'input': '""\n["bcc", "cdcc", "aac", "aad", "c"]', 'expected_output': 'true'},
        {'input': '"cccc"\n["c"]', 'expected_output': 'true'},
        {'input': '"cdbcdbcdbcdbcdbebeacdbcdb"\n["cdb", "ebea"]', 'expected_output': 'true'},
        {'input': '"dcccadcccacbdcbddccca"\n["dccca", "cbd"]', 'expected_output': 'true'},
        {'input': '"cabaeecebbebdedebcbbebbd"\n["bbd", "bcc", "ebb", "ebde", "de", "bcbbe", "abaee", "c"]', 'expected_output': 'true'},
        {'input': '""\n["cbad", "c"]', 'expected_output': 'true'},
        {'input': '"cce"\n["ca", "dacbd", "ea", "cedec", "cce"]', 'expected_output': 'true'},
        {'input': '"eabddbddeabddeaeabdd"\n["ea", "bdd"]', 'expected_output': 'true'},
        {'input': '"aecacbeeedbcabdedeed"\n["ee", "ce", "ac", "cc", "d"]', 'expected_output': 'false'},
        {'input': '"beadeadeebbcbcbb"\n["db", "ded", "a", "ca", "b", "d", "ddc", "ceb"]', 'expected_output': 'false'},
        {'input': '"ee"\n["e"]', 'expected_output': 'true'},
        {'input': '"ceadbceadb"\n["eb", "ceadb", "de", "ebead", "cea", "aa"]', 'expected_output': 'true'},
        {'input': '"daaadaaadaaadaaadaaadaaadaaa"\n["daaa"]', 'expected_output': 'true'},
        {'input': '"abcabccdaeadbcdab"\n["cda", "abc", "b", "ead"]', 'expected_output': 'true'},
        {'input': '"abeaabcdacd"\n["c", "b", "aab", "cda", "cd", "ab", "cb", "ea"]', 'expected_output': 'true'},
        {'input': '"eeceeeceeeceeeceeeceeece"\n["eece"]', 'expected_output': 'true'},
        {'input': '"ebebebebeb"\n["eb"]', 'expected_output': 'true'},
        {'input': '"c"\n["caa", "cbc", "c", "d", "aee", "abe"]', 'expected_output': 'true'},
        {'input': '"ecaeca"\n["eca", "adc", "bacaa", "aeda"]', 'expected_output': 'true'},
        {'input': '"eecb"\n["b", "edda", "e"]', 'expected_output': 'false'},
        {'input': '""\n["bcb", "a"]', 'expected_output': 'true'},
        {'input': '"b"\n["bb", "dd", "cbad", "babab", "b"]', 'expected_output': 'true'},
        {'input': '"aabbcbbeedacabbbce"\n["b", "dca", "ead"]', 'expected_output': 'false'},
        {'input': '"adcbbccbedebdcdb"\n["abad", "d", "cdbd"]', 'expected_output': 'false'},
        {'input': '"acdedaaecedceb"\n["cebcc", "abdab", "aee", "bb", "badc", "bdbec"]', 'expected_output': 'false'},
        {'input': '"cacacacacaca"\n["ca"]', 'expected_output': 'true'},
        {'input': '"ebaecdeeeecab"\n["ccc", "e", "aeb", "eaec", "aeaed", "cb"]', 'expected_output': 'false'},
        {'input': '"cabeeeede"\n["eeede", "bab", "abe", "c"]', 'expected_output': 'true'},
        {'input': '"eade"\n["eade"]', 'expected_output': 'true'},
        {'input': '"ecebccda"\n["ece", "bccda"]', 'expected_output': 'true'},
        {'input': '"dcedae"\n["dce", "dced", "ecabc", "c", "ed", "edccb", "ccdee"]', 'expected_output': 'false'},
        {'input': '""\n["d", "eabb", "deae", "e"]', 'expected_output': 'true'},
        {'input': '"ccd"\n["dac", "c", "d"]', 'expected_output': 'true'},
        {'input': '"baeeabaeeabaeeabaeeabaeeabaeea"\n["baeea"]', 'expected_output': 'true'},
        {'input': '"cdbccedaebbebb"\n["dbcc", "acde", "ebb", "eda", "c", "ba"]', 'expected_output': 'true'},
        {'input': '""\n["cdd"]', 'expected_output': 'true'},
        {'input': '"ec"\n["cdcbb", "ec", "beda", "aded"]', 'expected_output': 'true'},
        {'input': '"ebe"\n["cdcdd", "ea", "dc", "addeb", "b", "de", "beec"]', 'expected_output': 'false'},
        {'input': '"acededeaeeace"\n["ace", "aee", "ded", "e"]', 'expected_output': 'true'},
        {'input': '"ddaeddab"\n["ddce", "edadb", "cdbb", "abbde", "be", "ceaad"]', 'expected_output': 'false'},
        {'input': '"aedecedacdaede"\n["ae", "c", "a", "edacd", "bbdcb", "de", "deaaa", "aede"]', 'expected_output': 'true'},
        {'input': '"ccbddbd"\n["cbdcd", "e", "bd", "d", "cc"]', 'expected_output': 'true'},
        {'input': '"beae"\n["beae", "aedab"]', 'expected_output': 'true'},
        {'input': '"dadddaeac"\n["cbe"]', 'expected_output': 'false'},
        {'input': '"dced"\n["d", "dced", "e", "ab", "bba"]', 'expected_output': 'true'},
        {'input': '"dacbdccdabadce"\n["dacb", "dce", "daba", "ddcc", "dc", "c", "dabca"]', 'expected_output': 'true'},
        {'input': '"cabcbdbcbcacdeead"\n["ceace", "aedb", "bae", "b"]', 'expected_output': 'false'},
        {'input': '"eeccecadcbcecadccecce"\n["e", "c", "ecce", "cadc", "ba", "bce"]', 'expected_output': 'true'},
        {'input': '""\n["ab", "ed", "daadb"]', 'expected_output': 'true'},
        {'input': '"ccbb"\n["debe", "d", "cad", "ee", "ccbb"]', 'expected_output': 'true'},
        {'input': '"aedabe"\n["bb", "abdb", "aa", "abe", "bda", "aede", "aed", "cddc"]', 'expected_output': 'true'},
        {'input': '"dcdcdcdcdcdc"\n["dc"]', 'expected_output': 'true'},
        {'input': '""\n["adcb"]', 'expected_output': 'true'},
        {'input': '"bbbcddabeec"\n["abbec", "bbe", "aaebb", "aa", "cbaec"]', 'expected_output': 'false'},
        {'input': '"baddaadbdebdbaadbaeacebaddb"\n["abee", "b", "aeace", "debdb", "aadb", "badd"]', 'expected_output': 'true'},
        {'input': '"babaecceccbacddce"\n["ba", "dab", "cddce", "ecc", "beabb", "dedc", "baba"]', 'expected_output': 'true'},
        {'input': '""\n["bebb", "bad", "bbd", "eca"]', 'expected_output': 'true'},
        {'input': '"eebeebeebeeb"\n["eeb"]', 'expected_output': 'true'},
        {'input': '"adecc"\n["adecc"]', 'expected_output': 'true'},
        {'input': '"aeaaeaeacebddea"\n["cbdbc", "dedad", "cee", "a", "bbbb", "caabe", "bbae"]', 'expected_output': 'false'},
        {'input': '"bdaacbdaac"\n["bdaac"]', 'expected_output': 'true'},
        {'input': '"dededeabdececde"\n["ecec", "de", "abd"]', 'expected_output': 'true'},
        {'input': '"eeaecdadaeaecdada"\n["dada", "e", "bbba", "eaec", "eeede"]', 'expected_output': 'true'},
        {'input': '"eceadeadcde"\n["baaae", "edee", "bcb", "bbd", "bda"]', 'expected_output': 'false'},
        {'input': '"ebacdbdeadabbd"\n["ebac", "ad", "acca", "adab", "db", "bd", "de"]', 'expected_output': 'true'},
        {'input': '"daacedcddedcdddaac"\n["b", "cd", "edcdd", "daac", "da"]', 'expected_output': 'true'},
        {'input': '"ebaedbabacddeceecebddeceeceb"\n["eeceb", "ddec", "eb", "d", "ebaed", "babac", "c"]', 'expected_output': 'true'},
        {'input': '"acacacac"\n["ac"]', 'expected_output': 'true'},
        {'input': '""\n["acdcb", "bdca", "a", "d", "b"]', 'expected_output': 'true'},
        {'input': '"abcabeeea"\n["adea", "daedc", "b", "eedba"]', 'expected_output': 'false'},
        {'input': '"ddbaeecdcdcbabc"\n["cdba", "decce", "e", "eedad", "cdee", "edecc", "b"]', 'expected_output': 'false'},
        {'input': '"eebbaeababdbcacd"\n["cbbed", "ebed", "ce", "b"]', 'expected_output': 'false'},
        {'input': '""\n["baeac", "d"]', 'expected_output': 'true'},
        {'input': '"bdabdabdadaeadaeabdadaea"\n["daea", "bda"]', 'expected_output': 'true'},
        {'input': '"decdcebdc"\n["cebdc", "d", "eeede", "aed", "ebed", "a", "decd"]', 'expected_output': 'true'},
        {'input': '""\n["cbe", "adadc"]', 'expected_output': 'true'},
        {'input': '"cedddcadddddbbca"\n["b"]', 'expected_output': 'false'},
        {'input': '"abaaabaaabaaabaaabaa"\n["abaa"]', 'expected_output': 'true'},
        {'input': '"ddeb"\n["d", "deb"]', 'expected_output': 'true'},
        {'input': '"bbaceebaacabaacaaceebaaca"\n["ec", "a", "ccc", "baaca", "b", "acee"]', 'expected_output': 'true'},
        {'input': '"aaabac"\n["ac", "baadc", "e", "bcdde", "bea", "aaab", "added"]', 'expected_output': 'true'},
        {'input': '"decdecdec"\n["e", "dec"]', 'expected_output': 'true'},
        {'input': '"ddad"\n["b"]', 'expected_output': 'false'},
        {'input': '"adbaaacdeddadbacdedadbacded"\n["cdcab", "d", "aec", "adb", "ddde", "aa", "acded", "dadec"]', 'expected_output': 'true'},
        {'input': '"eabccceadbba"\n["bebe", "badb", "ecde", "bced", "cddad"]', 'expected_output': 'false'},
        {'input': '"cacaededbbeed"\n["ae", "ed", "bbe", "adde", "aebc", "ded", "cac"]', 'expected_output': 'true'},
        {'input': '"d"\n["b", "d", "de", "edc", "ddcde"]', 'expected_output': 'true'},
        {'input': '"ebedebedebed"\n["abcaa", "caba", "b", "ebed"]', 'expected_output': 'true'},
        {'input': '"bcbbcabadcbcbbbcbb"\n["dab", "c", "abadc", "bcbb", "ad"]', 'expected_output': 'true'},
        {'input': '"eeeee"\n["e"]', 'expected_output': 'true'},
        {'input': '"bbbb"\n["ab", "dacd", "bb", "aeaae", "ceebb", "e", "cedc", "bce"]', 'expected_output': 'true'},
        {'input': '"becdbacabeebaddbe"\n["ab", "dbaca", "be", "ebabd", "ebadd", "c"]', 'expected_output': 'true'},
        {'input': '"bbb"\n["b", "a", "d", "e"]', 'expected_output': 'true'},
        {'input': '"aaaadbaaaadb"\n["da", "aaaa", "db"]', 'expected_output': 'true'},
        {'input': '"ddcddadaddcdebebddcddadaddcd"\n["ddcd", "dada", "eb"]', 'expected_output': 'true'},
        {'input': '"ddaddaddaddaddaddadda"\n["dda"]', 'expected_output': 'true'},
        {'input': '"cbabbccbaccbacc"\n["c", "cba", "bb"]', 'expected_output': 'true'},
        {'input': '"ceceeeeababeeececab"\n["c", "cece", "eee", "ac", "cb", "ab", "cecab", "a"]', 'expected_output': 'true'},
        {'input': '"ddbeeddbeeddddbee"\n["bee", "dd"]', 'expected_output': 'true'},
        {'input': '"dcaedebaddcaeddcae"\n["d", "dcae", "a", "eb"]', 'expected_output': 'true'},
        {'input': '"dbbedadcbabdbcca"\n["a", "ebcc", "becec", "bbcd"]', 'expected_output': 'false'},
        {'input': '"cdabeaadeaaddaadcdaadccdabeaadaaaab"\n["eaad", "aaaab", "cdab", "ccded", "b", "d", "daadc"]', 'expected_output': 'true'},
        {'input': '"eecdbcddacd"\n["edbc"]', 'expected_output': 'false'},
        {'input': '"abbddbcbbcabbbcabb"\n["b", "ddbc", "de", "ebbba", "d", "bc", "abb"]', 'expected_output': 'true'},
        {'input': '"e"\n["aba", "aacda", "eaecb", "e", "abb"]', 'expected_output': 'true'},
        {'input': '""\n["c", "bde", "bbb", "edae", "b"]', 'expected_output': 'true'},
        {'input': '"ddddddacddacdd"\n["c", "dd", "ac", "ae"]', 'expected_output': 'true'},
        {'input': '"ee"\n["e", "aad", "ecae", "ceea"]', 'expected_output': 'true'},
        {'input': '"cccb"\n["b", "de", "dbe", "adbd"]', 'expected_output': 'false'},
        {'input': '"eadabbbeda"\n["c", "b"]', 'expected_output': 'false'},
        {'input': '"dddaccdcdaeeeddec"\n["d", "bee", "dbae", "e"]', 'expected_output': 'false'},
        {'input': '"edbcdcdbcdcec"\n["dbcdc", "e", "c"]', 'expected_output': 'true'},
        {'input': '"bebeaecbbe"\n["b", "aec", "be"]', 'expected_output': 'true'},
        {'input': '"decdceecdceecdecdceecdceecdceecdceec"\n["dceec", "dec"]', 'expected_output': 'true'},
        {'input': '"ccacecd"\n["eadbb", "b", "bacae", "cdc", "cbbba", "baebd", "a", "cb"]', 'expected_output': 'false'},
        {'input': '"ebeeebeebeebeeaaeaebeeadbeb"\n["bceb", "ebe", "ebee", "d", "eeed", "adbe", "b", "eaaea"]', 'expected_output': 'true'},
        {'input': '"cdcdececb"\n["cdbd", "cd", "ccc", "ecd", "ececb"]', 'expected_output': 'true'},
        {'input': '"bdc"\n["da", "dbda", "bacee", "bab"]', 'expected_output': 'false'},
        {'input': '"eecaceecacdabbceadabba"\n["d", "cea", "ddccc", "a", "bde", "eaadc", "dabb", "eecac"]', 'expected_output': 'true'},
        {'input': '"aebabacdabaecdeaba"\n["e", "cd", "aba", "aeb"]', 'expected_output': 'true'},
        {'input': '"dccdcededcededcedeabeedcede"\n["abee", "dcc", "dcede"]', 'expected_output': 'true'},
        {'input': '"dccae"\n["ccca", "b", "eaae", "ccbad", "dcca", "e", "bc"]', 'expected_output': 'true'},
        {'input': '"aeaecaeecaeecaeecaee"\n["caee", "ae", "dcd"]', 'expected_output': 'true'},
        {'input': '"da"\n["deedb", "b", "cbbea"]', 'expected_output': 'false'},
        {'input': '"dbbaeeebabea"\n["caee", "adabb", "e", "adbb", "c", "daae", "aaac", "bab"]', 'expected_output': 'false'},
        {'input': '"bbbb"\n["aae", "bb", "edb"]', 'expected_output': 'true'},
        {'input': '"cbabbeeedaadedd"\n["bd", "bb", "aba", "a", "eabaa", "caed", "ece"]', 'expected_output': 'false'},
        {'input': '"abbcaabbcaabbcabbb"\n["abbca", "bddcd", "b"]', 'expected_output': 'true'},
        {'input': '"bbceadad"\n["adad", "dada", "b", "bce"]', 'expected_output': 'true'},
        {'input': '"ecbdabd"\n["eeec", "dd"]', 'expected_output': 'false'},
        {'input': '"ebbaacddde"\n["b", "bcbcc", "eabb", "cbee"]', 'expected_output': 'false'},
        {'input': '"bededaeacbdebbc"\n["eb", "bde", "bc", "bede", "cbdeb", "e", "daea"]', 'expected_output': 'true'},
        {'input': '"abcdbedddeedeaabec"\n["cb", "dc"]', 'expected_output': 'false'},
        {'input': '"eba"\n["aecd", "ba", "be"]', 'expected_output': 'false'},
        {'input': '"debdeeaecdebdededdbdeddbeaecdebdedebde"\n["eaec", "deddb", "debde"]', 'expected_output': 'true'},
        {'input': '"ebcbeaadbabccebeedd"\n["b", "daec"]', 'expected_output': 'false'},
        {'input': '"ebebebdeebbedcc"\n["ce", "ebae", "d", "eb", "bedcc", "ced", "eeb", "aa"]', 'expected_output': 'true'},
        {'input': '"aebaebbaebebebaebbcdb"\n["baebb", "bd", "db", "c", "ae", "be"]', 'expected_output': 'true'},
        {'input': '"aeedeadbaecadeea"\n["eecb"]', 'expected_output': 'false'},
        {'input': '"eadbc"\n["ddb", "cac", "da", "eddcc", "e", "adbc"]', 'expected_output': 'true'},
        {'input': '"acc"\n["dadcb", "ebe"]', 'expected_output': 'false'},
        {'input': '"aabcbbabcbbabcbb"\n["dca", "cd", "a", "abcbb"]', 'expected_output': 'true'},
        {'input': '"dcdc"\n["dc"]', 'expected_output': 'true'},
        {'input': '"eebb"\n["bb", "e", "a"]', 'expected_output': 'true'},
        {'input': '"bcbadcedbebabecaa"\n["ebdaa", "eabb", "cb", "e", "a", "bc", "bbe"]', 'expected_output': 'false'},
        {'input': '"eeeee"\n["e", "cacae"]', 'expected_output': 'true'},
        {'input': '"eab"\n["de", "e", "dbb"]', 'expected_output': 'false'},
        {'input': '"e"\n["d", "ba", "bbccc", "dbbc", "abdae", "dccd", "cda"]', 'expected_output': 'false'},
        {'input': '"abebdceabbdecbccec"\n["ccec", "ecb", "abeb", "abbd", "dce"]', 'expected_output': 'true'},
        {'input': '""\n["bedc"]', 'expected_output': 'true'},
        {'input': '"db"\n["a", "ecaee", "dee", "edecd", "aabc"]', 'expected_output': 'false'},
        {'input': '"bc"\n["cbeb", "aea", "bddac", "bc", "be", "a", "cda", "b"]', 'expected_output': 'true'},
        {'input': '"cbaceee"\n["eb", "bcd", "bea", "aedda", "acaa", "ccdce"]', 'expected_output': 'false'},
        {'input': '"eccdbeeeeebdddce"\n["aced", "dce", "dcced", "c", "cb", "b"]', 'expected_output': 'false'},
        {'input': '"dcebbeabcbcddedde"\n["bcc", "cdb"]', 'expected_output': 'false'},
        {'input': '"ddcdcddcdc"\n["ddcdc"]', 'expected_output': 'true'},
        {'input': '"dbceaddadddbbdaddacde"\n["dbbd", "dbce", "add", "d", "acde", "ec", "dbceb"]', 'expected_output': 'true'},
        {'input': '"cccae"\n["cbb", "bd", "b", "da", "a"]', 'expected_output': 'false'},
        {'input': '"abbdabbdeabbd"\n["abbd", "d", "e"]', 'expected_output': 'true'},
        {'input': '""\n["c", "a", "dbada", "be", "d", "aebbb"]', 'expected_output': 'true'},
        {'input': '"ebeacbaeddcdaecccd"\n["a", "dbabd", "de", "ccbb", "ca"]', 'expected_output': 'false'},
        {'input': '"acce"\n["ac", "bd", "e", "ce"]', 'expected_output': 'true'},
        {'input': '"cbeaeedbabacedbc"\n["bb", "eca", "a"]', 'expected_output': 'false'},
        {'input': '"bbcabbca"\n["bbca"]', 'expected_output': 'true'},
        {'input': '"daecbdbc"\n["e", "bbba", "dbc", "aab", "daecb", "b", "bd"]', 'expected_output': 'true'},
        {'input': '"abcedabcedbabebabeabcedabced"\n["babe", "abced"]', 'expected_output': 'true'},
        {'input': '"ebeebbeebccbd"\n["e", "ecdbb", "acecd", "edcad", "beeb", "ccbd"]', 'expected_output': 'true'},
        {'input': '"bacbbeebcbbcbbbddb"\n["eeb", "db", "cda", "ba", "be", "cbb", "bddb"]', 'expected_output': 'true'},
        {'input': '"aabcdecdecdeaabaab"\n["cde", "aab"]', 'expected_output': 'true'},
        {'input': '"d"\n["cac", "aadbd", "d", "bd"]', 'expected_output': 'true'},
        {'input': '"baebae"\n["ac", "bae"]', 'expected_output': 'true'},
        {'input': '"dccac"\n["dcca", "bdc", "c"]', 'expected_output': 'true'},
        {'input': '"beaabceaabcedcecebedcecebe"\n["aabce", "be", "dcece"]', 'expected_output': 'true'},
        {'input': '"bccec"\n["eba", "bccec", "eebde"]', 'expected_output': 'true'},
        {'input': '"cebecabdcebeccebeccebec"\n["abd", "cebec"]', 'expected_output': 'true'},
        {'input': '"decededddeced"\n["edd", "aea", "deced", "dbe", "ee"]', 'expected_output': 'true'},
        {'input': '"cededaaadabaae"\n["de", "d", "bdbad", "c", "bbad", "bcbdd"]', 'expected_output': 'false'},
        {'input': '"a"\n["da", "cddeb", "b", "eba", "a", "cdcca", "debc"]', 'expected_output': 'true'},
        {'input': '"cbad"\n["eeb", "d", "cbad", "ddeaa", "a", "dca"]', 'expected_output': 'true'},
        {'input': '"cceccedbccdcadbccd"\n["cc", "ca", "dbc", "cd", "c", "cce"]', 'expected_output': 'true'},
        {'input': '"ddcadaecbcededdadda"\n["dcbc", "add"]', 'expected_output': 'false'},
        {'input': '"cecdccbdaaeddd"\n["d", "be", "aceac"]', 'expected_output': 'false'},
        {'input': '"ecaeeabcecae"\n["ecae", "eabc", "cee", "e", "ee"]', 'expected_output': 'true'},
        {'input': '"aeaabbeaeaabecdecbdbcebadebadbd"\n["becde", "cbdbc", "bd", "bbe", "aeaa", "ebad"]', 'expected_output': 'true'},
        {'input': '"aaacdcdbccaceadaaa"\n["c", "bad", "aaa", "d", "a", "dbc", "acead", "daac"]', 'expected_output': 'true'},
        {'input': '"eedcbadceeb"\n["b", "edcba", "deddb", "dce", "ee", "e"]', 'expected_output': 'true'},
        {'input': '"cabcb"\n["bdb", "cabcb", "d", "cbaa"]', 'expected_output': 'true'},
        {'input': '"cdcdecdeccccd"\n["ecca", "cba", "dda", "dec", "cccd", "edca", "cdc"]', 'expected_output': 'true'},
        {'input': '"edaebbeaeedceadcba"\n["edaeb", "dcea", "ccddd", "a", "beaee", "dcba"]', 'expected_output': 'true'},
        {'input': '"ade"\n["abee", "ade", "bdccd", "baeec", "dacc", "ccce", "d"]', 'expected_output': 'true'},
        {'input': '"c"\n["cc", "daac", "e", "b", "ecbe", "c", "bdd"]', 'expected_output': 'true'},
        {'input': '"abacadaeacccbcdeaaad"\n["cabc", "adeed", "cbbad", "baccb", "cbbdd", "e", "ccb", "cbec"]', 'expected_output': 'false'},
        {'input': '"dcdedabebbee"\n["c", "a", "dcde", "ebbee", "dab"]', 'expected_output': 'true'},
        {'input': '"baabdbaabdb"\n["edcac", "aabd", "b", "ea", "a"]', 'expected_output': 'true'},
        {'input': '"cc"\n["ccc", "a"]', 'expected_output': 'false'},
        {'input': '"dcdececcada"\n["ec", "ada", "ececc", "d", "dcd", "eeb"]', 'expected_output': 'true'},
        {'input': '"bacbacdaecdaec"\n["dd", "bac", "e", "daec"]', 'expected_output': 'true'},
        {'input': '"cedbced"\n["abac", "b", "ca", "ced"]', 'expected_output': 'true'},
        {'input': '"baacaad"\n["ecbea", "daeb", "acc", "edea", "dcbbe"]', 'expected_output': 'false'},
        {'input': '"bbeeeeadbcb"\n["dbb", "de", "be", "a"]', 'expected_output': 'false'},
        {'input': '"bdccbedcbbbedccbdedc"\n["ed", "edc", "dcbd", "bd", "c", "cbbb", "cbed"]', 'expected_output': 'true'},
        {'input': '"ebadedadceb"\n["eda", "e", "ecab", "dceb", "ebe", "ebad", "beb"]', 'expected_output': 'true'},
        {'input': '"c"\n["aadcd", "dbbda", "c"]', 'expected_output': 'true'},
        {'input': '"cbaabeeccba"\n["cdacc", "a", "abeec", "cb", "beea"]', 'expected_output': 'true'},
        {'input': '"ddbdedbdedbdeddbde"\n["dbde", "d", "adbac", "babdb"]', 'expected_output': 'true'},
        {'input': '"bcebceeecdadcaebcebceeebcebce"\n["bceee", "bce", "dcae", "cda", "bee"]', 'expected_output': 'true'},
        {'input': '"eccbeabcbc"\n["edacd", "adb", "cd"]', 'expected_output': 'false'},
        {'input': '"daacccbee"\n["accc", "da", "bee"]', 'expected_output': 'true'},
        {'input': '"bbaacdbbbbaaababcdbbab"\n["ab", "bbaa", "cdbb"]', 'expected_output': 'true'},
        {'input': '"aacaacaacbbbeeebbbeee"\n["aac", "eee", "bbb"]', 'expected_output': 'true'},
        {'input': '"cabaee"\n["bdece", "bbaa", "caad"]', 'expected_output': 'false'},
        {'input': '""\n["dcaba", "bebc", "aedec", "baeb"]', 'expected_output': 'true'},
        {'input': '"beaacbdedc"\n["eccc", "dda", "eac", "abc", "ac"]', 'expected_output': 'false'},
        {'input': '"caacadeacbabacbbbbac"\n["a", "ab", "bbec", "cddd", "deeb", "cc", "adada", "adebd"]', 'expected_output': 'false'},
        {'input': '"ccdedbdcabcdda"\n["cd", "dcaec"]', 'expected_output': 'false'},
        {'input': '"cd"\n["be", "ebab"]', 'expected_output': 'false'},
        {'input': '"bacbacbacbacbacbacbac"\n["bac"]', 'expected_output': 'true'},
        {'input': '"dab"\n["bbbea", "daedb"]', 'expected_output': 'false'},
        {'input': '""\n["e", "acb", "dd", "a"]', 'expected_output': 'true'},
        {'input': '"acadcacadc"\n["acadc", "abc", "bde", "bbce"]', 'expected_output': 'true'},
        {'input': '"aeaebe"\n["e", "ae", "b"]', 'expected_output': 'true'},
        {'input': '"cbbbaeceaedade"\n["b", "d", "e", "cbe", "a"]', 'expected_output': 'false'},
        {'input': '"bdbaddcab"\n["cdaea", "cdba", "d", "db", "e", "ce", "de", "ece"]', 'expected_output': 'false'},
        {'input': '"abeeacaadedcdcaadedcdcaaaccaaabeea"\n["caa", "dedcd", "abeea", "accaa"]', 'expected_output': 'true'},
        {'input': '"ccecceccedddcdddd"\n["d", "dd", "ebae", "cce", "cd", "bcd"]', 'expected_output': 'true'},
        {'input': '"aedac"\n["b", "cdc"]', 'expected_output': 'false'},
        {'input': '"babebbaccbd"\n["bed", "dbcce", "bc", "edcad", "eed", "bddbe", "bbbc"]', 'expected_output': 'false'},
        {'input': '"ecdbd"\n["dec", "edb", "a", "bc", "abdd", "ecd", "de", "bd"]', 'expected_output': 'true'},
        {'input': '"dacccadacdccc"\n["da", "a", "ccc", "cd"]', 'expected_output': 'true'},
        {'input': '"beecdbaecabaecaec"\n["ec", "beecd", "baeca"]', 'expected_output': 'true'},
        {'input': '"ebebdcaabeeb"\n["d", "dc", "aabe", "eb"]', 'expected_output': 'true'},
        {'input': '"ceeacceeac"\n["ceeac"]', 'expected_output': 'true'},
        {'input': '""\n["aedb", "eaec"]', 'expected_output': 'true'},
        {'input': '"dacbeacdedd"\n["b"]', 'expected_output': 'false'},
        {'input': '"b"\n["be", "caee", "ebacc", "b"]', 'expected_output': 'true'},
        {'input': '"eed"\n["d", "daeeb", "a", "bcc", "aadd", "dbab", "daecc"]', 'expected_output': 'false'},
        {'input': '"dadc"\n["dadee", "e", "aebcb", "a", "cd", "ec", "dadc"]', 'expected_output': 'true'},
        {'input': '"dbaaccbcb"\n["dae", "becd", "bbab"]', 'expected_output': 'false'},
        {'input': '"cdbaadacecaecbee"\n["adecc", "cbdbb", "bdda", "e", "dbcb", "ccdab"]', 'expected_output': 'false'},
        {'input': '"eecbcbecb"\n["cbecb", "eecb", "d", "beab", "aeaa", "a", "ba"]', 'expected_output': 'true'},
        {'input': '"cecdbc"\n["eacc", "eb"]', 'expected_output': 'false'},
        {'input': '"ecbcbecbcbdadcbdadcb"\n["ecbcb", "dadcb", "ae", "ecae"]', 'expected_output': 'true'},
        {'input': '"debbbdbd"\n["ce", "bceea", "eddac", "deb", "bdabb", "bbdbd", "cca", "eeed"]', 'expected_output': 'true'},
        {'input': '"eeededeedede"\n["e", "de"]', 'expected_output': 'true'},
        {'input': '"eddbcccebccebccebc"\n["cebc", "ea", "eddbc", "c"]', 'expected_output': 'true'},
        {'input': '"daeae"\n["dcbe", "daeae", "a", "ea", "aa", "cbd"]', 'expected_output': 'true'},
        {'input': '"e"\n["e", "dcd"]', 'expected_output': 'true'},
        {'input': '"cdadcdaddbacdaddbadbadbacdad"\n["dba", "cdad"]', 'expected_output': 'true'},
        {'input': '"ccccc"\n["c"]', 'expected_output': 'true'},
        {'input': '"dd"\n["cd"]', 'expected_output': 'false'},
        {'input': '"daadddaaddddaaddd"\n["aaddd", "d"]', 'expected_output': 'true'},
        {'input': '""\n["dde", "eccba", "ebcc"]', 'expected_output': 'true'},
        {'input': '"add"\n["badca", "a", "bcd", "abc", "eeb"]', 'expected_output': 'false'},
        {'input': '"acbbaaaeee"\n["ea", "ae", "aa"]', 'expected_output': 'false'},
        {'input': '""\n["bccc", "aecaa", "be", "bdaa"]', 'expected_output': 'true'},
        {'input': '"daedaedcdeddcdeddcdeddae"\n["ea", "dae", "dcded"]', 'expected_output': 'true'},
        {'input': '"eeeeee"\n["e"]', 'expected_output': 'true'},
        {'input': '"deaedeaeebcdeebcdedeaecbbcbb"\n["ebcde", "deae", "cbb"]', 'expected_output': 'true'},
        {'input': '"cbacebddadaaebcd"\n["babce", "bce", "bdbae", "c"]', 'expected_output': 'false'},
        {'input': '"ccdbe"\n["bdbb", "ac", "adda", "aeeca", "d"]', 'expected_output': 'false'},
        {'input': '"abaaaeabaaaeaaae"\n["ab", "aaae"]', 'expected_output': 'true'},
        {'input': '"edaedbbceedaedbee"\n["daedb", "bc", "ec", "e"]', 'expected_output': 'true'},
        {'input': '"dccacacaacacaccdacaca"\n["d", "acaca", "cc"]', 'expected_output': 'true'},
        {'input': '"cdeccbbeecacaedceeccbdebbacd"\n["cd", "eccb", "dce", "debba", "cacae", "bcbae", "bee", "a"]', 'expected_output': 'true'},
        {'input': '"bceec"\n["bbcd", "e", "bbab", "ccad", "de", "ec", "bc"]', 'expected_output': 'true'},
        {'input': '"eabaddccdaad"\n["eb", "aaae", "beca", "ace", "dda", "dd", "bdcbb"]', 'expected_output': 'false'},
        {'input': '"ececdaeeeaa"\n["e", "cecda", "eeaa"]', 'expected_output': 'true'},
        {'input': '""\n["ad", "dadda", "d", "bceea", "dd", "eb", "bc"]', 'expected_output': 'true'},
        {'input': '"bcedadabceda"\n["a", "bceda", "da"]', 'expected_output': 'true'},
        {'input': '""\n["ebde", "b", "bce", "edb", "c", "bcacb"]', 'expected_output': 'true'},
        {'input': '"aabddbbebbe"\n["aabdd", "bbe"]', 'expected_output': 'true'},
        {'input': '"ebccecaacdabcddbbccbacecaacecaa"\n["e", "ebc", "ccba", "cdabc", "ddbb", "cecaa"]', 'expected_output': 'true'},
        {'input': '"becbec"\n["bec"]', 'expected_output': 'true'},
        {'input': '"cddcd"\n["cd", "dece", "cdd", "bacca"]', 'expected_output': 'true'},
        {'input': '"decbdbecbdcbd"\n["eddcd", "be", "d", "ebe", "de", "b", "dced", "cbd"]', 'expected_output': 'true'},
        {'input': '"aebabebaba"\n["a", "ebab"]', 'expected_output': 'true'},
        {'input': '"adcdcebcb"\n["abd", "db", "ccad", "e", "adcdc", "ca", "bcb"]', 'expected_output': 'true'},
        {'input': '"deccecdcab"\n["adba", "beae", "debcc", "a", "e", "dccdb", "ee"]', 'expected_output': 'false'},
        {'input': '"acccddecdde"\n["dbda", "cdde", "cc", "a"]', 'expected_output': 'true'},
        {'input': '"adbba"\n["cb", "dbba", "eeaca", "d", "a"]', 'expected_output': 'true'},
        {'input': '"ddca"\n["acda", "d", "ca", "b"]', 'expected_output': 'true'},
        {'input': '"abceddaaeddaabeddaabaeddaa"\n["eddaa", "b", "cca", "ba", "ec", "debc", "abc"]', 'expected_output': 'true'},
        {'input': '""\n["cad", "babd", "bbcb", "cc", "c", "ec"]', 'expected_output': 'true'},
        {'input': '"cbeedecbdbcccdcbeedec"\n["cb", "c", "cbdb", "ccdcb", "eede", "d"]', 'expected_output': 'true'},
        {'input': '"eaaeabceacc"\n["be", "b", "abdcd", "baccb", "c"]', 'expected_output': 'false'},
        {'input': '"aadacaccacaccaadaad"\n["aad", "acacc", "ec"]', 'expected_output': 'true'},
        {'input': '""\n["ceea", "dd", "d"]', 'expected_output': 'true'},
        {'input': '"beeeedeaeaaaabebe"\n["a", "bca", "adbc", "bced", "eac", "d"]', 'expected_output': 'false'},
        {'input': '"dcbbdcbb"\n["dcbb", "adcbb"]', 'expected_output': 'true'},
        {'input': '"daccbbbbecbedcbaeebe"\n["aebb", "a", "eaeee", "edad", "c", "abeda", "acee", "e"]', 'expected_output': 'false'},
        {'input': '"aaaaaaaaaaaaaa"\n["aa"]', 'expected_output': 'true'},
        {'input': '"bdccdeaceacabdcacaeceac"\n["a", "acaec", "cd", "eac", "bdc"]', 'expected_output': 'true'},
        {'input': '"cbccbdddacbbdddacb"\n["eed", "ddacb", "bc", "eaea", "c", "bd"]', 'expected_output': 'true'},
        {'input': '""\n["adebe", "ae", "eade", "dedbc", "eb", "dedb"]', 'expected_output': 'true'},
        {'input': '"cadbbccecadbeacad"\n["bec", "cad", "c", "dd", "bbcce", "ec", "bea", "edd"]', 'expected_output': 'true'},
        {'input': '"bacacecc"\n["eebae", "dc", "ecc", "cbbc", "b", "aeabc", "edeec", "ac"]', 'expected_output': 'true'},
        {'input': '""\n["cecc", "b", "aeeed", "dcc", "eaec", "eec"]', 'expected_output': 'true'},
        {'input': '"addbdcedbdcbcbeaaeba"\n["a", "dbdc", "e", "c", "bcbe", "ad", "aea", "aaeb"]', 'expected_output': 'true'},
        {'input': '"bbcbaeebeeb"\n["bb", "eeb", "ae", "cba", "aacb", "ddb", "de"]', 'expected_output': 'true'},
        {'input': '"dddd"\n["d"]', 'expected_output': 'true'},
        {'input': '"dbcabdbcabdbcabdbcabdbcabdbcab"\n["dbcab"]', 'expected_output': 'true'},
        {'input': '""\n["a", "bbd", "e"]', 'expected_output': 'true'},
        {'input': '"abcec"\n["abcec", "adeda"]', 'expected_output': 'true'},
        {'input': '""\n["a", "ebe", "cac", "cd", "e"]', 'expected_output': 'true'},
        {'input': '"bdaaec"\n["db", "a", "cabec", "ebd", "c"]', 'expected_output': 'false'},
        {'input': '"aabedaabedaabedbeb"\n["bdab", "aabed", "acdb", "beb"]', 'expected_output': 'true'},
        {'input': '"cbedbca"\n["bdd", "aacb", "bd", "d", "ca", "eaca", "cbedb"]', 'expected_output': 'true'},
        {'input': '""\n["beac", "bcd", "deec", "dadde", "aacae"]', 'expected_output': 'true'},
        {'input': '"cdaaee"\n["ad", "b", "d", "dbdd", "e", "cceab"]', 'expected_output': 'false'},
        {'input': '"ddbccaaabddbcce"\n["edbab", "d", "ddbcc", "aaab", "e"]', 'expected_output': 'true'},
        {'input': '"accbd"\n["accbd", "baab", "ecaaa", "cddeb", "eeddb"]', 'expected_output': 'true'},
        {'input': '""\n["dee", "cdd", "bd", "eccbd", "dca", "cca", "bca"]', 'expected_output': 'true'},
        {'input': '"bdabebdabbdabbdabebd"\n["ebd", "bdab", "dbd", "ab"]', 'expected_output': 'true'},
        {'input': '"cacacacacacaca"\n["ca"]', 'expected_output': 'true'},
        {'input': '"aeeaeedeedbededab"\n["ca", "eed", "ab", "ded", "eedbe", "aeea"]', 'expected_output': 'true'},
        {'input': '"ebedbdcbceebedebed"\n["ebed", "e", "bdcbc"]', 'expected_output': 'true'},
        {'input': '"dbdeedcecbbbcebbcebbcebbcedb"\n["dee", "bbce", "dcecb", "edbea", "ec", "db", "dbb"]', 'expected_output': 'true'},
        {'input': '"adeecbadeecbbbbadeec"\n["adeec", "b"]', 'expected_output': 'true'},
        {'input': '"decceadeccedeeea"\n["deeea", "a", "eada", "c", "decce"]', 'expected_output': 'true'},
        {'input': '"acee"\n["ace", "cde", "cd", "eadea", "e", "ccca"]', 'expected_output': 'true'},
        {'input': '"eedcdedababddcecac"\n["cbcea", "edab", "eedcd", "c", "abddc", "ecac"]', 'expected_output': 'true'},
        {'input': '"cba"\n["eea", "cbba", "d", "e", "dc", "c", "eb"]', 'expected_output': 'false'},
        {'input': '""\n["bd", "ddbc", "a", "ebb", "bdbab"]', 'expected_output': 'true'},
        {'input': '"ebedbabe"\n["d", "eb", "edaab", "be", "ed", "babe"]', 'expected_output': 'true'},
        {'input': '"adadadadadadad"\n["ad"]', 'expected_output': 'true'},
        {'input': '"cccc"\n["c"]', 'expected_output': 'true'},
        {'input': '"adadbddbddbddbdd"\n["bdd", "ad"]', 'expected_output': 'true'},
        {'input': '"ddddd"\n["d"]', 'expected_output': 'true'},
        {'input': '"deeddeedadacebabdadade"\n["d", "edde", "cebab", "dada", "de", "e"]', 'expected_output': 'true'},
        {'input': '"ebdceacadcedca"\n["cbcc", "dca", "aca", "eb", "dce", "adab"]', 'expected_output': 'true'},
        {'input': '"addbaddbaddbaddbaddbaddbaddb"\n["addb"]', 'expected_output': 'true'},
        {'input': '"abdeaecaaedeecaae"\n["b", "de", "addde", "ecaae", "ab", "a"]', 'expected_output': 'true'},
        {'input': '"bcedaabcedabcedbced"\n["bced", "a"]', 'expected_output': 'true'},
        {'input': '"eadcaddeababdeaeabbb"\n["ecbb", "b", "ec", "eaedb", "eaeeb", "dac", "bdaa"]', 'expected_output': 'false'},
        {'input': '"dddcdedbbcaaedbbdebb"\n["eb", "a", "baebb", "c"]', 'expected_output': 'false'},
        {'input': '"ccdabebe"\n["be", "ccda", "dce"]', 'expected_output': 'true'},
        {'input': '"bedabbbbbb"\n["beda", "b", "bb"]', 'expected_output': 'true'},
        {'input': '"bbbdb"\n["ecb", "bbbd", "edaca", "abdab", "b", "dc"]', 'expected_output': 'true'},
        {'input': '"edededededededed"\n["ed"]', 'expected_output': 'true'},
        {'input': '"cbdbeebccaabbd"\n["bd", "caa", "eae"]', 'expected_output': 'false'},
        {'input': '"cdcacdcaace"\n["ace", "addd", "cdca"]', 'expected_output': 'true'},
        {'input': '"dbbaedaaadbebcdeae"\n["adb", "dbdb", "bbc", "ebb", "edcb", "be", "ecbb"]', 'expected_output': 'false'},
        {'input': '"aebbedecc"\n["addd", "eacc", "d", "e"]', 'expected_output': 'false'},
        {'input': '"aaa"\n["a"]', 'expected_output': 'true'},
        {'input': '""\n["dad"]', 'expected_output': 'true'},
        {'input': '"debaa"\n["bde", "ccaaa", "a", "d", "eddb"]', 'expected_output': 'false'},
        {'input': '"cdbdbbdbdbbcdaccac"\n["cac", "d", "ededb", "cdac", "c", "dbdbb", "dee", "ee"]', 'expected_output': 'true'},
        {'input': '"cbcbcbcbcb"\n["cb"]', 'expected_output': 'true'},
        {'input': '"aedcacacddc"\n["a", "be", "eecce", "aaaee", "eeeb", "cca", "b"]', 'expected_output': 'false'},
        {'input': '"dcacaedcacaecaecae"\n["dca", "cae"]', 'expected_output': 'true'},
        {'input': '"bceeddbbbbceedbceeddbbbbceedbceed"\n["bceed", "dbbb"]', 'expected_output': 'true'},
        {'input': '"bbbbbb"\n["b"]', 'expected_output': 'true'},
        {'input': '"c"\n["ebdba", "ec", "b", "e", "ae"]', 'expected_output': 'false'},
        {'input': '"dee"\n["cded", "dee"]', 'expected_output': 'true'},
        {'input': '"edcbdacba"\n["be", "baca", "ac", "a", "cc", "ccbba"]', 'expected_output': 'false'},
        {'input': '"acb"\n["dca", "d", "debec", "acb", "bb", "ceceb", "cda"]', 'expected_output': 'true'},
        {'input': '"aabdce"\n["caea"]', 'expected_output': 'false'},
        {'input': '"cebcdadaccbcedaccbbcdadaccb"\n["daccb", "ce", "b", "bcda"]', 'expected_output': 'true'},
        {'input': '"aad"\n["ecbdd", "ceb", "dbaaa", "bbc", "ec", "beb"]', 'expected_output': 'false'},
        {'input': '"aeeababbcaeebabbccccceeea"\n["babbc", "eeea", "ddce", "bad", "a", "cc", "daee", "aee"]', 'expected_output': 'true'},
        {'input': '""\n["ccb", "ecab", "ce", "bad", "bcde", "dbdb", "cccbc", "ebace"]', 'expected_output': 'true'},
        {'input': '"eaaebcbdaeaaeababbdbabc"\n["eaae", "bcbda", "bdb", "c", "ab"]', 'expected_output': 'true'},
        {'input': '"cdcdeebdeebdbdc"\n["d", "bdc", "cbb", "cd", "eeb"]', 'expected_output': 'true'},
        {'input': '"aaddbcdadaabeab"\n["bcdbc", "cdea", "deec", "de", "b", "e"]', 'expected_output': 'false'},
        {'input': '"ddadbcadda"\n["dbca", "dda"]', 'expected_output': 'true'},
        {'input': '"aaeacaaeacabda"\n["abda", "aaeac", "aae"]', 'expected_output': 'true'},
    ]
    for offset, case in enumerate(cases[:count]):
        yield {
            "input": case["input"],
            "expected_output": case["expected_output"],
            "order_index": start_index + offset,
            "is_sample": False,
        }
