"""Auto-migrated bulk hidden test cases."""

def generate_cases(*, count: int, seed: int, start_index: int):
    del seed
    cases = [
        {'input': '"hadecfggafhgibcibdgcfhiegiaadhicacaeabaeghafgichghcdicbeeaaiaghcaagbbhafcfedhfhehfachcdfagbehffabgbhhgbhgdihibbbdieaehceefgfagagdfadcbcchachbdegdegfeicdefiagddbacbffahhffedfiacchfd"', 'expected_output': '[180]'},
        {'input': '"dd"', 'expected_output': '[2]'},
        {'input': '"hdbeecifheihdaeaaedgciccfcheadcfbcaahhfabffggeg"', 'expected_output': '[47]'},
        {'input': '"ehddccdfgeidffghbaaiiecddiieaicgafahehccegihhdbieegdhfcaeifehhagfigffeee"', 'expected_output': '[72]'},
        {'input': '"cddhhaheaddaeiaciiehgadgdfhbcfafdhhfhdfabeihchigacbibeibhhegdadiiccfceebhbgiifagihhhgeeeciiefhg"', 'expected_output': '[95]'},
        {'input': '"cbfbcadcbadcegihdgcdagihfdceehgcgddbhhbdddficfchdiaciafcgcdgcebiiggbbiedfebhibhigeibhhagfadiaacaheb"', 'expected_output': '[99]'},
        {'input': '"fdfedeehbfgcecgaiggfidcfbieeacehiebbidhbaecacdaicefbcfhhfiaceffeiccgehfh"', 'expected_output': '[72]'},
        {'input': '"idadcfchafeefibgdaedbbfdgeigfhbchahbfehififbbbcghacehbaceecafaafafcbfieibbbhieha"', 'expected_output': '[80]'},
        {'input': '"dgdah"', 'expected_output': '[3, 1, 1]'},
        {'input': '"bdb"', 'expected_output': '[3]'},
        {'input': '"aeidcffgfgdidihbadfabfhheheccdihccicccahigaabhaebaabbecfehighecdhggficgheeeicbfheagcbgchiifbihiacfbieggbfecgedfiffgfffideddfhibhfbffcbhdaidhdcgeaaciafabbcigbbghacgaahbd"', 'expected_output': '[168]'},
        {'input': '"dghihgifbea"', 'expected_output': '[1, 6, 1, 1, 1, 1]'},
        {'input': '"iccdfidcifgeighehdfgbbcbahcahbcadaeeaiehdhhfhffhbaiaegiigdaedbdfdcdcche"', 'expected_output': '[71]'},
        {'input': '"hgibdeegigiadaedadbgcaafhgabgiehabcciceieghahbifbbhafacfhgiggfddbdbbhbefbechb"', 'expected_output': '[77]'},
        {'input': '"cgdegafeeecdhgdhicggbdfbbhdciifbdhaeiacbhecdbddiediiedhddfifiedgcccdefahifbaaahbbcfdhgdgegeih"', 'expected_output': '[93]'},
        {'input': '"hegdhcahadeacdiiiahhgafgdghghgiabaicacfgifadfhiabdibciaeafhggafghchdbce"', 'expected_output': '[71]'},
        {'input': '"eaefghhcfdehbhffhgiaaedchbaiefcebfedbihheadbbhgcfehcdbbdibediciebfeihfbccddeabbaegegbdahafahbdciec"', 'expected_output': '[98]'},
        {'input': '"daahaibiafhefhhheidbfeiacbcfdadghfheigiaidfbggbbaibbdbegdhagffiabcaaaicccbbaahdidadiagbiae"', 'expected_output': '[90]'},
        {'input': '"ffhdccdbab"', 'expected_output': '[2, 1, 4, 3]'},
        {'input': '"gghefahfefddacahaahcbcibabaabgdehaehfadhgdbcghceaffiihhiibcfgggeghghhigghfcggeigfdhfhgfdebihaefadgfhafgaheccgaibii"', 'expected_output': '[114]'},
        {'input': '"cdgfefaigbcihbhgbacdicfhddcgfahacbihhhaebebbcdichgfhbbeaeacchahieiichbhiacfbedccegibhdgecbbhgbfgccfbcgcghiffccddddbfbibhiaeighedgfeeahdeaicecicibicccbegecbcggdibdiegfifbbaafaceabf"', 'expected_output': '[179]'},
        {'input': '"chceidbbdbbicebagbcaeifagbhfibbiidibehfahchihabhbddcieadchehiiidciiacigbifeifecddhhdadbgihhdgdaccacfdfgeabcfdgfehfhhhchgaaghicafbiadbhgcadgcbaacifffbaecdhgacg"', 'expected_output': '[158]'},
        {'input': '"ihdgahiiebhcbeehecidhcaefiiahcgcdfigdfccbaediiceigdgihgddgdaeeddafacgccbdbhhababbiagiagfhbechgfhgihbhidfffaddhbbicfcfdaieicifgghfdhdediegghagigdihhdcddegcfiehibf"', 'expected_output': '[161]'},
        {'input': '"fbabafgcibbicedffcfhcegabb"', 'expected_output': '[26]'},
        {'input': '"abeaegaheibhbcdgfibedibcbidabdebbdiddehhghiabe"', 'expected_output': '[46]'},
        {'input': '"hbachdebgcfccbdecfaabegaciicfaiiaidcgbbdcfcghecbedihbbaghafaaghbhbdddecaaccagbgbaiafghaefcdifbbeebfbeebhcdgeccibagbeaiababceegbefbcabchicbcgfbhegbibgihhbbhdgedciefefide"', 'expected_output': '[168]'},
        {'input': '"bhfdhbgidihdbfcfdcafh"', 'expected_output': '[21]'},
        {'input': '"beaebdbeibhhdghhhecddbhdgbhacighiidbhcceihceadaahbhfcfbegbhefaghbdfdbcbigiicaibaacbcdahhidadggbegbccfhechiedificdgghegiieecebdagaccdibebgbgadceecbedfaigeeechagfbfbicdiii"', 'expected_output': '[169]'},
        {'input': '"digefachdihbgebiebbfeccafieaccdhcgadgefaia"', 'expected_output': '[42]'},
        {'input': '"fedhgdfbgdcadacbihccibagebdfbcdbiaaagfffbaibbhbgciihehebbffaibbhedbadaehhaihdabfidbbdbiddadeecihfghhcafdhcbhddfichgafdcdcbadgfhfacibefgadgacbfbaiebebfhcdbdabcggihbgi"', 'expected_output': '[165]'},
        {'input': '"faacegfdiheicgcfdciebgdhcfedbeaacaegegbigcfdfbgfffgfabbgbihebfigcbgddahibbcafaageichhbgbibhbadfggdfe"', 'expected_output': '[100]'},
        {'input': '"bgbehfdgfafbabefabccffeaiiibhaafehgdcbaigfiihggfeacbchichfidgifbbdhahchfeihcdhhieaebacca"', 'expected_output': '[88]'},
        {'input': '"dedgfbhdifihgcdefcbcdaedggahfcehahbddcaadbhadgbgeeadfdgachiecgihcbdhidaegagefgfhhhighddhfheafeigiggiffihfbeghaefggcfhhciibefiibddigfcdhfiacfahadbhge"', 'expected_output': '[148]'},
        {'input': '"fhbfhfeggfeacbcdheidgbfdhebfceiiahidbfdacifeecigfcgededddhiahebdeigeagabfeafgigfabbaideiecibcfaigdciaihfecebfbcieibghhgfffebachfafigfadafcbeddbahfcgcg"', 'expected_output': '[150]'},
        {'input': '"fffgbcchcfefdecbhgfiifedidcadhchbfgeecdggbadbfafbhgbeachgefehgibchccbfdccehihaidaebiicfgdccbegfbfcghfaabgdafib"', 'expected_output': '[110]'},
        {'input': '"aiicieabecgifeeibbhaggbdbgcegdgfcfgafacbeaidiideegheichbaaigcahaicf"', 'expected_output': '[67]'},
        {'input': '"cchbifeeddhcchccdhbcehigigaeggahaihhiachicgbcbgbeadgbaeieghecahfhiibhhaffdecbfcb"', 'expected_output': '[80]'},
        {'input': '"gfaafbfdfgdachgfcacbffbfgbhibhcdiaffgbigigeibfcibggihieghchgiffegeefg"', 'expected_output': '[69]'},
        {'input': '"cefgcdgfhcgcfbfagggfbccafhcbefeiifhae"', 'expected_output': '[37]'},
        {'input': '"biiiadhcgdbcchafagedhiicddbdahhheahehfcbeagddgidbaeabbdeabahibchfhcigggcgecgdhefgei"', 'expected_output': '[83]'},
        {'input': '"eagficefgh"', 'expected_output': '[9, 1]'},
        {'input': '"gacciiiagiaghdfbiahgichigedbdegheabedgcbaeidhfeaffbgabaabcifigffbibibaahbfihegccagdcieieafeibdhiaacghd"', 'expected_output': '[102]'},
        {'input': '"cgdhceggedffbfhdefahfadfiahhahffbgegeddfcaccacieddbdafaghhiehefaaicacfcchifcbgebeddhcfgahadghhdicdeac"', 'expected_output': '[101]'},
        {'input': '"ch"', 'expected_output': '[1, 1]'},
        {'input': '"hccaedccbbeaiaehdddcdhaddhbcabehiacccihbhfbhcchahdafcbdfdidcccgccggdcbgdbeefgbbegicaafacdacaaadgeeggiefbbbchabaghgdceffbgidhibbciigbihfgfbgbfgfafgdbi"', 'expected_output': '[149]'},
        {'input': '"aagddbbbiiegbfifbdaadghhigfahgfbfbcbbehacedacaaagiifcifaiaafah"', 'expected_output': '[62]'},
        {'input': '"bffbdgichebaiiffagdifbghcifgdcfhhhdafbeheehaccehibibdgedcg"', 'expected_output': '[58]'},
        {'input': '"bbeaibechfceibbcfcdecaccbeffihiddiaabhefgcbhhghfbfabahdbf"', 'expected_output': '[57]'},
        {'input': '"g"', 'expected_output': '[1]'},
        {'input': '"fhbdiiicdifheaffbhfbicehfgadaedgcdbhadceheccbdhecabdhbgiegcbiiifghiafhfgaeiehcaidfihchhibbaebadaebfaeaidichahefgeeabebdhiad"', 'expected_output': '[123]'},
        {'input': '"hfabcdhcgcfdfchfabbaigdfhfhfhgcgeefgc"', 'expected_output': '[37]'},
        {'input': '"ahfieigedaafaegdgaagbcghchegfcddccacdhfgiefbifhcbiaeiccaifidfeiidcdhechbfhedfiebfdbdiebaedbgdggdhfbfbdfegfcfabeaghceaficcbhgcbdagficfgeehfbhhhhgcdibhafgfhieiidcebacbgdfgddfhgba"', 'expected_output': '[176]'},
        {'input': '"ggcfheicdbhbecfhbfdgfagbdcadb"', 'expected_output': '[29]'},
        {'input': '"defhgbbcaigiddficadffdfcgaciibebieedbgibaddfcficaidfcaaddgaahffhfdbhgcghgeaaceaehhgebibiihebaadaidfd"', 'expected_output': '[100]'},
        {'input': '"ciabbhdfdbdbeahaeagf"', 'expected_output': '[1, 1, 18]'},
        {'input': '"bdegaggbeegcaegciighefgdahaefiibdefibfhdaadabacdgfhiehgafacbefbcfcdbaeieegbifcegfddcigiebiagedhhbacadiehgaahacdbfffafeedbbeicibeidhaibifhachbggdhdgifdaagaihgcgchdcidagbihffiic"', 'expected_output': '[175]'},
        {'input': '"ecgefehcegdigidiaggdgahhdcebgbidcdfhageaeibiaeifhcfhaececihad"', 'expected_output': '[61]'},
        {'input': '"abcbeheiacheahihfcgafaffidbgagecagbeaedd"', 'expected_output': '[40]'},
        {'input': '"dabhhecbehdeggdcafhaeeghgbigibgiefdhbfafibbgeahbadcdbeehiihgbddcaacefcibahffidhgfc"', 'expected_output': '[82]'},
        {'input': '"ehchfgeifghieihehfbecddhaiddadbigfcbfdeebiffaiggaiabhfaheghfegdffbbbcadeidhbifebddbcbebgceeaeihbahefaiiaicchdaefcicdhciffgfghiiiaihgegbahfcgcecdbcdfcghdgcfcgfacacabfaidiiai"', 'expected_output': '[172]'},
        {'input': '"bcbhiiffgagbghgaihciicaibebbbiaeheaeihccfaehdbbaaeaghacbfafffadbhfbcigdbgedchdchcfcacidbdbaefcf"', 'expected_output': '[95]'},
        {'input': '"decchheabfebbbgchgibhhhdigahhcfhfdacibdcbdgbbgefdegcedcdacdggdedbffbdiceadghchebbgfhfhifdebiahaehgbcbcabcdgfachgacbhehbfdcegdbaahegdabieibccfhcfhgfiiiedbced"', 'expected_output': '[156]'},
        {'input': '"eeecgdaghcbffdgbhdgdaggafcgiaiffachhaabegiefffeddbbefcdaabeeicedieiegheidbhgbbhhcecefaghfhiefhagfegfcaiegaddeggdfaheghcfdiihadebcfdaiaf"', 'expected_output': '[135]'},
        {'input': '"igcgdcbhadfidfgbbaaccidehacggeaehgffadeggffhahdcchieiehghdihghaeghdehggegaddadhhhihgcacghifaehagbgeifchcaaddghdfdadchgbhhiebbgebdbefegidghfiigibiidegdgbcaghfhcfehihdgaddhggbia"', 'expected_output': '[175]'},
        {'input': '"bgadcgegibfcebhfbehhgggdicb"', 'expected_output': '[27]'},
        {'input': '"aacciggfgcbdchcgecedcideaacebcaedceabigedgehchhhgadeabccecacaehchchegfiigidhcbeiidhefaeedifhiegeaadbdbhhfdeaccidegbaggfcbcfffgbccabcegcheagieedeachcgaeffceigchafbfbeefbce"', 'expected_output': '[170]'},
        {'input': '"gfceehfedafccfeffghdafdebaagfcfebgafabbedbieaddcfiiedadbceebhfdhfbebifbiheeggdfdahbegdbcafdbfbhcbhggdbefhgaaadbgegcchhbci"', 'expected_output': '[121]'},
        {'input': '"iighiedfgefhfdefiihgicdcchdigdgahhfcbgiicfgfdhcbebabhdhbighddcicadhhgiaihcfhedebiafhbabigidafihadhbeaecebegebgdafedbbeafh"', 'expected_output': '[121]'},
        {'input': '"cefachbeccheafebheihiedfffahdcfahgafdeagedghchccgibaccffgcdaibbhaafiihgbiebaghhebddehbibcddbhi"', 'expected_output': '[94]'},
        {'input': '"ehcedicbgaiibcaahhhebifcdfgfbe"', 'expected_output': '[30]'},
        {'input': '"ifhbdebafegifeggfahiagbhdfagagaehiigehaihfahhfhdedahahhbbddchihedbfbichheihicicdcfhebggfdihaciagabbggaiedabaceeghieii"', 'expected_output': '[117]'},
        {'input': '"fgaahfacbccaicggdhgceiieiebeeceefieccicigbchbabbibecfhadfdebhhbahedfgcichdiciidiidhaigbheiec"', 'expected_output': '[92]'},
        {'input': '"ehifgccegbgibieabchagbadggggbadefcaaagddaggfhbgacdighheaaebaecegedfbifaabfefgbbdbbceecdafbdahbdaehiiiiffehagdahh"', 'expected_output': '[112]'},
        {'input': '"bgiehfbcediagdbbaaccddhcddgahbbfehahigbddccfffhbheggbecdbcibdfbbcbccdibcihgfhaadicagffh"', 'expected_output': '[87]'},
        {'input': '"gfaffaffcddhadhdcddgfdchiigfhbghhgaeeadaihdebbfbcdgcbihbcdchbhehfggadbbd"', 'expected_output': '[72]'},
        {'input': '"efgbbgeecgicifeddecab"', 'expected_output': '[21]'},
        {'input': '"cgcbbfchgiidbdaghchcfc"', 'expected_output': '[22]'},
        {'input': '"egbaecgcecadgcbeghfeciifghadeacheegicgedidficigiegdfahhbeghicaihcahgaeihdghfcgfhfbacfdeffggagdbicdbidcaegfeidahbedgabacfchbgdhihgfdbedcafefgagbbgbfebbafgggfegbeedfdgdgba"', 'expected_output': '[169]'},
        {'input': '"bccefgiaifdbaebibhhcbfahhceiiidcccbigdggidbdcbgfiigcdcbbcfaceffdcigdhaeaeadfcdhhgdgechadhihaihaiacgbcaiadfichgaghgehdggeh"', 'expected_output': '[121]'},
        {'input': '"ecfgcfhdgfihbffgfdbhhhbibbahehhfchighefhdfaibgcaaibhgdfcabgiaddgichbbeefcifafhhdhgbegcbffghhcfhcgghefegihg"', 'expected_output': '[106]'},
        {'input': '"ffhigchbfibabagdchhfcibicafifgeafchdbgediffcgcfebcbgiceafcdhidceiiaedfddbfacedcbfchiiah"', 'expected_output': '[87]'},
        {'input': '"hcibcedcbacehbehfaabecbdcecbggeehgfafbfgfficfddiebfbcigaggdffhbdacdfcgceigechgdccghcieccbeagigdeagiadcigedeie"', 'expected_output': '[109]'},
        {'input': '"bbadgffddigiihbegebffehcdeegiiiiiidbgaff"', 'expected_output': '[40]'},
        {'input': '"fgiccafccdbacdgfiaiidbdcecafgeeeiabcfgagebechbbdechbchgadeccfgchecdabbcfachgdebbhiagchfeiccahhgchgcdfbg"', 'expected_output': '[103]'},
        {'input': '"edbbgdceidcdddahfehahhbaadcdfbebdbibcfifhhaahcchai"', 'expected_output': '[50]'},
        {'input': '"dehbdifibgehdhgbihiebhccfaibhgeadibaadbfdfdfgfgefddifdgcaecgggchaghceefeccbfbcecfhdhgiggieeabdfhhcdicgbafgeacbbadcbaihabehbceeffadiddaeecefbgagcddcdhdeddchhdbbiaecfgbf"', 'expected_output': '[167]'},
        {'input': '"gdeiaaghgaadbcahcaahdibbehagiahgiafiiebchdhfigibafaaefihcebechabchhhhhbhbbgbiehdgbhdheicdeefghacdffeadfbggfdbfgifhdd"', 'expected_output': '[116]'},
        {'input': '"feiefhdcbbgaheffdecgabehaiiegcdbbgdefgfageheciadcfeecifgcdghicfegbiifiicaafdbfcficefdaaedccefgc"', 'expected_output': '[95]'},
        {'input': '"gagbabideaeicccgfefhefecehegihgfegacgdaehibgdgagibcfgcggicdfgedieebcgiigeaffggfbggaeghgciacccfibdehahfgfgheghcaiehidgdeefacfbbab"', 'expected_output': '[128]'},
        {'input': '"dbeafebgefgbffabcfibaecaadbhbeaggababdiaabfbgdadddghbeffifchhdfcedeaiadagbfddeaaddcdfaebaefebabcgfcafagciagfdigibhbcdc"', 'expected_output': '[118]'},
        {'input': '"bgiiggffagbchbcdfbagcifcidabacihdfgchcacbfgegbgbicggehfdgdihdhihbddffichbcghedfbcahcfddafahdgaggbdidcfccdegibddbdgfbadgcabadgidiigifigeahggefa"', 'expected_output': '[142]'},
        {'input': '"aadcfcahcabdiihacdghfffefccgffcbaccabgchdeec"', 'expected_output': '[44]'},
        {'input': '"ddhdhcchiddbicefdffagihdgehfgdaegcegcdfaahehddchdffcibfcifhcibfbadgchgcecidihfeggafahegchhgeicbdiahcdhigahecedcaheecheabbgaade"', 'expected_output': '[126]'},
        {'input': '"iecfefcbghbbafidgbiefedfacfacicahgbahaih"', 'expected_output': '[40]'},
        {'input': '"bcdbeiafidcbggbiiefhfidcfbedaigbghbabbbhacdbgahhaeaihfeeadehgdhaadeiehhhaibieffbdeaeeaghfcacceafdeghgcabebcehcifeibdidahfhgihbae"', 'expected_output': '[128]'},
        {'input': '"bcbbiediaiihbh"', 'expected_output': '[14]'},
        {'input': '"fbdcffhifcecgehcghgababigfhacffiafeadfhbcgfadhdhhffddfafbcgacgcdadigdcihagadbfebaeiggbgedefffcihac"', 'expected_output': '[98]'},
        {'input': '"gaafedcefeacdfbcfdaafgbfgebfgafideifcehahhegcdbdfdagahaecbiiegdgbihgibgidbgbdhbdfdfcigcbggeegaciceccdghibeedafcdfbdbbii"', 'expected_output': '[119]'},
        {'input': '"hbeiaffghdiighbggdidaaahchbdfhhcgebahddcibbifedaehbieacgedbdaehfigehgeffgeeedhggbgfbagbgfddihehheheeffgfeahahceichgehbddeiabbfbdbeaabacgdeecgdaieaeaedgde"', 'expected_output': '[153]'},
        {'input': '"hbdchbeefebbaffacdgbidddaehggghghgebhecddbegeiiaebhcdfdcghicchgaebef"', 'expected_output': '[68]'},
        {'input': '"gfbheahigahieabggbgbbfcgacfccadfbibciccifiiafdiihdeaedgefdedeeigachabccidhdfchcfebidghdcdabegiachafchbddedfhbgiffhicaecbdebfcecihcfebigbageehcceiggb"', 'expected_output': '[148]'},
        {'input': '"dfificifdcdhccgagiegibhfccbdihcbgchbfehdhghieffghgdb"', 'expected_output': '[52]'},
        {'input': '"dddbiceadehcgacffihaeadfeecidggaiicedficciaifeifcaehechecfdhbfiafegbdcggiifhciggdgefhhchbbbdfccgagdbbhcghcahfhfeheaachffdgc"', 'expected_output': '[123]'},
        {'input': '"fddfggeaggiffhahdbdeicfgchchiabefgiahgbgdeegadbebiicihigedhhaccchiiaghbaaaehicfge"', 'expected_output': '[81]'},
        {'input': '"cghaghgicchcfeabeeeegabigbieideafh"', 'expected_output': '[34]'},
        {'input': '"hfgiihcehgdedebbgbadaegaebiegghfaaidcdgfbbbhahfbecbdieaiedhdaafaegdgifccfheedibeiachfbbhhiaiiagibgeeieaeici"', 'expected_output': '[107]'},
        {'input': '"agggebggicbedidagfgibigdcdgdicgehbcgcefcgcdcihbbbdacfaaibfeaehcifeffabebhfgchfefbfbddeagidfiecbgddbghcheeididiihegidihaecdgaecgcefcidheccbhaigecihbedic"', 'expected_output': '[151]'},
        {'input': '"icdaabefcddbhgfchcefhaddihebicgidiaifbaehigbfeeedfaiaciabbhbhabghcfihcfhecgdfibdagddgiifegaaigbhbdehbffeaedfbihefcbbbihifecff"', 'expected_output': '[125]'},
        {'input': '"eibfedaadgachhcghggadeehhfgac"', 'expected_output': '[29]'},
        {'input': '"hdcihgcccbgiiceifaffdiichdhedbcbidbdechgifdhggaahbdihbihcgcigbiedgb"', 'expected_output': '[67]'},
        {'input': '"bcidfbebbcfdhabdefigdbgcabbcbfieiihgfaahfiiicebhigddgbdbeccaebcbgcgabaiifgccccidhibaefhgeadfhbhcgcfcibgefaecefifeciiefaahhdbaahdaddfdcffhgcgiiffbfhgdgffdigbgiiibeffgbdafc"', 'expected_output': '[170]'},
        {'input': '"eebhihahefaidahaacabidccfchghghhbfaahcifeidfhhhhfbdibhgcfabaaihaecebiehiiegdeadbabefdbhgaigcdbhhfbbgagcadibaehhcihceadbecigb"', 'expected_output': '[124]'},
        {'input': '"ecicdhgbidaaachgigbiiaibeafeccfhcfedcicebgfdfedbecbbggficcddebd"', 'expected_output': '[63]'},
        {'input': '"cfbcffifcfihiihbbafdghfbafehcdhbiefhhcbidcaahhachgebdfcifbbcbihhacadbgiibbhighdbhffiggbigcfhbgfceehdgibcafhbgecibgifcbfiigdgabhficiefggh"', 'expected_output': '[136]'},
        {'input': '"ebgcaifdbfdhebbihagcifiehfiaahaadeihieefibiegbbagaefgibigeeedfcebahhbeahabfhgcebiiheihedgcefaacidecceifgibggbhcbicbighfgi"', 'expected_output': '[121]'},
        {'input': '"echcghiahbfhdehcddbiibeebdbhbchgdfecdhgbhbafaeebgbdhaghdicgdfgechahfgabgcebifegafcfdaffdaghiadfbfgbafbccgheiiahhcdaiadheegfafiehciaii"', 'expected_output': '[133]'},
        {'input': '"gfafgbacdfbaecdfdhiacedeeahiedaaiieabhecfiffihdhcfacbcadhfcgehhgbciddbaiieibdfigebdhbcahc"', 'expected_output': '[89]'},
        {'input': '"fcbagegfaefhagdah"', 'expected_output': '[17]'},
        {'input': '"aicchiadaifeccifgeaiihfchbdbeacefihhiiidgdgdbbfiidcegeaihedfbaadfcedgaigeebcbcaeeahegbahebhffgbegeiiibefhbfdfaih"', 'expected_output': '[112]'},
        {'input': '"iddidgedbhcfiieegidedgdhgfgbigafhddgfhdciebedhfideeagdiehgideehgecbicibafagichaeebgdibdiciic"', 'expected_output': '[92]'},
        {'input': '"biedbiaiciehhafbffha"', 'expected_output': '[20]'},
        {'input': '"gbefcgbhciaafhcbgfafgcaaehbcgaccedeghgaieghddcdhgccgdgfdbdggfb"', 'expected_output': '[62]'},
        {'input': '"dfdffhhdbadgdbfahddddgecigidafdaaffeadeiggbbdggbfahfgdgggbfifebfdfdgdbdbcfdfgfahf"', 'expected_output': '[81]'},
        {'input': '"fcaccaaiiahiffhaiacdgdefdecicagfbbbfeiddbegfbeigfcffghdhfegaagbecbhfchbdgagbibficgiecgfcaadiieabghhabgiaabeghiahacaeiffbdhafdaaiefdeddececcdedaccedbiegdaibcccfihbiacebbgaffcih"', 'expected_output': '[175]'},
        {'input': '"hhehddhbbfdabgbadhhcgehhfbdafegcghhgbfebfeiddcceaefdggbggibggcdcdibhaeaacgdbbecgfeabacgdccfddeidbiddfificbdcfgdbbiaiifbafiffdiihahidhabiheifahifcachcfhaaihhgafeeifgfgcfefebdb"', 'expected_output': '[174]'},
        {'input': '"gbchecefiaiffeigfibdfeebdfedaagbdggiiifahececeffcabhibfadbga"', 'expected_output': '[60]'},
        {'input': '"iigdcecffdecg"', 'expected_output': '[2, 11]'},
        {'input': '"fbdhfbhegegcchefgfdafbhdbacagdciadhdhbebadgfbbgfafebigdhcciiaefa"', 'expected_output': '[64]'},
        {'input': '"eicaheaiaibieddefbadfhehebifieghageacfigieeidffgaeihcaaabigfdcbgbiigbfiafiaieciddffgdieehddadhbchcecgcafhaifiaefeffehaiacfgaebgdhebbhbfhbdic"', 'expected_output': '[140]'},
        {'input': '"fcecidadefeddhhdd"', 'expected_output': '[17]'},
        {'input': '"ddfibbhibbhgdfaefhaghcghafifhacdfhachfcbiefdbdcchegicifcheeaigcfbccbgbbefhihdifadiecagfeegagaabheihhaabaiebfebbiah"', 'expected_output': '[114]'},
        {'input': '"efhdcbhdbcbbaf"', 'expected_output': '[1, 13]'},
        {'input': '"ehcafidfibeificebhegfhgaidheefggdhhgdhiheadfhcfaccedfeifaiiiicafbbahbcbefiagbgbdgigfbahhifbdgbigcihhifdghehfafhahihbgefeiibfdihahiideciabhcabcidbigcdihdfhibf"', 'expected_output': '[157]'},
        {'input': '"c"', 'expected_output': '[1]'},
        {'input': '"egfbahdigahbaehccfbhicefgehhchegccgcdfihfcedcgecdeahdi"', 'expected_output': '[54]'},
        {'input': '"iifdebgcefhaigbibbeeifihecaighdehbd"', 'expected_output': '[35]'},
        {'input': '"cfigcgicdacfdiifgecadhgcccgcihhffhaffhbbgdcebbaiiciacgibdaababaeaidicheidbebfdhgidiecfbfaciagdheccegcffeeiehfdhageaaiici"', 'expected_output': '[120]'},
        {'input': '"cgagffdhbhedhfdehhfegbhahddcabcgghfachdiagbebifffhfadgebifciihfhceadicicedgafghegahhhbafbdbceccaiibchcchdfceeegabefbeahfhdacfdfiaiighcdfgcehabgehiicdebbhbageagfd"', 'expected_output': '[161]'},
        {'input': '"chhfeicbhceccgcgfbc"', 'expected_output': '[19]'},
        {'input': '"hgheehabbghfidefddbeeggbhbiefeeahdgcificabdfeiigecfgbggeidgggbedbchecbfgdhfgdeaaifhbcebdfibedadhfacaafafei"', 'expected_output': '[106]'},
        {'input': '"ieggffeigaedgaicbgiecfdaeabafieehceiiiebdgghbhcihbgacg"', 'expected_output': '[54]'},
        {'input': '"gdefchfaiaaighiecbeciffeaieadaddcagifacfhdcifcabeaigbbhegbbdfgbbg"', 'expected_output': '[65]'},
        {'input': '"bihcigfbaggbhfieddeggbiacfacifdbeihiaibehhcadhgcifghfeeehecedegddhdfecifffdgcccifdeahbffdaeafccfbcbdacdfbhhcahdghfeiaicdchidfbfifgddcdegaghdccdfhidcabcc"', 'expected_output': '[152]'},
        {'input': '"hfgceaehcchicgha"', 'expected_output': '[16]'},
        {'input': '"fgbaaicaefeahhdighdaiedhiicddigeahihcbbicdididaahaidaeb"', 'expected_output': '[55]'},
        {'input': '"dgacddcehdhbedigehcafaccbhdcadgeaicegaagcafdbcfbefbfcdheiiafeciigchdcbdbdagbhbcgcagehhhhhbfbiccfcgihaegacgccifhehfdihfihdiheeeccihbdehdgdgcfibhbigbchcgebc"', 'expected_output': '[154]'},
        {'input': '"gcbe"', 'expected_output': '[1, 1, 1, 1]'},
        {'input': '"haicaghccdbdedidccahgccgiachifchcdc"', 'expected_output': '[35]'},
        {'input': '"hihcdigbiebaafgiegecdceihgfgbbfieiaidffcafceieebfcbahgdbihdggidhibgeeeadhaieacichefibaedbidia"', 'expected_output': '[93]'},
        {'input': '"igccebcigffedbieegcacgcicbbebbhcbbideahcffbhfiaebiddbacidbbabbceadcdbeddiacfbaabfabgbcieh"', 'expected_output': '[89]'},
        {'input': '"ihicficcaggcfddiedgfiabcdgafgaigcagigaceedgdffibicdbgcbbffacefhgiacahfgehcafihbhhdhabdfihbgcecagihbgigbeaafdcdeffahaebedcbbgbaciacgeaaiddegcf"', 'expected_output': '[141]'},
        {'input': '"ghcfbegbiahgadhihifccccibhgiagchccfccddbagffaccaiahebacacabeaaehdicigedafhiidgiedhhicfcefgcdigfiehefdbc"', 'expected_output': '[103]'},
        {'input': '"fifeggididddibaiedbgcieaeeagbeihhffhbgheccheeigeahegicdbdbaidbeiaeahgadgdccdhcgdffcfhdifef"', 'expected_output': '[90]'},
        {'input': '"ebhgiibcabdcaebddcgiacdhgggbaciececibficcadeffggdibhigiabaceaiccfcabahgcfgcdibdiedfiicehiabacfiabcgcbhfdgidbchccfhid"', 'expected_output': '[116]'},
        {'input': '"aecdhdbhgaifegfbhf"', 'expected_output': '[18]'},
        {'input': '"hehdhdd"', 'expected_output': '[7]'},
        {'input': '"aheabfbeahcadecedicfgihdeabfhhedgfiiegedcgecghedciagacfcdagaiccfcaeafbdffbhfifehbigedchffbhicbhhhfeeicebbcefbgibdghfhbcgbcebbbac"', 'expected_output': '[128]'},
        {'input': '"ih"', 'expected_output': '[1, 1]'},
        {'input': '"aihcdieaeeeieeeeegfdeaeadfghebiifadabhfhfbigigcebcdfiifaeigbbaafheihheagceehheaicidbheibfeadfbgabeaddiighibciaccfaggdghfhbccdeehibhbhiedefeacahhhfhcfichaghahcd"', 'expected_output': '[159]'},
        {'input': '"iceccbiahgigheaceciafibachebfaghefefeecfehdcahhfdhdaeihhcedhhahdhbibfgfgfecfahecceaffgd"', 'expected_output': '[87]'},
        {'input': '"aibbdaegfbchefiiccgeiiaffhiacghdf"', 'expected_output': '[33]'},
        {'input': '"aabigebgedhfghcdfdbfdegedaafdiiebfebefhbiaheabbegaibdbfaiebcdecccaicdhcbigbbcghbhfd"', 'expected_output': '[83]'},
        {'input': '"gifadhdibhfhghbdhbgffbbhdfeabagcfigif"', 'expected_output': '[37]'},
        {'input': '"ihdfbbfeeggadddfhdgaddhfihadceaaeagcdfgbegfhfefciahaidaeebhhhdifhbegiidgcadbhhfiecdgiceafbcdbfccdbbgabhgdah"', 'expected_output': '[107]'},
        {'input': '"ifiicecifbggfdfdaihhcaifbacefhcbchfcbibiggfdchgfebabdicadbahbcfeheffahecggeeadicdcebbbhgaghfcggdihabaciecdfhghebifbabhdbbbeee"', 'expected_output': '[125]'},
        {'input': '"eedicedhcbddiffhhghieeadbefhchgffbhfheagaabfeidfddhbcggcabfbhdaiacfbggcfcigee"', 'expected_output': '[77]'},
        {'input': '"bbcfcggcaaehhhcfbgddaegcbbibhfhchhfiafggeeabghifbffgecbcfbba"', 'expected_output': '[60]'},
        {'input': '"ggidbcdgdfhiaccaddgaeffacbgeaihdhicieibiegeebcifh"', 'expected_output': '[49]'},
        {'input': '"afgdeidhcdaifiheafadggcchicgdhcigiehic"', 'expected_output': '[38]'},
        {'input': '"ihcghiaacgdiiibbchfdhcifbfbcdbgiifgbehhaidhigfedcchhdd"', 'expected_output': '[54]'},
    ]
    for offset, case in enumerate(cases[:count]):
        yield {
            "input": case["input"],
            "expected_output": case["expected_output"],
            "order_index": start_index + offset,
            "is_sample": False,
        }
