"""Auto-migrated bulk hidden test cases."""

def generate_cases(*, count: int, seed: int, start_index: int):
    del seed
    cases = [
        {'input': '"3e+7"', 'expected_output': 'true'},
        {'input': '"+6e-1"', 'expected_output': 'true'},
        {'input': '"53.5e93"', 'expected_output': 'true'},
        {'input': '"-123.456e789"', 'expected_output': 'true'},
        {'input': '"abc"', 'expected_output': 'false'},
        {'input': '"1a"', 'expected_output': 'false'},
        {'input': '"1e"', 'expected_output': 'false'},
        {'input': '"e3"', 'expected_output': 'false'},
        {'input': '"99e2.5"', 'expected_output': 'false'},
        {'input': '"--6"', 'expected_output': 'false'},
        {'input': '"-+3"', 'expected_output': 'false'},
        {'input': '"95a54e53"', 'expected_output': 'false'},
        {'input': '"838.360"', 'expected_output': 'true'},
        {'input': '"ey7"', 'expected_output': 'false'},
        {'input': '"375+"', 'expected_output': 'false'},
        {'input': '"2E2x.x222eb0"', 'expected_output': 'false'},
        {'input': '"637e573"', 'expected_output': 'true'},
        {'input': '"6e417"', 'expected_output': 'true'},
        {'input': '"26e98y58"', 'expected_output': 'false'},
        {'input': '" -397 "', 'expected_output': 'true'},
        {'input': '"-363e-562"', 'expected_output': 'true'},
        {'input': '"521005"', 'expected_output': 'true'},
        {'input': '"-976.551"', 'expected_output': 'true'},
        {'input': '"-452 "', 'expected_output': 'true'},
        {'input': '"+912e+965"', 'expected_output': 'true'},
        {'input': '".691"', 'expected_output': 'true'},
        {'input': '"-503e+315"', 'expected_output': 'true'},
        {'input': '"+112.350"', 'expected_output': 'true'},
        {'input': '"a.4587"', 'expected_output': 'false'},
        {'input': '".a01.090"', 'expected_output': 'false'},
        {'input': '"zx7x"', 'expected_output': 'false'},
        {'input': '".83"', 'expected_output': 'true'},
        {'input': '"64e-671"', 'expected_output': 'true'},
        {'input': '" 217  "', 'expected_output': 'true'},
        {'input': '"30e+4"', 'expected_output': 'true'},
        {'input': '"68.440"', 'expected_output': 'true'},
        {'input': '"-632.134"', 'expected_output': 'true'},
        {'input': '"  -208 "', 'expected_output': 'true'},
        {'input': '"-.826"', 'expected_output': 'true'},
        {'input': '"-418  "', 'expected_output': 'true'},
        {'input': '" -478"', 'expected_output': 'true'},
        {'input': '".341"', 'expected_output': 'true'},
        {'input': '"333185"', 'expected_output': 'true'},
        {'input': '"-661137"', 'expected_output': 'true'},
        {'input': '"12e-657"', 'expected_output': 'true'},
        {'input': '"-922e400"', 'expected_output': 'true'},
        {'input': '"+666.642"', 'expected_output': 'true'},
        {'input': '"-333.61"', 'expected_output': 'true'},
        {'input': '"770.232"', 'expected_output': 'true'},
        {'input': '"  54 "', 'expected_output': 'true'},
        {'input': '"c3ac-z"', 'expected_output': 'false'},
        {'input': '"52 "', 'expected_output': 'true'},
        {'input': '".953"', 'expected_output': 'true'},
        {'input': '"445.499"', 'expected_output': 'true'},
        {'input': '"+468.686"', 'expected_output': 'true'},
        {'input': '"+89.709"', 'expected_output': 'true'},
        {'input': '"-.688"', 'expected_output': 'true'},
        {'input': '" -76"', 'expected_output': 'true'},
        {'input': '"232811"', 'expected_output': 'true'},
        {'input': '"+636.655"', 'expected_output': 'true'},
        {'input': '"bb2cx"', 'expected_output': 'false'},
        {'input': '".27"', 'expected_output': 'true'},
        {'input': '"227"', 'expected_output': 'true'},
        {'input': '"+938e+341"', 'expected_output': 'true'},
        {'input': '"3be.0"', 'expected_output': 'false'},
        {'input': '".478"', 'expected_output': 'true'},
        {'input': '"-.635"', 'expected_output': 'true'},
        {'input': '"+396e+281"', 'expected_output': 'true'},
        {'input': '"-699.849"', 'expected_output': 'true'},
        {'input': '"+698e-713"', 'expected_output': 'true'},
        {'input': '"233253"', 'expected_output': 'true'},
        {'input': '"+252e+833"', 'expected_output': 'true'},
        {'input': '" 232 "', 'expected_output': 'true'},
        {'input': '"-265134"', 'expected_output': 'true'},
        {'input': '" 151 "', 'expected_output': 'true'},
        {'input': '"0-+003e8x-"', 'expected_output': 'false'},
        {'input': '"56.203"', 'expected_output': 'true'},
        {'input': '"-489e+918"', 'expected_output': 'true'},
        {'input': '"x0yab8"', 'expected_output': 'false'},
        {'input': '"967757"', 'expected_output': 'true'},
        {'input': '"-965e-736"', 'expected_output': 'true'},
        {'input': '"-86590"', 'expected_output': 'true'},
        {'input': '"712594"', 'expected_output': 'true'},
        {'input': '"  461"', 'expected_output': 'true'},
        {'input': '"-326"', 'expected_output': 'true'},
        {'input': '"-254967"', 'expected_output': 'true'},
        {'input': '"-.778"', 'expected_output': 'true'},
        {'input': '"-.989"', 'expected_output': 'true'},
        {'input': '" -231  "', 'expected_output': 'true'},
        {'input': '"-809.961"', 'expected_output': 'true'},
        {'input': '"-94337"', 'expected_output': 'true'},
        {'input': '"447e-641"', 'expected_output': 'true'},
        {'input': '"  214 "', 'expected_output': 'true'},
        {'input': '"-540e-439"', 'expected_output': 'true'},
        {'input': '""', 'expected_output': 'false'},
        {'input': '"+123e327"', 'expected_output': 'true'},
        {'input': '"+672.664"', 'expected_output': 'true'},
        {'input': '"+.185"', 'expected_output': 'true'},
        {'input': '".12"', 'expected_output': 'true'},
        {'input': '"72.939"', 'expected_output': 'true'},
        {'input': '"+.239"', 'expected_output': 'true'},
        {'input': '"+482e-228"', 'expected_output': 'true'},
        {'input': '".42"', 'expected_output': 'true'},
        {'input': '"z8x9"', 'expected_output': 'false'},
        {'input': '"-613e+36"', 'expected_output': 'true'},
        {'input': '"  -452  "', 'expected_output': 'true'},
        {'input': '"+0.406"', 'expected_output': 'true'},
        {'input': '"1cy9"', 'expected_output': 'false'},
        {'input': '"-516172"', 'expected_output': 'true'},
        {'input': '"357e-770"', 'expected_output': 'true'},
        {'input': '"-.635"', 'expected_output': 'true'},
        {'input': '"-631.957"', 'expected_output': 'true'},
        {'input': '"+167e+4"', 'expected_output': 'true'},
        {'input': '"+.766"', 'expected_output': 'true'},
        {'input': '"06+-9"', 'expected_output': 'false'},
        {'input': '"453e+315"', 'expected_output': 'true'},
        {'input': '"766275"', 'expected_output': 'true'},
        {'input': '"a"', 'expected_output': 'false'},
        {'input': '"589193"', 'expected_output': 'true'},
        {'input': '"+817.730"', 'expected_output': 'true'},
        {'input': '"-.471"', 'expected_output': 'true'},
        {'input': '"-411758"', 'expected_output': 'true'},
        {'input': '"35e639"', 'expected_output': 'true'},
        {'input': '"521647"', 'expected_output': 'true'},
        {'input': '"  -92 "', 'expected_output': 'true'},
        {'input': '"-1b.-e64.a07"', 'expected_output': 'false'},
        {'input': '"+.238"', 'expected_output': 'true'},
        {'input': '"434466"', 'expected_output': 'true'},
        {'input': '"+810e+114"', 'expected_output': 'true'},
        {'input': '"-99722"', 'expected_output': 'true'},
        {'input': '"+209e45"', 'expected_output': 'true'},
        {'input': '"-611.489"', 'expected_output': 'true'},
        {'input': '"  408  "', 'expected_output': 'true'},
        {'input': '"-410.851"', 'expected_output': 'true'},
        {'input': '"E.y"', 'expected_output': 'false'},
        {'input': '"+.332"', 'expected_output': 'true'},
        {'input': '"725792"', 'expected_output': 'true'},
        {'input': '"52E970"', 'expected_output': 'true'},
        {'input': '"1x-52cE867a"', 'expected_output': 'false'},
        {'input': '"-203140"', 'expected_output': 'true'},
        {'input': '"+83e-83"', 'expected_output': 'true'},
        {'input': '"485"', 'expected_output': 'true'},
        {'input': '"-217327"', 'expected_output': 'true'},
        {'input': '"-485360"', 'expected_output': 'true'},
        {'input': '"  -30 "', 'expected_output': 'true'},
        {'input': '"-238347"', 'expected_output': 'true'},
        {'input': '"-842.488"', 'expected_output': 'true'},
        {'input': '"796e-314"', 'expected_output': 'true'},
        {'input': '"-170e337"', 'expected_output': 'true'},
        {'input': '"-57  "', 'expected_output': 'true'},
        {'input': '"-708661"', 'expected_output': 'true'},
        {'input': '"480.549"', 'expected_output': 'true'},
        {'input': '"+.469"', 'expected_output': 'true'},
        {'input': '"986e89"', 'expected_output': 'true'},
        {'input': '"-676276"', 'expected_output': 'true'},
        {'input': '"+939.11"', 'expected_output': 'true'},
        {'input': '"  -55"', 'expected_output': 'true'},
        {'input': '"-166.82"', 'expected_output': 'true'},
        {'input': '"3-6.9"', 'expected_output': 'false'},
        {'input': '"999.691"', 'expected_output': 'true'},
        {'input': '"701573"', 'expected_output': 'true'},
        {'input': '"-2xz3+-69xEz"', 'expected_output': 'false'},
        {'input': '"-100e-108"', 'expected_output': 'true'},
        {'input': '"+839.295"', 'expected_output': 'true'},
        {'input': '"2a2-x0E2+c"', 'expected_output': 'false'},
        {'input': '"-41519"', 'expected_output': 'true'},
        {'input': '".808"', 'expected_output': 'true'},
        {'input': '"+.476"', 'expected_output': 'true'},
        {'input': '"294339"', 'expected_output': 'true'},
        {'input': '"-.210"', 'expected_output': 'true'},
        {'input': '"-x76z1"', 'expected_output': 'false'},
        {'input': '"-743.393"', 'expected_output': 'true'},
        {'input': '"  480"', 'expected_output': 'true'},
        {'input': '"-345900"', 'expected_output': 'true'},
        {'input': '""', 'expected_output': 'false'},
        {'input': '"+447e-356"', 'expected_output': 'true'},
        {'input': '"549.441"', 'expected_output': 'true'},
        {'input': '"-c2..2z3."', 'expected_output': 'false'},
        {'input': '"+160.382"', 'expected_output': 'true'},
        {'input': '" -134"', 'expected_output': 'true'},
        {'input': '"-509852"', 'expected_output': 'true'},
        {'input': '"a-bby-.5ex4."', 'expected_output': 'false'},
        {'input': '"776570"', 'expected_output': 'true'},
        {'input': '".305"', 'expected_output': 'true'},
        {'input': '"  190  "', 'expected_output': 'true'},
        {'input': '"-151.297"', 'expected_output': 'true'},
        {'input': '"+.852"', 'expected_output': 'true'},
        {'input': '"-923389"', 'expected_output': 'true'},
        {'input': '"-42329"', 'expected_output': 'true'},
        {'input': '"+8e+403"', 'expected_output': 'true'},
        {'input': '"-386.768"', 'expected_output': 'true'},
        {'input': '"422e+56"', 'expected_output': 'true'},
        {'input': '"556.786"', 'expected_output': 'true'},
        {'input': '" -291 "', 'expected_output': 'true'},
        {'input': '"6yx8z6b294c"', 'expected_output': 'false'},
        {'input': '" -136 "', 'expected_output': 'true'},
        {'input': '"-920016"', 'expected_output': 'true'},
        {'input': '"+823e374"', 'expected_output': 'true'},
        {'input': '"-.552"', 'expected_output': 'true'},
        {'input': '"-182088"', 'expected_output': 'true'},
        {'input': '"  368"', 'expected_output': 'true'},
        {'input': '"-244319"', 'expected_output': 'true'},
        {'input': '"-"', 'expected_output': 'false'},
        {'input': '"553.926"', 'expected_output': 'true'},
        {'input': '"991.917"', 'expected_output': 'true'},
        {'input': '"-6z+079y8."', 'expected_output': 'false'},
        {'input': '"y6xE768z"', 'expected_output': 'false'},
        {'input': '".309"', 'expected_output': 'true'},
        {'input': '"424"', 'expected_output': 'true'},
        {'input': '"  -306 "', 'expected_output': 'true'},
        {'input': '" 427 "', 'expected_output': 'true'},
        {'input': '"-631582"', 'expected_output': 'true'},
        {'input': '"249"', 'expected_output': 'true'},
        {'input': '"-469e866"', 'expected_output': 'true'},
        {'input': '"676.41"', 'expected_output': 'true'},
        {'input': '"-443 "', 'expected_output': 'true'},
        {'input': '"80c4E1"', 'expected_output': 'false'},
        {'input': '"  384  "', 'expected_output': 'true'},
        {'input': '"+673e+705"', 'expected_output': 'true'},
        {'input': '"+696.788"', 'expected_output': 'true'},
        {'input': '"-77.468"', 'expected_output': 'true'},
        {'input': '"+930e-283"', 'expected_output': 'true'},
        {'input': '"+262.514"', 'expected_output': 'true'},
        {'input': '"-208291"', 'expected_output': 'true'},
        {'input': '"718e+296"', 'expected_output': 'true'},
        {'input': '"-698.447"', 'expected_output': 'true'},
        {'input': '".372"', 'expected_output': 'true'},
        {'input': '"-555.747"', 'expected_output': 'true'},
        {'input': '"+83.924"', 'expected_output': 'true'},
        {'input': '"aex86"', 'expected_output': 'false'},
        {'input': '"+758e+428"', 'expected_output': 'true'},
        {'input': '"611e360"', 'expected_output': 'true'},
        {'input': '"+.184"', 'expected_output': 'true'},
        {'input': '"161e+481"', 'expected_output': 'true'},
        {'input': '"-55 "', 'expected_output': 'true'},
        {'input': '"-453  "', 'expected_output': 'true'},
        {'input': '"-47578"', 'expected_output': 'true'},
        {'input': '"112"', 'expected_output': 'true'},
        {'input': '"-327576"', 'expected_output': 'true'},
        {'input': '"+494.501"', 'expected_output': 'true'},
        {'input': '"6bxEx432E11"', 'expected_output': 'false'},
        {'input': '"+708.405"', 'expected_output': 'true'},
        {'input': '" 235 "', 'expected_output': 'true'},
        {'input': '"+.362"', 'expected_output': 'true'},
        {'input': '"-382.309"', 'expected_output': 'true'},
        {'input': '"-.346"', 'expected_output': 'true'},
        {'input': '"213  "', 'expected_output': 'true'},
        {'input': '"-738064"', 'expected_output': 'true'},
        {'input': '".913"', 'expected_output': 'true'},
        {'input': '"+171.563"', 'expected_output': 'true'},
        {'input': '"ya+7"', 'expected_output': 'false'},
        {'input': '"-272722"', 'expected_output': 'true'},
        {'input': '"-11e909"', 'expected_output': 'true'},
        {'input': '"  -464  "', 'expected_output': 'true'},
        {'input': '"x-"', 'expected_output': 'false'},
        {'input': '"+897.860"', 'expected_output': 'true'},
        {'input': '"+171e213"', 'expected_output': 'true'},
        {'input': '"-.514"', 'expected_output': 'true'},
        {'input': '"+.640"', 'expected_output': 'true'},
        {'input': '"  1"', 'expected_output': 'true'},
        {'input': '"-184208"', 'expected_output': 'true'},
        {'input': '"282.322"', 'expected_output': 'true'},
        {'input': '"-.765"', 'expected_output': 'true'},
        {'input': '"+-ebEE34ea"', 'expected_output': 'false'},
        {'input': '"+.914"', 'expected_output': 'true'},
        {'input': '"-632.639"', 'expected_output': 'true'},
        {'input': '"+214.826"', 'expected_output': 'true'},
        {'input': '"+954e+604"', 'expected_output': 'true'},
        {'input': '"-500  "', 'expected_output': 'true'},
        {'input': '"+674e+416"', 'expected_output': 'true'},
        {'input': '"+13.592"', 'expected_output': 'true'},
        {'input': '"+.467"', 'expected_output': 'true'},
        {'input': '"-518368"', 'expected_output': 'true'},
        {'input': '"5+-x"', 'expected_output': 'false'},
        {'input': '"26.630"', 'expected_output': 'true'},
        {'input': '"+342.714"', 'expected_output': 'true'},
        {'input': '"+.288"', 'expected_output': 'true'},
        {'input': '"x+0z83e4c3"', 'expected_output': 'false'},
        {'input': '"-.828"', 'expected_output': 'true'},
        {'input': '"525.170"', 'expected_output': 'true'},
        {'input': '"-.886"', 'expected_output': 'true'},
        {'input': '"-794806"', 'expected_output': 'true'},
        {'input': '"-516.681"', 'expected_output': 'true'},
        {'input': '"+.623"', 'expected_output': 'true'},
        {'input': '"-714367"', 'expected_output': 'true'},
        {'input': '"-240 "', 'expected_output': 'true'},
        {'input': '"681729"', 'expected_output': 'true'},
        {'input': '"368e918"', 'expected_output': 'true'},
        {'input': '"+318.360"', 'expected_output': 'true'},
        {'input': '"x3"', 'expected_output': 'false'},
        {'input': '"+.996"', 'expected_output': 'true'},
        {'input': '"-670.820"', 'expected_output': 'true'},
        {'input': '" 162"', 'expected_output': 'true'},
        {'input': '"202656"', 'expected_output': 'true'},
        {'input': '" -485 "', 'expected_output': 'true'},
        {'input': '".710"', 'expected_output': 'true'},
        {'input': '"+.110"', 'expected_output': 'true'},
        {'input': '"+793.37"', 'expected_output': 'true'},
        {'input': '"+.278"', 'expected_output': 'true'},
        {'input': '"892.531"', 'expected_output': 'true'},
        {'input': '"+.226"', 'expected_output': 'true'},
        {'input': '"+767e+534"', 'expected_output': 'true'},
        {'input': '"-y482"', 'expected_output': 'false'},
        {'input': '"-780.422"', 'expected_output': 'true'},
        {'input': '"5"', 'expected_output': 'true'},
        {'input': '" 248"', 'expected_output': 'true'},
        {'input': '"+494e303"', 'expected_output': 'true'},
        {'input': '"+15.339"', 'expected_output': 'true'},
        {'input': '"+580.988"', 'expected_output': 'true'},
        {'input': '"x909"', 'expected_output': 'false'},
        {'input': '"8b4"', 'expected_output': 'false'},
        {'input': '".777"', 'expected_output': 'true'},
        {'input': '"59270080"', 'expected_output': 'true'},
        {'input': '"  -156 "', 'expected_output': 'true'},
        {'input': '"89e-146"', 'expected_output': 'true'},
        {'input': '"-917939"', 'expected_output': 'true'},
        {'input': '"109177"', 'expected_output': 'true'},
        {'input': '"-8 "', 'expected_output': 'true'},
        {'input': '"+719e-926"', 'expected_output': 'true'},
        {'input': '"-449e-960"', 'expected_output': 'true'},
        {'input': '"-237067"', 'expected_output': 'true'},
        {'input': '"+.13"', 'expected_output': 'true'},
        {'input': '"+876.274"', 'expected_output': 'true'},
        {'input': '" -362"', 'expected_output': 'true'},
        {'input': '"665e-691"', 'expected_output': 'true'},
        {'input': '".752"', 'expected_output': 'true'},
        {'input': '"-854279"', 'expected_output': 'true'},
        {'input': '"777.237"', 'expected_output': 'true'},
        {'input': '"+976.64"', 'expected_output': 'true'},
        {'input': '".7y.16c0acc"', 'expected_output': 'false'},
        {'input': '"-325"', 'expected_output': 'true'},
        {'input': '"-954112"', 'expected_output': 'true'},
        {'input': '"727e-178"', 'expected_output': 'true'},
        {'input': '"93133700-c77"', 'expected_output': 'false'},
        {'input': '"-595958"', 'expected_output': 'true'},
        {'input': '"+214e9"', 'expected_output': 'true'},
        {'input': '"902590"', 'expected_output': 'true'},
        {'input': '"88x247c20+ez"', 'expected_output': 'false'},
        {'input': '"-34074"', 'expected_output': 'true'},
        {'input': '"736414"', 'expected_output': 'true'},
        {'input': '" -329"', 'expected_output': 'true'},
        {'input': '"156.395"', 'expected_output': 'true'},
        {'input': '".441"', 'expected_output': 'true'},
        {'input': '"-204.485"', 'expected_output': 'true'},
        {'input': '"8cb-361xa"', 'expected_output': 'false'},
        {'input': '"+667e+638"', 'expected_output': 'true'},
        {'input': '"-394e1"', 'expected_output': 'true'},
        {'input': '"35+b..E9-z4"', 'expected_output': 'false'},
        {'input': '"-.42"', 'expected_output': 'true'},
        {'input': '"+813.382"', 'expected_output': 'true'},
        {'input': '"959e+896"', 'expected_output': 'true'},
        {'input': '"-218"', 'expected_output': 'true'},
        {'input': '"-440e+686"', 'expected_output': 'true'},
        {'input': '""', 'expected_output': 'false'},
        {'input': '"-2x4"', 'expected_output': 'false'},
        {'input': '"a8e"', 'expected_output': 'false'},
        {'input': '"e195-b"', 'expected_output': 'false'},
        {'input': '"  -303 "', 'expected_output': 'true'},
        {'input': '".647"', 'expected_output': 'true'},
        {'input': '"413e+808"', 'expected_output': 'true'},
        {'input': '"  298 "', 'expected_output': 'true'},
        {'input': '"-.213"', 'expected_output': 'true'},
        {'input': '"364481"', 'expected_output': 'true'},
        {'input': '"-434.797"', 'expected_output': 'true'},
        {'input': '"854687"', 'expected_output': 'true'},
        {'input': '"+536e-11"', 'expected_output': 'true'},
        {'input': '"-494180"', 'expected_output': 'true'},
        {'input': '"-.962"', 'expected_output': 'true'},
        {'input': '"-342898"', 'expected_output': 'true'},
        {'input': '"486e-513"', 'expected_output': 'true'},
        {'input': '"+241.636"', 'expected_output': 'true'},
        {'input': '"-"', 'expected_output': 'false'},
        {'input': '"-596e-508"', 'expected_output': 'true'},
        {'input': '"+.709"', 'expected_output': 'true'},
        {'input': '".241"', 'expected_output': 'true'},
        {'input': '" -74  "', 'expected_output': 'true'},
        {'input': '"-733673"', 'expected_output': 'true'},
        {'input': '"+923.907"', 'expected_output': 'true'},
        {'input': '"  78  "', 'expected_output': 'true'},
        {'input': '"478e-942"', 'expected_output': 'true'},
        {'input': '"444087"', 'expected_output': 'true'},
        {'input': '"-3zb2-3.7+"', 'expected_output': 'false'},
        {'input': '"62e-328"', 'expected_output': 'true'},
        {'input': '"3a"', 'expected_output': 'false'},
        {'input': '"+688.144"', 'expected_output': 'true'},
        {'input': '"+-2az.1"', 'expected_output': 'false'},
        {'input': '"y4xzaa-1ac"', 'expected_output': 'false'},
        {'input': '"194.572"', 'expected_output': 'true'},
        {'input': '"-649.665"', 'expected_output': 'true'},
        {'input': '"+857e-187"', 'expected_output': 'true'},
        {'input': '"-536474"', 'expected_output': 'true'},
        {'input': '"  -391  "', 'expected_output': 'true'},
        {'input': '"-3325"', 'expected_output': 'true'},
        {'input': '"+182e+380"', 'expected_output': 'true'},
        {'input': '"+ee"', 'expected_output': 'false'},
        {'input': '"793e645"', 'expected_output': 'true'},
        {'input': '"  -470"', 'expected_output': 'true'},
        {'input': '"-588935"', 'expected_output': 'true'},
        {'input': '"+903e-552"', 'expected_output': 'true'},
        {'input': '"-.870"', 'expected_output': 'true'},
        {'input': '"-870584"', 'expected_output': 'true'},
        {'input': '"E.249y3"', 'expected_output': 'false'},
        {'input': '"bz7bb17+5967"', 'expected_output': 'false'},
        {'input': '" 384 "', 'expected_output': 'true'},
        {'input': '"339e+399"', 'expected_output': 'true'},
        {'input': '"zx2813"', 'expected_output': 'false'},
        {'input': '"+.978"', 'expected_output': 'true'},
        {'input': '"69  "', 'expected_output': 'true'},
        {'input': '"763698"', 'expected_output': 'true'},
        {'input': '"e3+.0.3ee+"', 'expected_output': 'false'},
        {'input': '"-479927"', 'expected_output': 'true'},
        {'input': '"-.112"', 'expected_output': 'true'},
        {'input': '" 321 "', 'expected_output': 'true'},
        {'input': '"+826.408"', 'expected_output': 'true'},
        {'input': '" 353"', 'expected_output': 'true'},
        {'input': '"9"', 'expected_output': 'true'},
        {'input': '"-614.20"', 'expected_output': 'true'},
        {'input': '"-541943"', 'expected_output': 'true'},
        {'input': '"600933"', 'expected_output': 'true'},
        {'input': '"+283.165"', 'expected_output': 'true'},
        {'input': '"920e66"', 'expected_output': 'true'},
        {'input': '"+147e+840"', 'expected_output': 'true'},
        {'input': '"158z530aa"', 'expected_output': 'false'},
        {'input': '"-717.641"', 'expected_output': 'true'},
        {'input': '"zb099E92y+"', 'expected_output': 'false'},
        {'input': '"+562.317"', 'expected_output': 'true'},
        {'input': '"-.65"', 'expected_output': 'true'},
        {'input': '"+.160"', 'expected_output': 'true'},
        {'input': '"-299e+387"', 'expected_output': 'true'},
        {'input': '"1be+.y0Ec."', 'expected_output': 'false'},
        {'input': '"42"', 'expected_output': 'true'},
        {'input': '"216e-885"', 'expected_output': 'true'},
        {'input': '".704"', 'expected_output': 'true'},
        {'input': '".30"', 'expected_output': 'true'},
        {'input': '"  6  "', 'expected_output': 'true'},
        {'input': '"399.738"', 'expected_output': 'true'},
        {'input': '"+.530"', 'expected_output': 'true'},
        {'input': '"  -330 "', 'expected_output': 'true'},
        {'input': '"+.139"', 'expected_output': 'true'},
        {'input': '".257"', 'expected_output': 'true'},
        {'input': '"787511"', 'expected_output': 'true'},
        {'input': '"+.261"', 'expected_output': 'true'},
        {'input': '"+216e+861"', 'expected_output': 'true'},
        {'input': '"-.407"', 'expected_output': 'true'},
        {'input': '"+282.847"', 'expected_output': 'true'},
        {'input': '"+.293"', 'expected_output': 'true'},
        {'input': '"c72x9816"', 'expected_output': 'false'},
        {'input': '"+622e+952"', 'expected_output': 'true'},
        {'input': '"+890e+423"', 'expected_output': 'true'},
        {'input': '"+58+87E53967"', 'expected_output': 'false'},
        {'input': '"+587e+177"', 'expected_output': 'true'},
        {'input': '"730e-736"', 'expected_output': 'true'},
        {'input': '""', 'expected_output': 'false'},
        {'input': '"-710e95"', 'expected_output': 'true'},
        {'input': '"948.362"', 'expected_output': 'true'},
        {'input': '" -106  "', 'expected_output': 'true'},
        {'input': '"+.983"', 'expected_output': 'true'},
        {'input': '" 254  "', 'expected_output': 'true'},
        {'input': '"+877.757"', 'expected_output': 'true'},
        {'input': '"yaz535308+E"', 'expected_output': 'false'},
        {'input': '"-425449"', 'expected_output': 'true'},
        {'input': '"914e860"', 'expected_output': 'true'},
        {'input': '"-797e719"', 'expected_output': 'true'},
        {'input': '"520520"', 'expected_output': 'true'},
        {'input': '"  186"', 'expected_output': 'true'},
        {'input': '"+.372"', 'expected_output': 'true'},
        {'input': '"-413.188"', 'expected_output': 'true'},
        {'input': '".y34"', 'expected_output': 'false'},
        {'input': '"312  "', 'expected_output': 'true'},
        {'input': '"-.447"', 'expected_output': 'true'},
        {'input': '"-556700"', 'expected_output': 'true'},
        {'input': '"-985.514"', 'expected_output': 'true'},
        {'input': '"0e."', 'expected_output': 'false'},
        {'input': '"+.477"', 'expected_output': 'true'},
        {'input': '"-.926"', 'expected_output': 'true'},
        {'input': '".951"', 'expected_output': 'true'},
        {'input': '"  282"', 'expected_output': 'true'},
        {'input': '"-19060"', 'expected_output': 'true'},
        {'input': '"-.562"', 'expected_output': 'true'},
        {'input': '"-23540"', 'expected_output': 'true'},
        {'input': '"-290728"', 'expected_output': 'true'},
        {'input': '"-76.341"', 'expected_output': 'true'},
        {'input': '"zac.cy.9za"', 'expected_output': 'false'},
        {'input': '"-344033"', 'expected_output': 'true'},
        {'input': '"-872.162"', 'expected_output': 'true'},
        {'input': '"405899"', 'expected_output': 'true'},
        {'input': '"+851e296"', 'expected_output': 'true'},
        {'input': '"+810.375"', 'expected_output': 'true'},
        {'input': '"-.83"', 'expected_output': 'true'},
        {'input': '"-.933"', 'expected_output': 'true'},
        {'input': '".32"', 'expected_output': 'true'},
        {'input': '"bc6e.."', 'expected_output': 'false'},
        {'input': '"+.60"', 'expected_output': 'true'},
        {'input': '".174"', 'expected_output': 'true'},
        {'input': '"-.364"', 'expected_output': 'true'},
        {'input': '"-790e+769"', 'expected_output': 'true'},
        {'input': '"164e737"', 'expected_output': 'true'},
        {'input': '"-762725"', 'expected_output': 'true'},
        {'input': '"389037"', 'expected_output': 'true'},
        {'input': '"-707568"', 'expected_output': 'true'},
        {'input': '"-356e+456"', 'expected_output': 'true'},
        {'input': '"545e-428"', 'expected_output': 'true'},
        {'input': '"  303  "', 'expected_output': 'true'},
        {'input': '"284647"', 'expected_output': 'true'},
        {'input': '"z33+18"', 'expected_output': 'false'},
        {'input': '"-358.643"', 'expected_output': 'true'},
        {'input': '"+37.144"', 'expected_output': 'true'},
        {'input': '"238e626"', 'expected_output': 'true'},
        {'input': '"z0E95-c7"', 'expected_output': 'false'},
        {'input': '" -492"', 'expected_output': 'true'},
        {'input': '"-664e+901"', 'expected_output': 'true'},
        {'input': '"730013"', 'expected_output': 'true'},
        {'input': '"685e+779"', 'expected_output': 'true'},
        {'input': '"-588e-628"', 'expected_output': 'true'},
        {'input': '"+.263"', 'expected_output': 'true'},
        {'input': '"-980.979"', 'expected_output': 'true'},
        {'input': '"+431e193"', 'expected_output': 'true'},
        {'input': '"-427532"', 'expected_output': 'true'},
        {'input': '"-625.700"', 'expected_output': 'true'},
        {'input': '"979922"', 'expected_output': 'true'},
        {'input': '"+.994"', 'expected_output': 'true'},
        {'input': '".-149"', 'expected_output': 'false'},
        {'input': '"581632"', 'expected_output': 'true'},
        {'input': '"  -336"', 'expected_output': 'true'},
        {'input': '"-.930"', 'expected_output': 'true'},
        {'input': '"180"', 'expected_output': 'true'},
        {'input': '"65"', 'expected_output': 'true'},
        {'input': '"546266"', 'expected_output': 'true'},
        {'input': '"+853e-523"', 'expected_output': 'true'},
        {'input': '"-523e376"', 'expected_output': 'true'},
        {'input': '"+.767"', 'expected_output': 'true'},
        {'input': '"+546.667"', 'expected_output': 'true'},
        {'input': '"-747116"', 'expected_output': 'true'},
        {'input': '"262233"', 'expected_output': 'true'},
        {'input': '"875e881"', 'expected_output': 'true'},
        {'input': '"2E5zeE4x"', 'expected_output': 'false'},
        {'input': '"-687865"', 'expected_output': 'true'},
        {'input': '"-.468"', 'expected_output': 'true'},
        {'input': '".426"', 'expected_output': 'true'},
        {'input': '"+.94"', 'expected_output': 'true'},
        {'input': '"  -441 "', 'expected_output': 'true'},
        {'input': '"-969e+242"', 'expected_output': 'true'},
        {'input': '""', 'expected_output': 'false'},
        {'input': '"+513e+685"', 'expected_output': 'true'},
        {'input': '"96e-550"', 'expected_output': 'true'},
        {'input': '"451"', 'expected_output': 'true'},
        {'input': '" 360  "', 'expected_output': 'true'},
        {'input': '"-872e-612"', 'expected_output': 'true'},
        {'input': '"+260e+630"', 'expected_output': 'true'},
        {'input': '"-.345"', 'expected_output': 'true'},
        {'input': '".120"', 'expected_output': 'true'},
        {'input': '"a"', 'expected_output': 'false'},
        {'input': '"2"', 'expected_output': 'true'},
        {'input': '"+433e871"', 'expected_output': 'true'},
        {'input': '"-657184"', 'expected_output': 'true'},
        {'input': '"4e"', 'expected_output': 'false'},
        {'input': '"802e+379"', 'expected_output': 'true'},
        {'input': '"-.528"', 'expected_output': 'true'},
        {'input': '".123"', 'expected_output': 'true'},
        {'input': '"4Ex"', 'expected_output': 'false'},
        {'input': '"+975.503"', 'expected_output': 'true'},
        {'input': '"8--4b0227b7"', 'expected_output': 'false'},
        {'input': '"-.589"', 'expected_output': 'true'},
        {'input': '"-370e-10"', 'expected_output': 'true'},
        {'input': '"a-66"', 'expected_output': 'false'},
        {'input': '"-330.669"', 'expected_output': 'true'},
        {'input': '"0364ez0841"', 'expected_output': 'false'},
        {'input': '"522e-81"', 'expected_output': 'true'},
        {'input': '"114e394"', 'expected_output': 'true'},
        {'input': '"-144.839"', 'expected_output': 'true'},
        {'input': '"154870"', 'expected_output': 'true'},
        {'input': '"283.567"', 'expected_output': 'true'},
        {'input': '"711.360"', 'expected_output': 'true'},
        {'input': '"88"', 'expected_output': 'true'},
        {'input': '"25excb3ycx7"', 'expected_output': 'false'},
        {'input': '"-760.536"', 'expected_output': 'true'},
        {'input': '"+324e-914"', 'expected_output': 'true'},
        {'input': '"143e-654"', 'expected_output': 'true'},
    ]
    for offset, case in enumerate(cases[:count]):
        yield {
            "input": case["input"],
            "expected_output": case["expected_output"],
            "order_index": start_index + offset,
            "is_sample": False,
        }
